// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/Newscatcher/newscatcher-go/internal"
	big "math/big"
	time "time"
)

var (
	getAggregationCountRequestFieldQ                      = big.NewInt(1 << 0)
	getAggregationCountRequestFieldAggregationBy          = big.NewInt(1 << 1)
	getAggregationCountRequestFieldSearchIn               = big.NewInt(1 << 2)
	getAggregationCountRequestFieldPredefinedSources      = big.NewInt(1 << 3)
	getAggregationCountRequestFieldSources                = big.NewInt(1 << 4)
	getAggregationCountRequestFieldNotSources             = big.NewInt(1 << 5)
	getAggregationCountRequestFieldLang                   = big.NewInt(1 << 6)
	getAggregationCountRequestFieldNotLang                = big.NewInt(1 << 7)
	getAggregationCountRequestFieldCountries              = big.NewInt(1 << 8)
	getAggregationCountRequestFieldNotCountries           = big.NewInt(1 << 9)
	getAggregationCountRequestFieldNotAuthorName          = big.NewInt(1 << 10)
	getAggregationCountRequestFieldFrom                   = big.NewInt(1 << 11)
	getAggregationCountRequestFieldTo                     = big.NewInt(1 << 12)
	getAggregationCountRequestFieldPublishedDatePrecision = big.NewInt(1 << 13)
	getAggregationCountRequestFieldByParseDate            = big.NewInt(1 << 14)
	getAggregationCountRequestFieldSortBy                 = big.NewInt(1 << 15)
	getAggregationCountRequestFieldRankedOnly             = big.NewInt(1 << 16)
	getAggregationCountRequestFieldFromRank               = big.NewInt(1 << 17)
	getAggregationCountRequestFieldToRank                 = big.NewInt(1 << 18)
	getAggregationCountRequestFieldIsHeadline             = big.NewInt(1 << 19)
	getAggregationCountRequestFieldIsOpinion              = big.NewInt(1 << 20)
	getAggregationCountRequestFieldIsPaidContent          = big.NewInt(1 << 21)
	getAggregationCountRequestFieldParentUrl              = big.NewInt(1 << 22)
	getAggregationCountRequestFieldAllLinks               = big.NewInt(1 << 23)
	getAggregationCountRequestFieldAllDomainLinks         = big.NewInt(1 << 24)
	getAggregationCountRequestFieldAllLinksText           = big.NewInt(1 << 25)
	getAggregationCountRequestFieldWordCountMin           = big.NewInt(1 << 26)
	getAggregationCountRequestFieldWordCountMax           = big.NewInt(1 << 27)
	getAggregationCountRequestFieldPage                   = big.NewInt(1 << 28)
	getAggregationCountRequestFieldPageSize               = big.NewInt(1 << 29)
	getAggregationCountRequestFieldIncludeNlpData         = big.NewInt(1 << 30)
	getAggregationCountRequestFieldHasNlp                 = big.NewInt(1 << 31)
	getAggregationCountRequestFieldTheme                  = big.NewInt(1 << 32)
	getAggregationCountRequestFieldNotTheme               = big.NewInt(1 << 33)
	getAggregationCountRequestFieldOrgEntityName          = big.NewInt(1 << 34)
	getAggregationCountRequestFieldPerEntityName          = big.NewInt(1 << 35)
	getAggregationCountRequestFieldLocEntityName          = big.NewInt(1 << 36)
	getAggregationCountRequestFieldMiscEntityName         = big.NewInt(1 << 37)
	getAggregationCountRequestFieldTitleSentimentMin      = big.NewInt(1 << 38)
	getAggregationCountRequestFieldTitleSentimentMax      = big.NewInt(1 << 39)
	getAggregationCountRequestFieldContentSentimentMin    = big.NewInt(1 << 40)
	getAggregationCountRequestFieldContentSentimentMax    = big.NewInt(1 << 41)
	getAggregationCountRequestFieldIptcTags               = big.NewInt(1 << 42)
	getAggregationCountRequestFieldNotIptcTags            = big.NewInt(1 << 43)
	getAggregationCountRequestFieldRobotsCompliant        = big.NewInt(1 << 44)
)

type GetAggregationCountRequest struct {
	Q             Q              `json:"-" url:"q"`
	AggregationBy *AggregationBy `json:"-" url:"aggregation_by,omitempty"`
	SearchIn      *SearchIn      `json:"-" url:"search_in,omitempty"`
	// Predefined top news sources per country.
	//
	// Format: start with the word `top`, followed by the number of desired sources, and then the two-letter country code [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2).
	//
	// Multiple countries with the number of top sources can be specified as a comma-separated string.
	PredefinedSources *string `json:"-" url:"predefined_sources,omitempty"`
	// One or more news sources to narrow down the search. The format must be a domain URL. Subdomains, such as `finance.yahoo.com`, are also acceptable.To specify multiple sources, use a comma-separated string.
	Sources *string `json:"-" url:"sources,omitempty"`
	// The news sources to exclude from the search. To exclude multiple sources, use a comma-separated string.
	NotSources *string `json:"-" url:"not_sources,omitempty"`
	// The language(s) of the search. The only accepted format is the two-letter [ISO 639-1](https://en.wikipedia.org/wiki/ISO_639-1) code. To select multiple languages, use a comma-separated string.
	//
	// To learn more, see [Enumerated parameters > Language](https://www.newscatcherapi.com/docs/news-api/api-reference/enumerated-parameters#language-lang-and-not-lang).
	Lang *string `json:"-" url:"lang,omitempty"`
	// The language(s) to exclude from the search. The accepted format is the two-letter [ISO 639-1](https://en.wikipedia.org/wiki/ISO_639-1) code. To exclude multiple languages, use a comma-separated string.
	//
	// To learn more, see [Enumerated parameters > Language](https://www.newscatcherapi.com/docs/news-api/api-reference/enumerated-parameters#language-lang-and-not-lang).
	NotLang *string `json:"-" url:"not_lang,omitempty"`
	// The countries where the news publisher is located. The accepted format is the two-letter [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) code. To select multiple countries, use a comma-separated string.
	//
	// To learn more, see [Enumerated parameters > Country](https://www.newscatcherapi.com/docs/news-api/api-reference/enumerated-parameters#country-country-and-not-country).
	Countries *string `json:"-" url:"countries,omitempty"`
	// The publisher location countries to exclude from the search. The accepted format is the two-letter [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) code. To exclude multiple countries, use a comma-separated string.
	//
	// To learn more, see [Enumerated parameters > Country](https://www.newscatcherapi.com/docs/news-api/api-reference/enumerated-parameters#country-country-and-not-country).
	NotCountries *string `json:"-" url:"not_countries,omitempty"`
	// The list of author names to exclude from your search. To exclude articles by specific authors, use a comma-separated string.
	NotAuthorName          *string                 `json:"-" url:"not_author_name,omitempty"`
	From                   *From                   `json:"-" url:"from_,omitempty"`
	To                     *To                     `json:"-" url:"to_,omitempty"`
	PublishedDatePrecision *PublishedDatePrecision `json:"-" url:"published_date_precision,omitempty"`
	ByParseDate            *ByParseDate            `json:"-" url:"by_parse_date,omitempty"`
	SortBy                 *SortBy                 `json:"-" url:"sort_by,omitempty"`
	RankedOnly             *RankedOnly             `json:"-" url:"ranked_only,omitempty"`
	FromRank               *FromRank               `json:"-" url:"from_rank,omitempty"`
	ToRank                 *ToRank                 `json:"-" url:"to_rank,omitempty"`
	IsHeadline             *IsHeadline             `json:"-" url:"is_headline,omitempty"`
	IsOpinion              *IsOpinion              `json:"-" url:"is_opinion,omitempty"`
	IsPaidContent          *IsPaidContent          `json:"-" url:"is_paid_content,omitempty"`
	// The categorical URL(s) to filter your search. To filter your search by multiple categorical URLs, use a comma-separated string.
	ParentUrl *string `json:"-" url:"parent_url,omitempty"`
	// The complete URL(s) mentioned in the article. For multiple URLs, use a comma-separated string.
	//
	// For more details, see [Search by URL](https://www.newscatcherapi.com/docs/news-api/how-to/search-by-url).
	AllLinks *string `json:"-" url:"all_links,omitempty"`
	// The domain(s) mentioned in the article. For multiple domains, use a comma-separated string.
	//
	// For more details, see [Search by URL](https://www.newscatcherapi.com/docs/news-api/how-to/search-by-url).
	AllDomainLinks *string `json:"-" url:"all_domain_links,omitempty"`
	// The text content of links mentioned in the article. Searches for links where the anchor text contains the specified terms. For multiple terms, use a comma-separated string.
	//
	// **Note**: When this parameter is used, the response includes the `all_links_data` field with detailed link information.
	//
	// To learn more, see [Search by URL](https://www.newscatcherapi.com/docs/news-api/how-to/search-by-url).
	AllLinksText        *string              `json:"-" url:"all_links_text,omitempty"`
	WordCountMin        *WordCountMin        `json:"-" url:"word_count_min,omitempty"`
	WordCountMax        *WordCountMax        `json:"-" url:"word_count_max,omitempty"`
	Page                *Page                `json:"-" url:"page,omitempty"`
	PageSize            *PageSize            `json:"-" url:"page_size,omitempty"`
	IncludeNlpData      *IncludeNlpData      `json:"-" url:"include_nlp_data,omitempty"`
	HasNlp              *HasNlp              `json:"-" url:"has_nlp,omitempty"`
	Theme               *Theme               `json:"-" url:"theme,omitempty"`
	NotTheme            *NotTheme            `json:"-" url:"not_theme,omitempty"`
	OrgEntityName       *OrgEntityName       `json:"-" url:"ORG_entity_name,omitempty"`
	PerEntityName       *PerEntityName       `json:"-" url:"PER_entity_name,omitempty"`
	LocEntityName       *LocEntityName       `json:"-" url:"LOC_entity_name,omitempty"`
	MiscEntityName      *MiscEntityName      `json:"-" url:"MISC_entity_name,omitempty"`
	TitleSentimentMin   *TitleSentimentMin   `json:"-" url:"title_sentiment_min,omitempty"`
	TitleSentimentMax   *TitleSentimentMax   `json:"-" url:"title_sentiment_max,omitempty"`
	ContentSentimentMin *ContentSentimentMin `json:"-" url:"content_sentiment_min,omitempty"`
	ContentSentimentMax *ContentSentimentMax `json:"-" url:"content_sentiment_max,omitempty"`
	// Filters articles based on International Press Telecommunications Council (IPTC) media topic tags. To specify multiple IPTC tags, use a comma-separated string of tag IDs.
	//
	// **Note**: The `iptc_tags` parameter is only available in the `v3_nlp_iptc_tags` subscription plan.
	//
	// To learn more, see [IPTC Media Topic NewsCodes](https://www.iptc.org/std/NewsCodes/treeview/mediatopic/mediatopic-en-GB.html).
	IptcTags *string `json:"-" url:"iptc_tags,omitempty"`
	// Inverse of the `iptc_tags` parameter. Excludes articles based on International Press Telecommunications Council (IPTC) media topic tags. To specify multiple IPTC tags to exclude, use a comma-separated string of tag IDs.
	//
	// **Note**: The `not_iptc_tags` parameter is only available in the `v3_nlp_iptc_tags` subscription plan.
	//
	// To learn more, see [IPTC Media Topic NewsCodes](https://www.iptc.org/std/NewsCodes/treeview/mediatopic/mediatopic-en-GB.html).
	NotIptcTags     *string          `json:"-" url:"not_iptc_tags,omitempty"`
	RobotsCompliant *RobotsCompliant `json:"-" url:"robots_compliant,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetAggregationCountRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetQ sets the Q field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAggregationCountRequest) SetQ(q Q) {
	g.Q = q
	g.require(getAggregationCountRequestFieldQ)
}

// SetAggregationBy sets the AggregationBy field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAggregationCountRequest) SetAggregationBy(aggregationBy *AggregationBy) {
	g.AggregationBy = aggregationBy
	g.require(getAggregationCountRequestFieldAggregationBy)
}

// SetSearchIn sets the SearchIn field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAggregationCountRequest) SetSearchIn(searchIn *SearchIn) {
	g.SearchIn = searchIn
	g.require(getAggregationCountRequestFieldSearchIn)
}

// SetPredefinedSources sets the PredefinedSources field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAggregationCountRequest) SetPredefinedSources(predefinedSources *string) {
	g.PredefinedSources = predefinedSources
	g.require(getAggregationCountRequestFieldPredefinedSources)
}

// SetSources sets the Sources field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAggregationCountRequest) SetSources(sources *string) {
	g.Sources = sources
	g.require(getAggregationCountRequestFieldSources)
}

// SetNotSources sets the NotSources field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAggregationCountRequest) SetNotSources(notSources *string) {
	g.NotSources = notSources
	g.require(getAggregationCountRequestFieldNotSources)
}

// SetLang sets the Lang field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAggregationCountRequest) SetLang(lang *string) {
	g.Lang = lang
	g.require(getAggregationCountRequestFieldLang)
}

// SetNotLang sets the NotLang field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAggregationCountRequest) SetNotLang(notLang *string) {
	g.NotLang = notLang
	g.require(getAggregationCountRequestFieldNotLang)
}

// SetCountries sets the Countries field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAggregationCountRequest) SetCountries(countries *string) {
	g.Countries = countries
	g.require(getAggregationCountRequestFieldCountries)
}

// SetNotCountries sets the NotCountries field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAggregationCountRequest) SetNotCountries(notCountries *string) {
	g.NotCountries = notCountries
	g.require(getAggregationCountRequestFieldNotCountries)
}

// SetNotAuthorName sets the NotAuthorName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAggregationCountRequest) SetNotAuthorName(notAuthorName *string) {
	g.NotAuthorName = notAuthorName
	g.require(getAggregationCountRequestFieldNotAuthorName)
}

// SetFrom sets the From field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAggregationCountRequest) SetFrom(from *From) {
	g.From = from
	g.require(getAggregationCountRequestFieldFrom)
}

// SetTo sets the To field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAggregationCountRequest) SetTo(to *To) {
	g.To = to
	g.require(getAggregationCountRequestFieldTo)
}

// SetPublishedDatePrecision sets the PublishedDatePrecision field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAggregationCountRequest) SetPublishedDatePrecision(publishedDatePrecision *PublishedDatePrecision) {
	g.PublishedDatePrecision = publishedDatePrecision
	g.require(getAggregationCountRequestFieldPublishedDatePrecision)
}

// SetByParseDate sets the ByParseDate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAggregationCountRequest) SetByParseDate(byParseDate *ByParseDate) {
	g.ByParseDate = byParseDate
	g.require(getAggregationCountRequestFieldByParseDate)
}

// SetSortBy sets the SortBy field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAggregationCountRequest) SetSortBy(sortBy *SortBy) {
	g.SortBy = sortBy
	g.require(getAggregationCountRequestFieldSortBy)
}

// SetRankedOnly sets the RankedOnly field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAggregationCountRequest) SetRankedOnly(rankedOnly *RankedOnly) {
	g.RankedOnly = rankedOnly
	g.require(getAggregationCountRequestFieldRankedOnly)
}

// SetFromRank sets the FromRank field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAggregationCountRequest) SetFromRank(fromRank *FromRank) {
	g.FromRank = fromRank
	g.require(getAggregationCountRequestFieldFromRank)
}

// SetToRank sets the ToRank field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAggregationCountRequest) SetToRank(toRank *ToRank) {
	g.ToRank = toRank
	g.require(getAggregationCountRequestFieldToRank)
}

// SetIsHeadline sets the IsHeadline field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAggregationCountRequest) SetIsHeadline(isHeadline *IsHeadline) {
	g.IsHeadline = isHeadline
	g.require(getAggregationCountRequestFieldIsHeadline)
}

// SetIsOpinion sets the IsOpinion field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAggregationCountRequest) SetIsOpinion(isOpinion *IsOpinion) {
	g.IsOpinion = isOpinion
	g.require(getAggregationCountRequestFieldIsOpinion)
}

// SetIsPaidContent sets the IsPaidContent field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAggregationCountRequest) SetIsPaidContent(isPaidContent *IsPaidContent) {
	g.IsPaidContent = isPaidContent
	g.require(getAggregationCountRequestFieldIsPaidContent)
}

// SetParentUrl sets the ParentUrl field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAggregationCountRequest) SetParentUrl(parentUrl *string) {
	g.ParentUrl = parentUrl
	g.require(getAggregationCountRequestFieldParentUrl)
}

// SetAllLinks sets the AllLinks field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAggregationCountRequest) SetAllLinks(allLinks *string) {
	g.AllLinks = allLinks
	g.require(getAggregationCountRequestFieldAllLinks)
}

// SetAllDomainLinks sets the AllDomainLinks field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAggregationCountRequest) SetAllDomainLinks(allDomainLinks *string) {
	g.AllDomainLinks = allDomainLinks
	g.require(getAggregationCountRequestFieldAllDomainLinks)
}

// SetAllLinksText sets the AllLinksText field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAggregationCountRequest) SetAllLinksText(allLinksText *string) {
	g.AllLinksText = allLinksText
	g.require(getAggregationCountRequestFieldAllLinksText)
}

// SetWordCountMin sets the WordCountMin field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAggregationCountRequest) SetWordCountMin(wordCountMin *WordCountMin) {
	g.WordCountMin = wordCountMin
	g.require(getAggregationCountRequestFieldWordCountMin)
}

// SetWordCountMax sets the WordCountMax field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAggregationCountRequest) SetWordCountMax(wordCountMax *WordCountMax) {
	g.WordCountMax = wordCountMax
	g.require(getAggregationCountRequestFieldWordCountMax)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAggregationCountRequest) SetPage(page *Page) {
	g.Page = page
	g.require(getAggregationCountRequestFieldPage)
}

// SetPageSize sets the PageSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAggregationCountRequest) SetPageSize(pageSize *PageSize) {
	g.PageSize = pageSize
	g.require(getAggregationCountRequestFieldPageSize)
}

// SetIncludeNlpData sets the IncludeNlpData field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAggregationCountRequest) SetIncludeNlpData(includeNlpData *IncludeNlpData) {
	g.IncludeNlpData = includeNlpData
	g.require(getAggregationCountRequestFieldIncludeNlpData)
}

// SetHasNlp sets the HasNlp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAggregationCountRequest) SetHasNlp(hasNlp *HasNlp) {
	g.HasNlp = hasNlp
	g.require(getAggregationCountRequestFieldHasNlp)
}

// SetTheme sets the Theme field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAggregationCountRequest) SetTheme(theme *Theme) {
	g.Theme = theme
	g.require(getAggregationCountRequestFieldTheme)
}

// SetNotTheme sets the NotTheme field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAggregationCountRequest) SetNotTheme(notTheme *NotTheme) {
	g.NotTheme = notTheme
	g.require(getAggregationCountRequestFieldNotTheme)
}

// SetOrgEntityName sets the OrgEntityName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAggregationCountRequest) SetOrgEntityName(orgEntityName *OrgEntityName) {
	g.OrgEntityName = orgEntityName
	g.require(getAggregationCountRequestFieldOrgEntityName)
}

// SetPerEntityName sets the PerEntityName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAggregationCountRequest) SetPerEntityName(perEntityName *PerEntityName) {
	g.PerEntityName = perEntityName
	g.require(getAggregationCountRequestFieldPerEntityName)
}

// SetLocEntityName sets the LocEntityName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAggregationCountRequest) SetLocEntityName(locEntityName *LocEntityName) {
	g.LocEntityName = locEntityName
	g.require(getAggregationCountRequestFieldLocEntityName)
}

// SetMiscEntityName sets the MiscEntityName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAggregationCountRequest) SetMiscEntityName(miscEntityName *MiscEntityName) {
	g.MiscEntityName = miscEntityName
	g.require(getAggregationCountRequestFieldMiscEntityName)
}

// SetTitleSentimentMin sets the TitleSentimentMin field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAggregationCountRequest) SetTitleSentimentMin(titleSentimentMin *TitleSentimentMin) {
	g.TitleSentimentMin = titleSentimentMin
	g.require(getAggregationCountRequestFieldTitleSentimentMin)
}

// SetTitleSentimentMax sets the TitleSentimentMax field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAggregationCountRequest) SetTitleSentimentMax(titleSentimentMax *TitleSentimentMax) {
	g.TitleSentimentMax = titleSentimentMax
	g.require(getAggregationCountRequestFieldTitleSentimentMax)
}

// SetContentSentimentMin sets the ContentSentimentMin field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAggregationCountRequest) SetContentSentimentMin(contentSentimentMin *ContentSentimentMin) {
	g.ContentSentimentMin = contentSentimentMin
	g.require(getAggregationCountRequestFieldContentSentimentMin)
}

// SetContentSentimentMax sets the ContentSentimentMax field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAggregationCountRequest) SetContentSentimentMax(contentSentimentMax *ContentSentimentMax) {
	g.ContentSentimentMax = contentSentimentMax
	g.require(getAggregationCountRequestFieldContentSentimentMax)
}

// SetIptcTags sets the IptcTags field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAggregationCountRequest) SetIptcTags(iptcTags *string) {
	g.IptcTags = iptcTags
	g.require(getAggregationCountRequestFieldIptcTags)
}

// SetNotIptcTags sets the NotIptcTags field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAggregationCountRequest) SetNotIptcTags(notIptcTags *string) {
	g.NotIptcTags = notIptcTags
	g.require(getAggregationCountRequestFieldNotIptcTags)
}

// SetRobotsCompliant sets the RobotsCompliant field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAggregationCountRequest) SetRobotsCompliant(robotsCompliant *RobotsCompliant) {
	g.RobotsCompliant = robotsCompliant
	g.require(getAggregationCountRequestFieldRobotsCompliant)
}

var (
	postAggregationCountRequestFieldQ                      = big.NewInt(1 << 0)
	postAggregationCountRequestFieldAggregationBy          = big.NewInt(1 << 1)
	postAggregationCountRequestFieldSearchIn               = big.NewInt(1 << 2)
	postAggregationCountRequestFieldPredefinedSources      = big.NewInt(1 << 3)
	postAggregationCountRequestFieldSources                = big.NewInt(1 << 4)
	postAggregationCountRequestFieldNotSources             = big.NewInt(1 << 5)
	postAggregationCountRequestFieldLang                   = big.NewInt(1 << 6)
	postAggregationCountRequestFieldNotLang                = big.NewInt(1 << 7)
	postAggregationCountRequestFieldCountries              = big.NewInt(1 << 8)
	postAggregationCountRequestFieldNotCountries           = big.NewInt(1 << 9)
	postAggregationCountRequestFieldNotAuthorName          = big.NewInt(1 << 10)
	postAggregationCountRequestFieldFrom                   = big.NewInt(1 << 11)
	postAggregationCountRequestFieldTo                     = big.NewInt(1 << 12)
	postAggregationCountRequestFieldPublishedDatePrecision = big.NewInt(1 << 13)
	postAggregationCountRequestFieldByParseDate            = big.NewInt(1 << 14)
	postAggregationCountRequestFieldSortBy                 = big.NewInt(1 << 15)
	postAggregationCountRequestFieldRankedOnly             = big.NewInt(1 << 16)
	postAggregationCountRequestFieldFromRank               = big.NewInt(1 << 17)
	postAggregationCountRequestFieldToRank                 = big.NewInt(1 << 18)
	postAggregationCountRequestFieldIsHeadline             = big.NewInt(1 << 19)
	postAggregationCountRequestFieldIsOpinion              = big.NewInt(1 << 20)
	postAggregationCountRequestFieldIsPaidContent          = big.NewInt(1 << 21)
	postAggregationCountRequestFieldParentUrl              = big.NewInt(1 << 22)
	postAggregationCountRequestFieldAllLinks               = big.NewInt(1 << 23)
	postAggregationCountRequestFieldAllDomainLinks         = big.NewInt(1 << 24)
	postAggregationCountRequestFieldAllLinksText           = big.NewInt(1 << 25)
	postAggregationCountRequestFieldWordCountMin           = big.NewInt(1 << 26)
	postAggregationCountRequestFieldWordCountMax           = big.NewInt(1 << 27)
	postAggregationCountRequestFieldPage                   = big.NewInt(1 << 28)
	postAggregationCountRequestFieldPageSize               = big.NewInt(1 << 29)
	postAggregationCountRequestFieldIncludeNlpData         = big.NewInt(1 << 30)
	postAggregationCountRequestFieldHasNlp                 = big.NewInt(1 << 31)
	postAggregationCountRequestFieldTheme                  = big.NewInt(1 << 32)
	postAggregationCountRequestFieldNotTheme               = big.NewInt(1 << 33)
	postAggregationCountRequestFieldOrgEntityName          = big.NewInt(1 << 34)
	postAggregationCountRequestFieldPerEntityName          = big.NewInt(1 << 35)
	postAggregationCountRequestFieldLocEntityName          = big.NewInt(1 << 36)
	postAggregationCountRequestFieldMiscEntityName         = big.NewInt(1 << 37)
	postAggregationCountRequestFieldTitleSentimentMin      = big.NewInt(1 << 38)
	postAggregationCountRequestFieldTitleSentimentMax      = big.NewInt(1 << 39)
	postAggregationCountRequestFieldContentSentimentMin    = big.NewInt(1 << 40)
	postAggregationCountRequestFieldContentSentimentMax    = big.NewInt(1 << 41)
	postAggregationCountRequestFieldIptcTags               = big.NewInt(1 << 42)
	postAggregationCountRequestFieldNotIptcTags            = big.NewInt(1 << 43)
	postAggregationCountRequestFieldRobotsCompliant        = big.NewInt(1 << 44)
)

type PostAggregationCountRequest struct {
	Q                      Q                       `json:"q" url:"-"`
	AggregationBy          *AggregationBy          `json:"aggregation_by,omitempty" url:"-"`
	SearchIn               *SearchIn               `json:"search_in,omitempty" url:"-"`
	PredefinedSources      *PredefinedSources      `json:"predefined_sources,omitempty" url:"-"`
	Sources                *Sources                `json:"sources,omitempty" url:"-"`
	NotSources             *NotSources             `json:"not_sources,omitempty" url:"-"`
	Lang                   *Lang                   `json:"lang,omitempty" url:"-"`
	NotLang                *NotLang                `json:"not_lang,omitempty" url:"-"`
	Countries              *Countries              `json:"countries,omitempty" url:"-"`
	NotCountries           *NotCountries           `json:"not_countries,omitempty" url:"-"`
	NotAuthorName          *NotAuthorName          `json:"not_author_name,omitempty" url:"-"`
	From                   *From                   `json:"from_,omitempty" url:"-"`
	To                     *To                     `json:"to_,omitempty" url:"-"`
	PublishedDatePrecision *PublishedDatePrecision `json:"published_date_precision,omitempty" url:"-"`
	ByParseDate            *ByParseDate            `json:"by_parse_date,omitempty" url:"-"`
	SortBy                 *SortBy                 `json:"sort_by,omitempty" url:"-"`
	RankedOnly             *RankedOnly             `json:"ranked_only,omitempty" url:"-"`
	FromRank               *FromRank               `json:"from_rank,omitempty" url:"-"`
	ToRank                 *ToRank                 `json:"to_rank,omitempty" url:"-"`
	IsHeadline             *IsHeadline             `json:"is_headline,omitempty" url:"-"`
	IsOpinion              *IsOpinion              `json:"is_opinion,omitempty" url:"-"`
	IsPaidContent          *IsPaidContent          `json:"is_paid_content,omitempty" url:"-"`
	ParentUrl              *ParentUrl              `json:"parent_url,omitempty" url:"-"`
	AllLinks               *AllLinks               `json:"all_links,omitempty" url:"-"`
	AllDomainLinks         *AllDomainLinks         `json:"all_domain_links,omitempty" url:"-"`
	AllLinksText           *AllLinksText           `json:"all_links_text,omitempty" url:"-"`
	WordCountMin           *WordCountMin           `json:"word_count_min,omitempty" url:"-"`
	WordCountMax           *WordCountMax           `json:"word_count_max,omitempty" url:"-"`
	Page                   *Page                   `json:"page,omitempty" url:"-"`
	PageSize               *PageSize               `json:"page_size,omitempty" url:"-"`
	IncludeNlpData         *IncludeNlpData         `json:"include_nlp_data,omitempty" url:"-"`
	HasNlp                 *HasNlp                 `json:"has_nlp,omitempty" url:"-"`
	Theme                  *Theme                  `json:"theme,omitempty" url:"-"`
	NotTheme               *NotTheme               `json:"not_theme,omitempty" url:"-"`
	OrgEntityName          *OrgEntityName          `json:"ORG_entity_name,omitempty" url:"-"`
	PerEntityName          *PerEntityName          `json:"PER_entity_name,omitempty" url:"-"`
	LocEntityName          *LocEntityName          `json:"LOC_entity_name,omitempty" url:"-"`
	MiscEntityName         *MiscEntityName         `json:"MISC_entity_name,omitempty" url:"-"`
	TitleSentimentMin      *TitleSentimentMin      `json:"title_sentiment_min,omitempty" url:"-"`
	TitleSentimentMax      *TitleSentimentMax      `json:"title_sentiment_max,omitempty" url:"-"`
	ContentSentimentMin    *ContentSentimentMin    `json:"content_sentiment_min,omitempty" url:"-"`
	ContentSentimentMax    *ContentSentimentMax    `json:"content_sentiment_max,omitempty" url:"-"`
	IptcTags               *IptcTags               `json:"iptc_tags,omitempty" url:"-"`
	NotIptcTags            *NotIptcTags            `json:"not_iptc_tags,omitempty" url:"-"`
	RobotsCompliant        *RobotsCompliant        `json:"robots_compliant,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *PostAggregationCountRequest) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetQ sets the Q field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostAggregationCountRequest) SetQ(q Q) {
	p.Q = q
	p.require(postAggregationCountRequestFieldQ)
}

// SetAggregationBy sets the AggregationBy field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostAggregationCountRequest) SetAggregationBy(aggregationBy *AggregationBy) {
	p.AggregationBy = aggregationBy
	p.require(postAggregationCountRequestFieldAggregationBy)
}

// SetSearchIn sets the SearchIn field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostAggregationCountRequest) SetSearchIn(searchIn *SearchIn) {
	p.SearchIn = searchIn
	p.require(postAggregationCountRequestFieldSearchIn)
}

// SetPredefinedSources sets the PredefinedSources field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostAggregationCountRequest) SetPredefinedSources(predefinedSources *PredefinedSources) {
	p.PredefinedSources = predefinedSources
	p.require(postAggregationCountRequestFieldPredefinedSources)
}

// SetSources sets the Sources field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostAggregationCountRequest) SetSources(sources *Sources) {
	p.Sources = sources
	p.require(postAggregationCountRequestFieldSources)
}

// SetNotSources sets the NotSources field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostAggregationCountRequest) SetNotSources(notSources *NotSources) {
	p.NotSources = notSources
	p.require(postAggregationCountRequestFieldNotSources)
}

// SetLang sets the Lang field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostAggregationCountRequest) SetLang(lang *Lang) {
	p.Lang = lang
	p.require(postAggregationCountRequestFieldLang)
}

// SetNotLang sets the NotLang field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostAggregationCountRequest) SetNotLang(notLang *NotLang) {
	p.NotLang = notLang
	p.require(postAggregationCountRequestFieldNotLang)
}

// SetCountries sets the Countries field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostAggregationCountRequest) SetCountries(countries *Countries) {
	p.Countries = countries
	p.require(postAggregationCountRequestFieldCountries)
}

// SetNotCountries sets the NotCountries field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostAggregationCountRequest) SetNotCountries(notCountries *NotCountries) {
	p.NotCountries = notCountries
	p.require(postAggregationCountRequestFieldNotCountries)
}

// SetNotAuthorName sets the NotAuthorName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostAggregationCountRequest) SetNotAuthorName(notAuthorName *NotAuthorName) {
	p.NotAuthorName = notAuthorName
	p.require(postAggregationCountRequestFieldNotAuthorName)
}

// SetFrom sets the From field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostAggregationCountRequest) SetFrom(from *From) {
	p.From = from
	p.require(postAggregationCountRequestFieldFrom)
}

// SetTo sets the To field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostAggregationCountRequest) SetTo(to *To) {
	p.To = to
	p.require(postAggregationCountRequestFieldTo)
}

// SetPublishedDatePrecision sets the PublishedDatePrecision field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostAggregationCountRequest) SetPublishedDatePrecision(publishedDatePrecision *PublishedDatePrecision) {
	p.PublishedDatePrecision = publishedDatePrecision
	p.require(postAggregationCountRequestFieldPublishedDatePrecision)
}

// SetByParseDate sets the ByParseDate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostAggregationCountRequest) SetByParseDate(byParseDate *ByParseDate) {
	p.ByParseDate = byParseDate
	p.require(postAggregationCountRequestFieldByParseDate)
}

// SetSortBy sets the SortBy field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostAggregationCountRequest) SetSortBy(sortBy *SortBy) {
	p.SortBy = sortBy
	p.require(postAggregationCountRequestFieldSortBy)
}

// SetRankedOnly sets the RankedOnly field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostAggregationCountRequest) SetRankedOnly(rankedOnly *RankedOnly) {
	p.RankedOnly = rankedOnly
	p.require(postAggregationCountRequestFieldRankedOnly)
}

// SetFromRank sets the FromRank field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostAggregationCountRequest) SetFromRank(fromRank *FromRank) {
	p.FromRank = fromRank
	p.require(postAggregationCountRequestFieldFromRank)
}

// SetToRank sets the ToRank field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostAggregationCountRequest) SetToRank(toRank *ToRank) {
	p.ToRank = toRank
	p.require(postAggregationCountRequestFieldToRank)
}

// SetIsHeadline sets the IsHeadline field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostAggregationCountRequest) SetIsHeadline(isHeadline *IsHeadline) {
	p.IsHeadline = isHeadline
	p.require(postAggregationCountRequestFieldIsHeadline)
}

// SetIsOpinion sets the IsOpinion field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostAggregationCountRequest) SetIsOpinion(isOpinion *IsOpinion) {
	p.IsOpinion = isOpinion
	p.require(postAggregationCountRequestFieldIsOpinion)
}

// SetIsPaidContent sets the IsPaidContent field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostAggregationCountRequest) SetIsPaidContent(isPaidContent *IsPaidContent) {
	p.IsPaidContent = isPaidContent
	p.require(postAggregationCountRequestFieldIsPaidContent)
}

// SetParentUrl sets the ParentUrl field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostAggregationCountRequest) SetParentUrl(parentUrl *ParentUrl) {
	p.ParentUrl = parentUrl
	p.require(postAggregationCountRequestFieldParentUrl)
}

// SetAllLinks sets the AllLinks field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostAggregationCountRequest) SetAllLinks(allLinks *AllLinks) {
	p.AllLinks = allLinks
	p.require(postAggregationCountRequestFieldAllLinks)
}

// SetAllDomainLinks sets the AllDomainLinks field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostAggregationCountRequest) SetAllDomainLinks(allDomainLinks *AllDomainLinks) {
	p.AllDomainLinks = allDomainLinks
	p.require(postAggregationCountRequestFieldAllDomainLinks)
}

// SetAllLinksText sets the AllLinksText field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostAggregationCountRequest) SetAllLinksText(allLinksText *AllLinksText) {
	p.AllLinksText = allLinksText
	p.require(postAggregationCountRequestFieldAllLinksText)
}

// SetWordCountMin sets the WordCountMin field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostAggregationCountRequest) SetWordCountMin(wordCountMin *WordCountMin) {
	p.WordCountMin = wordCountMin
	p.require(postAggregationCountRequestFieldWordCountMin)
}

// SetWordCountMax sets the WordCountMax field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostAggregationCountRequest) SetWordCountMax(wordCountMax *WordCountMax) {
	p.WordCountMax = wordCountMax
	p.require(postAggregationCountRequestFieldWordCountMax)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostAggregationCountRequest) SetPage(page *Page) {
	p.Page = page
	p.require(postAggregationCountRequestFieldPage)
}

// SetPageSize sets the PageSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostAggregationCountRequest) SetPageSize(pageSize *PageSize) {
	p.PageSize = pageSize
	p.require(postAggregationCountRequestFieldPageSize)
}

// SetIncludeNlpData sets the IncludeNlpData field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostAggregationCountRequest) SetIncludeNlpData(includeNlpData *IncludeNlpData) {
	p.IncludeNlpData = includeNlpData
	p.require(postAggregationCountRequestFieldIncludeNlpData)
}

// SetHasNlp sets the HasNlp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostAggregationCountRequest) SetHasNlp(hasNlp *HasNlp) {
	p.HasNlp = hasNlp
	p.require(postAggregationCountRequestFieldHasNlp)
}

// SetTheme sets the Theme field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostAggregationCountRequest) SetTheme(theme *Theme) {
	p.Theme = theme
	p.require(postAggregationCountRequestFieldTheme)
}

// SetNotTheme sets the NotTheme field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostAggregationCountRequest) SetNotTheme(notTheme *NotTheme) {
	p.NotTheme = notTheme
	p.require(postAggregationCountRequestFieldNotTheme)
}

// SetOrgEntityName sets the OrgEntityName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostAggregationCountRequest) SetOrgEntityName(orgEntityName *OrgEntityName) {
	p.OrgEntityName = orgEntityName
	p.require(postAggregationCountRequestFieldOrgEntityName)
}

// SetPerEntityName sets the PerEntityName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostAggregationCountRequest) SetPerEntityName(perEntityName *PerEntityName) {
	p.PerEntityName = perEntityName
	p.require(postAggregationCountRequestFieldPerEntityName)
}

// SetLocEntityName sets the LocEntityName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostAggregationCountRequest) SetLocEntityName(locEntityName *LocEntityName) {
	p.LocEntityName = locEntityName
	p.require(postAggregationCountRequestFieldLocEntityName)
}

// SetMiscEntityName sets the MiscEntityName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostAggregationCountRequest) SetMiscEntityName(miscEntityName *MiscEntityName) {
	p.MiscEntityName = miscEntityName
	p.require(postAggregationCountRequestFieldMiscEntityName)
}

// SetTitleSentimentMin sets the TitleSentimentMin field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostAggregationCountRequest) SetTitleSentimentMin(titleSentimentMin *TitleSentimentMin) {
	p.TitleSentimentMin = titleSentimentMin
	p.require(postAggregationCountRequestFieldTitleSentimentMin)
}

// SetTitleSentimentMax sets the TitleSentimentMax field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostAggregationCountRequest) SetTitleSentimentMax(titleSentimentMax *TitleSentimentMax) {
	p.TitleSentimentMax = titleSentimentMax
	p.require(postAggregationCountRequestFieldTitleSentimentMax)
}

// SetContentSentimentMin sets the ContentSentimentMin field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostAggregationCountRequest) SetContentSentimentMin(contentSentimentMin *ContentSentimentMin) {
	p.ContentSentimentMin = contentSentimentMin
	p.require(postAggregationCountRequestFieldContentSentimentMin)
}

// SetContentSentimentMax sets the ContentSentimentMax field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostAggregationCountRequest) SetContentSentimentMax(contentSentimentMax *ContentSentimentMax) {
	p.ContentSentimentMax = contentSentimentMax
	p.require(postAggregationCountRequestFieldContentSentimentMax)
}

// SetIptcTags sets the IptcTags field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostAggregationCountRequest) SetIptcTags(iptcTags *IptcTags) {
	p.IptcTags = iptcTags
	p.require(postAggregationCountRequestFieldIptcTags)
}

// SetNotIptcTags sets the NotIptcTags field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostAggregationCountRequest) SetNotIptcTags(notIptcTags *NotIptcTags) {
	p.NotIptcTags = notIptcTags
	p.require(postAggregationCountRequestFieldNotIptcTags)
}

// SetRobotsCompliant sets the RobotsCompliant field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostAggregationCountRequest) SetRobotsCompliant(robotsCompliant *RobotsCompliant) {
	p.RobotsCompliant = robotsCompliant
	p.require(postAggregationCountRequestFieldRobotsCompliant)
}

func (p *PostAggregationCountRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler PostAggregationCountRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*p = PostAggregationCountRequest(body)
	return nil
}

func (p *PostAggregationCountRequest) MarshalJSON() ([]byte, error) {
	type embed PostAggregationCountRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

// The aggregation interval for the results.
type AggregationBy string

const (
	AggregationByDay   AggregationBy = "day"
	AggregationByHour  AggregationBy = "hour"
	AggregationByMonth AggregationBy = "month"
)

func NewAggregationByFromString(s string) (AggregationBy, error) {
	switch s {
	case "day":
		return AggregationByDay, nil
	case "hour":
		return AggregationByHour, nil
	case "month":
		return AggregationByMonth, nil
	}
	var t AggregationBy
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (a AggregationBy) Ptr() *AggregationBy {
	return &a
}

// The response model for a successful `Aggregation count` request. Response field behavior:
// - Required fields are guaranteed to be present and non-null.
// - Optional fields may be `null` or `undefined` if the data point is not presented or couldn't be extracted during processing.
var (
	aggregationCountResponseDtoFieldStatus       = big.NewInt(1 << 0)
	aggregationCountResponseDtoFieldTotalHits    = big.NewInt(1 << 1)
	aggregationCountResponseDtoFieldPage         = big.NewInt(1 << 2)
	aggregationCountResponseDtoFieldTotalPages   = big.NewInt(1 << 3)
	aggregationCountResponseDtoFieldPageSize     = big.NewInt(1 << 4)
	aggregationCountResponseDtoFieldAggregations = big.NewInt(1 << 5)
	aggregationCountResponseDtoFieldUserInput    = big.NewInt(1 << 6)
)

type AggregationCountResponseDto struct {
	// The status of the response.
	Status string `json:"status" url:"status"`
	// The total number of articles matching the search criteria.
	TotalHits int `json:"total_hits" url:"total_hits"`
	// The current page number of the results.
	Page int `json:"page" url:"page"`
	// The total number of pages available for the given search criteria.
	TotalPages int `json:"total_pages" url:"total_pages"`
	// The number of articles per page.
	PageSize int `json:"page_size" url:"page_size"`
	// The aggregation results. Can be either a dictionary or a list of dictionaries.
	Aggregations *AggregationCountResponseDtoAggregations `json:"aggregations,omitempty" url:"aggregations,omitempty"`
	UserInput    *UserInputDto                            `json:"user_input,omitempty" url:"user_input,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AggregationCountResponseDto) GetStatus() string {
	if a == nil {
		return ""
	}
	return a.Status
}

func (a *AggregationCountResponseDto) GetTotalHits() int {
	if a == nil {
		return 0
	}
	return a.TotalHits
}

func (a *AggregationCountResponseDto) GetPage() int {
	if a == nil {
		return 0
	}
	return a.Page
}

func (a *AggregationCountResponseDto) GetTotalPages() int {
	if a == nil {
		return 0
	}
	return a.TotalPages
}

func (a *AggregationCountResponseDto) GetPageSize() int {
	if a == nil {
		return 0
	}
	return a.PageSize
}

func (a *AggregationCountResponseDto) GetAggregations() *AggregationCountResponseDtoAggregations {
	if a == nil {
		return nil
	}
	return a.Aggregations
}

func (a *AggregationCountResponseDto) GetUserInput() *UserInputDto {
	if a == nil {
		return nil
	}
	return a.UserInput
}

func (a *AggregationCountResponseDto) GetExtraProperties() map[string]interface{} {
	if a == nil {
		return nil
	}
	return a.extraProperties
}

func (a *AggregationCountResponseDto) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationCountResponseDto) SetStatus(status string) {
	a.Status = status
	a.require(aggregationCountResponseDtoFieldStatus)
}

// SetTotalHits sets the TotalHits field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationCountResponseDto) SetTotalHits(totalHits int) {
	a.TotalHits = totalHits
	a.require(aggregationCountResponseDtoFieldTotalHits)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationCountResponseDto) SetPage(page int) {
	a.Page = page
	a.require(aggregationCountResponseDtoFieldPage)
}

// SetTotalPages sets the TotalPages field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationCountResponseDto) SetTotalPages(totalPages int) {
	a.TotalPages = totalPages
	a.require(aggregationCountResponseDtoFieldTotalPages)
}

// SetPageSize sets the PageSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationCountResponseDto) SetPageSize(pageSize int) {
	a.PageSize = pageSize
	a.require(aggregationCountResponseDtoFieldPageSize)
}

// SetAggregations sets the Aggregations field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationCountResponseDto) SetAggregations(aggregations *AggregationCountResponseDtoAggregations) {
	a.Aggregations = aggregations
	a.require(aggregationCountResponseDtoFieldAggregations)
}

// SetUserInput sets the UserInput field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationCountResponseDto) SetUserInput(userInput *UserInputDto) {
	a.UserInput = userInput
	a.require(aggregationCountResponseDtoFieldUserInput)
}

func (a *AggregationCountResponseDto) UnmarshalJSON(data []byte) error {
	type unmarshaler AggregationCountResponseDto
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AggregationCountResponseDto(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AggregationCountResponseDto) MarshalJSON() ([]byte, error) {
	type embed AggregationCountResponseDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *AggregationCountResponseDto) String() string {
	if a == nil {
		return "<nil>"
	}
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

// The aggregation results. Can be either a dictionary or a list of dictionaries.
type AggregationCountResponseDtoAggregations struct {
	AggregationItem     *AggregationItem
	AggregationItemList []*AggregationItem

	typ string
}

func (a *AggregationCountResponseDtoAggregations) GetAggregationItem() *AggregationItem {
	if a == nil {
		return nil
	}
	return a.AggregationItem
}

func (a *AggregationCountResponseDtoAggregations) GetAggregationItemList() []*AggregationItem {
	if a == nil {
		return nil
	}
	return a.AggregationItemList
}

func (a *AggregationCountResponseDtoAggregations) UnmarshalJSON(data []byte) error {
	valueAggregationItem := new(AggregationItem)
	if err := json.Unmarshal(data, &valueAggregationItem); err == nil {
		a.typ = "AggregationItem"
		a.AggregationItem = valueAggregationItem
		return nil
	}
	var valueAggregationItemList []*AggregationItem
	if err := json.Unmarshal(data, &valueAggregationItemList); err == nil {
		a.typ = "AggregationItemList"
		a.AggregationItemList = valueAggregationItemList
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, a)
}

func (a AggregationCountResponseDtoAggregations) MarshalJSON() ([]byte, error) {
	if a.typ == "AggregationItem" || a.AggregationItem != nil {
		return json.Marshal(a.AggregationItem)
	}
	if a.typ == "AggregationItemList" || a.AggregationItemList != nil {
		return json.Marshal(a.AggregationItemList)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", a)
}

type AggregationCountResponseDtoAggregationsVisitor interface {
	VisitAggregationItem(*AggregationItem) error
	VisitAggregationItemList([]*AggregationItem) error
}

func (a *AggregationCountResponseDtoAggregations) Accept(visitor AggregationCountResponseDtoAggregationsVisitor) error {
	if a.typ == "AggregationItem" || a.AggregationItem != nil {
		return visitor.VisitAggregationItem(a.AggregationItem)
	}
	if a.typ == "AggregationItemList" || a.AggregationItemList != nil {
		return visitor.VisitAggregationItemList(a.AggregationItemList)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", a)
}

// A single item in the aggregations array containing a collection of time-based article counts.
var (
	aggregationItemFieldAggregationCount = big.NewInt(1 << 0)
)

type AggregationItem struct {
	// Array of time frames and their corresponding article counts
	AggregationCount []*TimeFrameCount `json:"aggregation_count" url:"aggregation_count"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AggregationItem) GetAggregationCount() []*TimeFrameCount {
	if a == nil {
		return nil
	}
	return a.AggregationCount
}

func (a *AggregationItem) GetExtraProperties() map[string]interface{} {
	if a == nil {
		return nil
	}
	return a.extraProperties
}

func (a *AggregationItem) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetAggregationCount sets the AggregationCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationItem) SetAggregationCount(aggregationCount []*TimeFrameCount) {
	a.AggregationCount = aggregationCount
	a.require(aggregationItemFieldAggregationCount)
}

func (a *AggregationItem) UnmarshalJSON(data []byte) error {
	type unmarshaler AggregationItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AggregationItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AggregationItem) MarshalJSON() ([]byte, error) {
	type embed AggregationItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *AggregationItem) String() string {
	if a == nil {
		return "<nil>"
	}
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

// The response model for a failed `Aggregation count` request.
var (
	failedAggregationCountResponseDtoFieldStatus     = big.NewInt(1 << 0)
	failedAggregationCountResponseDtoFieldTotalHits  = big.NewInt(1 << 1)
	failedAggregationCountResponseDtoFieldPage       = big.NewInt(1 << 2)
	failedAggregationCountResponseDtoFieldTotalPages = big.NewInt(1 << 3)
	failedAggregationCountResponseDtoFieldPageSize   = big.NewInt(1 << 4)
	failedAggregationCountResponseDtoFieldUserInput  = big.NewInt(1 << 5)
)

type FailedAggregationCountResponseDto struct {
	// The status of the response.
	Status string `json:"status" url:"status"`
	// The total number of articles matching the search criteria.
	TotalHits int `json:"total_hits" url:"total_hits"`
	// The current page number of the results.
	Page int `json:"page" url:"page"`
	// The total number of pages available for the given search criteria.
	TotalPages int `json:"total_pages" url:"total_pages"`
	// The number of articles per page.
	PageSize  int           `json:"page_size" url:"page_size"`
	UserInput *UserInputDto `json:"user_input,omitempty" url:"user_input,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (f *FailedAggregationCountResponseDto) GetStatus() string {
	if f == nil {
		return ""
	}
	return f.Status
}

func (f *FailedAggregationCountResponseDto) GetTotalHits() int {
	if f == nil {
		return 0
	}
	return f.TotalHits
}

func (f *FailedAggregationCountResponseDto) GetPage() int {
	if f == nil {
		return 0
	}
	return f.Page
}

func (f *FailedAggregationCountResponseDto) GetTotalPages() int {
	if f == nil {
		return 0
	}
	return f.TotalPages
}

func (f *FailedAggregationCountResponseDto) GetPageSize() int {
	if f == nil {
		return 0
	}
	return f.PageSize
}

func (f *FailedAggregationCountResponseDto) GetUserInput() *UserInputDto {
	if f == nil {
		return nil
	}
	return f.UserInput
}

func (f *FailedAggregationCountResponseDto) GetExtraProperties() map[string]interface{} {
	if f == nil {
		return nil
	}
	return f.extraProperties
}

func (f *FailedAggregationCountResponseDto) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FailedAggregationCountResponseDto) SetStatus(status string) {
	f.Status = status
	f.require(failedAggregationCountResponseDtoFieldStatus)
}

// SetTotalHits sets the TotalHits field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FailedAggregationCountResponseDto) SetTotalHits(totalHits int) {
	f.TotalHits = totalHits
	f.require(failedAggregationCountResponseDtoFieldTotalHits)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FailedAggregationCountResponseDto) SetPage(page int) {
	f.Page = page
	f.require(failedAggregationCountResponseDtoFieldPage)
}

// SetTotalPages sets the TotalPages field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FailedAggregationCountResponseDto) SetTotalPages(totalPages int) {
	f.TotalPages = totalPages
	f.require(failedAggregationCountResponseDtoFieldTotalPages)
}

// SetPageSize sets the PageSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FailedAggregationCountResponseDto) SetPageSize(pageSize int) {
	f.PageSize = pageSize
	f.require(failedAggregationCountResponseDtoFieldPageSize)
}

// SetUserInput sets the UserInput field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FailedAggregationCountResponseDto) SetUserInput(userInput *UserInputDto) {
	f.UserInput = userInput
	f.require(failedAggregationCountResponseDtoFieldUserInput)
}

func (f *FailedAggregationCountResponseDto) UnmarshalJSON(data []byte) error {
	type unmarshaler FailedAggregationCountResponseDto
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*f = FailedAggregationCountResponseDto(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties
	f.rawJSON = json.RawMessage(data)
	return nil
}

func (f *FailedAggregationCountResponseDto) MarshalJSON() ([]byte, error) {
	type embed FailedAggregationCountResponseDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*f),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, f.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (f *FailedAggregationCountResponseDto) String() string {
	if f == nil {
		return "<nil>"
	}
	if len(f.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(f.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

// Represents the article count for a specific time frame.
var (
	timeFrameCountFieldTimeFrame    = big.NewInt(1 << 0)
	timeFrameCountFieldArticleCount = big.NewInt(1 << 1)
)

type TimeFrameCount struct {
	// The timestamp for the aggregation period in format "YYYY-MM-DD HH:mm:ss"
	TimeFrame time.Time `json:"time_frame" url:"time_frame"`
	// The number of articles published during this time frame
	ArticleCount int `json:"article_count" url:"article_count"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TimeFrameCount) GetTimeFrame() time.Time {
	if t == nil {
		return time.Time{}
	}
	return t.TimeFrame
}

func (t *TimeFrameCount) GetArticleCount() int {
	if t == nil {
		return 0
	}
	return t.ArticleCount
}

func (t *TimeFrameCount) GetExtraProperties() map[string]interface{} {
	if t == nil {
		return nil
	}
	return t.extraProperties
}

func (t *TimeFrameCount) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetTimeFrame sets the TimeFrame field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TimeFrameCount) SetTimeFrame(timeFrame time.Time) {
	t.TimeFrame = timeFrame
	t.require(timeFrameCountFieldTimeFrame)
}

// SetArticleCount sets the ArticleCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TimeFrameCount) SetArticleCount(articleCount int) {
	t.ArticleCount = articleCount
	t.require(timeFrameCountFieldArticleCount)
}

func (t *TimeFrameCount) UnmarshalJSON(data []byte) error {
	type embed TimeFrameCount
	var unmarshaler = struct {
		embed
		TimeFrame *internal.DateTime `json:"time_frame"`
	}{
		embed: embed(*t),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*t = TimeFrameCount(unmarshaler.embed)
	t.TimeFrame = unmarshaler.TimeFrame.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TimeFrameCount) MarshalJSON() ([]byte, error) {
	type embed TimeFrameCount
	var marshaler = struct {
		embed
		TimeFrame *internal.DateTime `json:"time_frame"`
	}{
		embed:     embed(*t),
		TimeFrame: internal.NewDateTime(t.TimeFrame),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *TimeFrameCount) String() string {
	if t == nil {
		return "<nil>"
	}
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

type GetAggregationCountResponse struct {
	AggregationCountResponseDto       *AggregationCountResponseDto
	FailedAggregationCountResponseDto *FailedAggregationCountResponseDto

	typ string
}

func (g *GetAggregationCountResponse) GetAggregationCountResponseDto() *AggregationCountResponseDto {
	if g == nil {
		return nil
	}
	return g.AggregationCountResponseDto
}

func (g *GetAggregationCountResponse) GetFailedAggregationCountResponseDto() *FailedAggregationCountResponseDto {
	if g == nil {
		return nil
	}
	return g.FailedAggregationCountResponseDto
}

func (g *GetAggregationCountResponse) UnmarshalJSON(data []byte) error {
	valueAggregationCountResponseDto := new(AggregationCountResponseDto)
	if err := json.Unmarshal(data, &valueAggregationCountResponseDto); err == nil {
		g.typ = "AggregationCountResponseDto"
		g.AggregationCountResponseDto = valueAggregationCountResponseDto
		return nil
	}
	valueFailedAggregationCountResponseDto := new(FailedAggregationCountResponseDto)
	if err := json.Unmarshal(data, &valueFailedAggregationCountResponseDto); err == nil {
		g.typ = "FailedAggregationCountResponseDto"
		g.FailedAggregationCountResponseDto = valueFailedAggregationCountResponseDto
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, g)
}

func (g GetAggregationCountResponse) MarshalJSON() ([]byte, error) {
	if g.typ == "AggregationCountResponseDto" || g.AggregationCountResponseDto != nil {
		return json.Marshal(g.AggregationCountResponseDto)
	}
	if g.typ == "FailedAggregationCountResponseDto" || g.FailedAggregationCountResponseDto != nil {
		return json.Marshal(g.FailedAggregationCountResponseDto)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", g)
}

type GetAggregationCountResponseVisitor interface {
	VisitAggregationCountResponseDto(*AggregationCountResponseDto) error
	VisitFailedAggregationCountResponseDto(*FailedAggregationCountResponseDto) error
}

func (g *GetAggregationCountResponse) Accept(visitor GetAggregationCountResponseVisitor) error {
	if g.typ == "AggregationCountResponseDto" || g.AggregationCountResponseDto != nil {
		return visitor.VisitAggregationCountResponseDto(g.AggregationCountResponseDto)
	}
	if g.typ == "FailedAggregationCountResponseDto" || g.FailedAggregationCountResponseDto != nil {
		return visitor.VisitFailedAggregationCountResponseDto(g.FailedAggregationCountResponseDto)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", g)
}

type PostAggregationCountResponse struct {
	AggregationCountResponseDto       *AggregationCountResponseDto
	FailedAggregationCountResponseDto *FailedAggregationCountResponseDto

	typ string
}

func (p *PostAggregationCountResponse) GetAggregationCountResponseDto() *AggregationCountResponseDto {
	if p == nil {
		return nil
	}
	return p.AggregationCountResponseDto
}

func (p *PostAggregationCountResponse) GetFailedAggregationCountResponseDto() *FailedAggregationCountResponseDto {
	if p == nil {
		return nil
	}
	return p.FailedAggregationCountResponseDto
}

func (p *PostAggregationCountResponse) UnmarshalJSON(data []byte) error {
	valueAggregationCountResponseDto := new(AggregationCountResponseDto)
	if err := json.Unmarshal(data, &valueAggregationCountResponseDto); err == nil {
		p.typ = "AggregationCountResponseDto"
		p.AggregationCountResponseDto = valueAggregationCountResponseDto
		return nil
	}
	valueFailedAggregationCountResponseDto := new(FailedAggregationCountResponseDto)
	if err := json.Unmarshal(data, &valueFailedAggregationCountResponseDto); err == nil {
		p.typ = "FailedAggregationCountResponseDto"
		p.FailedAggregationCountResponseDto = valueFailedAggregationCountResponseDto
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, p)
}

func (p PostAggregationCountResponse) MarshalJSON() ([]byte, error) {
	if p.typ == "AggregationCountResponseDto" || p.AggregationCountResponseDto != nil {
		return json.Marshal(p.AggregationCountResponseDto)
	}
	if p.typ == "FailedAggregationCountResponseDto" || p.FailedAggregationCountResponseDto != nil {
		return json.Marshal(p.FailedAggregationCountResponseDto)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", p)
}

type PostAggregationCountResponseVisitor interface {
	VisitAggregationCountResponseDto(*AggregationCountResponseDto) error
	VisitFailedAggregationCountResponseDto(*FailedAggregationCountResponseDto) error
}

func (p *PostAggregationCountResponse) Accept(visitor PostAggregationCountResponseVisitor) error {
	if p.typ == "AggregationCountResponseDto" || p.AggregationCountResponseDto != nil {
		return visitor.VisitAggregationCountResponseDto(p.AggregationCountResponseDto)
	}
	if p.typ == "FailedAggregationCountResponseDto" || p.FailedAggregationCountResponseDto != nil {
		return visitor.VisitFailedAggregationCountResponseDto(p.FailedAggregationCountResponseDto)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", p)
}
