// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/Newscatcher/newscatcher-go/internal"
	big "math/big"
	time "time"
)

var (
	aggregationGetRequestFieldQ                      = big.NewInt(1 << 0)
	aggregationGetRequestFieldAggregationBy          = big.NewInt(1 << 1)
	aggregationGetRequestFieldSearchIn               = big.NewInt(1 << 2)
	aggregationGetRequestFieldPredefinedSources      = big.NewInt(1 << 3)
	aggregationGetRequestFieldSources                = big.NewInt(1 << 4)
	aggregationGetRequestFieldNotSources             = big.NewInt(1 << 5)
	aggregationGetRequestFieldLang                   = big.NewInt(1 << 6)
	aggregationGetRequestFieldNotLang                = big.NewInt(1 << 7)
	aggregationGetRequestFieldCountries              = big.NewInt(1 << 8)
	aggregationGetRequestFieldNotCountries           = big.NewInt(1 << 9)
	aggregationGetRequestFieldNotAuthorName          = big.NewInt(1 << 10)
	aggregationGetRequestFieldFrom                   = big.NewInt(1 << 11)
	aggregationGetRequestFieldTo                     = big.NewInt(1 << 12)
	aggregationGetRequestFieldPublishedDatePrecision = big.NewInt(1 << 13)
	aggregationGetRequestFieldByParseDate            = big.NewInt(1 << 14)
	aggregationGetRequestFieldSortBy                 = big.NewInt(1 << 15)
	aggregationGetRequestFieldRankedOnly             = big.NewInt(1 << 16)
	aggregationGetRequestFieldFromRank               = big.NewInt(1 << 17)
	aggregationGetRequestFieldToRank                 = big.NewInt(1 << 18)
	aggregationGetRequestFieldIsHeadline             = big.NewInt(1 << 19)
	aggregationGetRequestFieldIsOpinion              = big.NewInt(1 << 20)
	aggregationGetRequestFieldIsPaidContent          = big.NewInt(1 << 21)
	aggregationGetRequestFieldParentUrl              = big.NewInt(1 << 22)
	aggregationGetRequestFieldAllLinks               = big.NewInt(1 << 23)
	aggregationGetRequestFieldAllDomainLinks         = big.NewInt(1 << 24)
	aggregationGetRequestFieldWordCountMin           = big.NewInt(1 << 25)
	aggregationGetRequestFieldWordCountMax           = big.NewInt(1 << 26)
	aggregationGetRequestFieldPage                   = big.NewInt(1 << 27)
	aggregationGetRequestFieldPageSize               = big.NewInt(1 << 28)
	aggregationGetRequestFieldIncludeNlpData         = big.NewInt(1 << 29)
	aggregationGetRequestFieldHasNlp                 = big.NewInt(1 << 30)
	aggregationGetRequestFieldTheme                  = big.NewInt(1 << 31)
	aggregationGetRequestFieldNotTheme               = big.NewInt(1 << 32)
	aggregationGetRequestFieldOrgEntityName          = big.NewInt(1 << 33)
	aggregationGetRequestFieldPerEntityName          = big.NewInt(1 << 34)
	aggregationGetRequestFieldLocEntityName          = big.NewInt(1 << 35)
	aggregationGetRequestFieldMiscEntityName         = big.NewInt(1 << 36)
	aggregationGetRequestFieldTitleSentimentMin      = big.NewInt(1 << 37)
	aggregationGetRequestFieldTitleSentimentMax      = big.NewInt(1 << 38)
	aggregationGetRequestFieldContentSentimentMin    = big.NewInt(1 << 39)
	aggregationGetRequestFieldContentSentimentMax    = big.NewInt(1 << 40)
	aggregationGetRequestFieldIptcTags               = big.NewInt(1 << 41)
	aggregationGetRequestFieldNotIptcTags            = big.NewInt(1 << 42)
	aggregationGetRequestFieldRobotsCompliant        = big.NewInt(1 << 43)
)

type AggregationGetRequest struct {
	Q             Q              `json:"-" url:"q"`
	AggregationBy *AggregationBy `json:"-" url:"aggregation_by,omitempty"`
	SearchIn      *SearchIn      `json:"-" url:"search_in,omitempty"`
	// Predefined top news sources per country.
	//
	// Format: start with the word `top`, followed by the number of desired sources, and then the two-letter country code [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2). Multiple countries with the number of top sources can be specified as a comma-separated string.
	//
	// Examples:
	// - `"top 100 US"`
	// - `"top 33 AT"`
	// - `"top 50 US, top 20 GB"`
	// - `"top 33 AT, top 50 IT"`
	PredefinedSources *string `json:"-" url:"predefined_sources,omitempty"`
	// One or more news sources to narrow down the search. The format must be a domain URL. Subdomains, such as `finance.yahoo.com`, are also acceptable.To specify multiple sources, use a comma-separated string.
	//
	// Examples:
	// - `"nytimes.com"`
	// - `"theguardian.com, finance.yahoo.com"`
	Sources *string `json:"-" url:"sources,omitempty"`
	// The news sources to exclude from the search. To exclude multiple sources, use a comma-separated string.
	//
	// Example: `"cnn.com, wsj.com"`
	NotSources *string `json:"-" url:"not_sources,omitempty"`
	// The language(s) of the search. The only accepted format is the two-letter [ISO 639-1](https://en.wikipedia.org/wiki/ISO_639-1) code. To select multiple languages, use a comma-separated string.
	//
	// Example: `"en, es"`
	//
	// To learn more, see [Enumerated parameters > Language](/docs/v3/api-reference/overview/enumerated-parameters#language-lang-and-not-lang).
	Lang *string `json:"-" url:"lang,omitempty"`
	// The language(s) to exclude from the search. The accepted format is the two-letter [ISO 639-1](https://en.wikipedia.org/wiki/ISO_639-1) code. To exclude multiple languages, use a comma-separated string.
	//
	// Example: `"fr, de"`
	//
	// To learn more, see [Enumerated parameters > Language](/docs/v3/api-reference/overview/enumerated-parameters#language-lang-and-not-lang).
	NotLang *string `json:"-" url:"not_lang,omitempty"`
	// The countries where the news publisher is located. The accepted format is the two-letter [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) code. To select multiple countries, use a comma-separated string.
	//
	// Example: `"US, CA"`
	//
	// To learn more, see [Enumerated parameters > Country](/docs/v3/api-reference/overview/enumerated-parameters#country-country-and-not-country).
	Countries *string `json:"-" url:"countries,omitempty"`
	// The publisher location countries to exclude from the search. The accepted format is the two-letter [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) code. To exclude multiple countries, use a comma-separated string.
	//
	// Example:`"US, CA"`
	//
	// To learn more, see [Enumerated parameters > Country](/docs/v3/api-reference/overview/enumerated-parameters#country-country-and-not-country).
	NotCountries *string `json:"-" url:"not_countries,omitempty"`
	// The list of author names to exclude from your search. To exclude articles by specific authors, use a comma-separated string.
	//
	// Example: `"John Doe, Jane Doe"`
	NotAuthorName *string `json:"-" url:"not_author_name,omitempty"`
	// The starting point in time to search from. Accepts date-time strings in ISO 8601 format and plain text. The default time zone is UTC.
	//
	// Formats with examples:
	// - YYYY-mm-ddTHH:MM:SS: `2024-07-01T00:00:00`
	// - YYYY-MM-dd: `2024-07-01`
	// - YYYY/mm/dd HH:MM:SS: `2024/07/01 00:00:00`
	// - YYYY/mm/dd: `2024/07/01`
	// - English phrases: `7 day ago`, `today`
	//
	// **Note**: By default, applied to the publication date of the article. To use the article's parse date instead, set the `by_parse_date` parameter to `true`.
	From *AggregationGetRequestFrom `json:"-" url:"from_,omitempty"`
	// The ending point in time to search up to. Accepts date-time strings in ISO 8601 format and plain text. The default time zone is UTC.
	//
	// Formats with examples:
	// - YYYY-mm-ddTHH:MM:SS: `2024-07-01T00:00:00`
	// - YYYY-MM-dd: `2024-07-01`
	// - YYYY/mm/dd HH:MM:SS: `2024/07/01 00:00:00`
	// - YYYY/mm/dd: `2024/07/01`
	// - English phrases: `1 day ago`, `now`
	//
	// **Note**: By default, applied to the publication date of the article. To use the article's parse date instead, set the `by_parse_date` parameter to `true`.
	To *AggregationGetRequestTo `json:"-" url:"to_,omitempty"`
	// The precision of the published date. There are three types:
	// - `full`: The day and time of an article is correctly identified with the appropriate timezone.
	// - `timezone unknown`: The day and time of an article is correctly identified without timezone.
	// - `date`: Only the day is identified without an exact time.
	PublishedDatePrecision *AggregationGetRequestPublishedDatePrecision `json:"-" url:"published_date_precision,omitempty"`
	// If true, the `from_` and `to_` parameters use article parse dates instead of published dates. Additionally, the `parse_date` variable is added to the output for each article object.
	ByParseDate *bool `json:"-" url:"by_parse_date,omitempty"`
	// The sorting order of the results. Possible values are:
	// - `relevancy`: The most relevant results first.
	// - `date`: The most recently published results first.
	// - `rank`: The results from the highest-ranked sources first.
	SortBy *AggregationGetRequestSortBy `json:"-" url:"sort_by,omitempty"`
	// If true, limits the search to sources ranked in the top 1 million online websites. If false, includes unranked sources which are assigned a rank of 999999.
	RankedOnly *bool `json:"-" url:"ranked_only,omitempty"`
	// The lowest boundary of the rank of a news website to filter by. A lower rank indicates a more popular source.
	FromRank *int `json:"-" url:"from_rank,omitempty"`
	// The highest boundary of the rank of a news website to filter by. A lower rank indicates a more popular source.
	ToRank *int `json:"-" url:"to_rank,omitempty"`
	// If true, only returns articles that were posted on the home page of a given news domain.
	IsHeadline *bool `json:"-" url:"is_headline,omitempty"`
	// If true, returns only opinion pieces. If false, excludes opinion-based articles and returns news only.
	IsOpinion *bool `json:"-" url:"is_opinion,omitempty"`
	// If false, returns only articles that have publicly available complete content. Some publishers partially block content, so this setting ensures that only full articles are retrieved.
	IsPaidContent *bool `json:"-" url:"is_paid_content,omitempty"`
	// The categorical URL(s) to filter your search. To filter your search by multiple categorical URLs, use a comma-separated string.
	//
	// Example: `"wsj.com/politics, wsj.com/tech"`
	ParentUrl *string `json:"-" url:"parent_url,omitempty"`
	// The complete URL(s) mentioned in the article. For multiple URLs, use a comma-separated string.
	//
	// Example: `"https://aiindex.stanford.edu/report, https://www.stateof.ai"`
	//
	// For more details, see [Search by URL](/docs/v3/documentation/how-to/search-by-url).
	AllLinks *string `json:"-" url:"all_links,omitempty"`
	// The domain(s) mentioned in the article. For multiple domains, use a comma-separated string.
	//
	// Example: `"who.int, nih.gov"`
	//
	// For more details, see [Search by URL](/docs/v3/documentation/how-to/search-by-url).
	AllDomainLinks *string `json:"-" url:"all_domain_links,omitempty"`
	// The minimum number of words an article must contain. To be used for avoiding articles with small content.
	WordCountMin *int `json:"-" url:"word_count_min,omitempty"`
	// The maximum number of words an article can contain. To be used for avoiding articles with large content.
	WordCountMax *int `json:"-" url:"word_count_max,omitempty"`
	// The page number to scroll through the results. Use for pagination, as a single API response can return up to 1,000 articles.
	//
	// For details, see [How to paginate large datasets](https://www.newscatcherapi.com/docs/v3/documentation/how-to/paginate-large-datasets).
	Page *int `json:"-" url:"page,omitempty"`
	// The number of articles to return per page.
	PageSize       *int            `json:"-" url:"page_size,omitempty"`
	IncludeNlpData *IncludeNlpData `json:"-" url:"include_nlp_data,omitempty"`
	HasNlp         *HasNlp         `json:"-" url:"has_nlp,omitempty"`
	// Filters articles based on their general topic, as determined by NLP analysis. To select multiple themes, use a comma-separated string.
	//
	// Example: `"Finance, Tech"`
	//
	// **Note**: The `theme` parameter is only available if NLP is included in your subscription plan.
	//
	// To learn more, see [NLP features](/docs/v3/documentation/guides-and-concepts/nlp-features).
	//
	// Available options: `Business`, `Economics`, `Entertainment`, `Finance`, `Health`, `Politics`, `Science`, `Sports`, `Tech`, `Crime`, `Financial Crime`, `Lifestyle`, `Automotive`, `Travel`, `Weather`, `General`.
	Theme *string `json:"-" url:"theme,omitempty"`
	// Inverse of the `theme` parameter. Excludes articles based on their general topic, as determined by NLP analysis. To exclude multiple themes, use a comma-separated string.
	//
	// Example: `"Crime, Tech"`
	//
	// **Note**: The `not_theme` parameter is only available if NLP is included in your subscription plan.
	//
	// To learn more, see [NLP features](/docs/v3/documentation/guides-and-concepts/nlp-features).
	NotTheme *string `json:"-" url:"not_theme,omitempty"`
	// Filters articles that mention specific organization names, as identified by NLP analysis. To specify multiple organizations, use a comma-separated string. To search named entities in translations, combine with the translation options of the `search_in` parameter (e.g., `title_content_translated`).
	//
	// Example: `"Apple, Microsoft"`
	//
	// **Note**: The `ORG_entity_name` parameter is only available if NLP is included in your subscription plan.
	//
	// To learn more, see [Search by entity](/docs/v3/documentation/how-to/search-by-entity).
	OrgEntityName *string `json:"-" url:"ORG_entity_name,omitempty"`
	// Filters articles that mention specific person names, as identified by NLP analysis. To specify multiple names, use a comma-separated string. To search named entities in translations, combine with the translation options of the `search_in` parameter (e.g., `title_content_translated`).
	//
	// Example: `"Elon Musk, Jeff Bezos"`
	//
	// **Note**: The `PER_entity_name` parameter is only available if NLP is included in your subscription plan.
	//
	// To learn more, see [Search by entity](/docs/v3/documentation/how-to/search-by-entity).
	PerEntityName *string `json:"-" url:"PER_entity_name,omitempty"`
	// Filters articles that mention specific location names, as identified by NLP analysis. To specify multiple locations, use a comma-separated string. To search named entities in translations, combine with the translation options of the `search_in` parameter (e.g., `title_content_translated`).
	//
	// Example: `"California, New York"`
	//
	// **Note**: The `LOC_entity_name` parameter is only available if NLP is included in your subscription plan.
	//
	// To learn more, see [Search by entity](/docs/v3/documentation/how-to/search-by-entity).
	LocEntityName *string `json:"-" url:"LOC_entity_name,omitempty"`
	// Filters articles that mention other named entities not falling under person, organization, or location categories. Includes events, nationalities, products, works of art, and more. To specify multiple entities, use a comma-separated string. To search named entities in translations, combine with the translation options of the `search_in` parameter (e.g., `title_content_translated`).
	//
	// Example: `"Bitcoin, Blockchain"`
	//
	// **Note**: The `MISC_entity_name` parameter is only available if NLP is included in your subscription plan.
	//
	// To learn more, see [Search by entity](/docs/v3/documentation/how-to/search-by-entity).
	MiscEntityName *string `json:"-" url:"MISC_entity_name,omitempty"`
	// Filters articles based on the minimum sentiment score of their titles.
	//
	// Range is `-1.0` to `1.0`, where:
	// - Negative values indicate negative sentiment.
	// - Positive values indicate positive sentiment.
	// - Values close to 0 indicate neutral sentiment.
	//
	// **Note**: The `title_sentiment_min` parameter is only available if NLP is included in your subscription plan.
	//
	// To learn more, see [NLP features](/docs/v3/documentation/guides-and-concepts/nlp-features).
	TitleSentimentMin *float64 `json:"-" url:"title_sentiment_min,omitempty"`
	// Filters articles based on the maximum sentiment score of their titles.
	//
	// Range is `-1.0` to `1.0`, where:
	// - Negative values indicate negative sentiment.
	// - Positive values indicate positive sentiment.
	// - Values close to 0 indicate neutral sentiment.
	//
	// **Note**: The `title_sentiment_max` parameter is only available if NLP is included in your subscription plan.
	//
	// To learn more, see [NLP features](/docs/v3/documentation/guides-and-concepts/nlp-features).
	TitleSentimentMax *float64 `json:"-" url:"title_sentiment_max,omitempty"`
	// Filters articles based on the minimum sentiment score of their content.
	//
	// Range is `-1.0` to `1.0`, where:
	// - Negative values indicate negative sentiment.
	// - Positive values indicate positive sentiment.
	// - Values close to 0 indicate neutral sentiment.
	//
	// **Note**: The `content_sentiment_min` parameter is only available if NLP is included in your subscription plan.
	//
	// To learn more, see [NLP features](/docs/v3/documentation/guides-and-concepts/nlp-features).
	ContentSentimentMin *float64 `json:"-" url:"content_sentiment_min,omitempty"`
	// Filters articles based on the maximum sentiment score of their content.
	//
	// Range is `-1.0` to `1.0`, where:
	// - Negative values indicate negative sentiment.
	// - Positive values indicate positive sentiment.
	// - Values close to 0 indicate neutral sentiment.
	//
	// **Note**: The `content_sentiment_max` parameter is only available if NLP is included in your subscription plan.
	//
	// To learn more, see [NLP features](/docs/v3/documentation/guides-and-concepts/nlp-features).
	ContentSentimentMax *float64 `json:"-" url:"content_sentiment_max,omitempty"`
	// Filters articles based on International Press Telecommunications Council (IPTC) media topic tags. To specify multiple IPTC tags, use a comma-separated string of tag IDs.
	//
	// Example: `"20000199, 20000209"`
	//
	// **Note**: The `iptc_tags` parameter is only available in the `v3_nlp_iptc_tags` subscription plan.
	//
	// To learn more, see [IPTC Media Topic NewsCodes](https://www.iptc.org/std/NewsCodes/treeview/mediatopic/mediatopic-en-GB.html).
	IptcTags *string `json:"-" url:"iptc_tags,omitempty"`
	// Inverse of the `iptc_tags` parameter. Excludes articles based on International Press Telecommunications Council (IPTC) media topic tags. To specify multiple IPTC tags to exclude, use a comma-separated string of tag IDs.
	//
	// Example: `"20000205, 20000209"`
	//
	// **Note**: The `not_iptc_tags` parameter is only available in the `v3_nlp_iptc_tags` subscription plan.
	//
	// To learn more, see [IPTC Media Topic NewsCodes](https://www.iptc.org/std/NewsCodes/treeview/mediatopic/mediatopic-en-GB.html).
	NotIptcTags *string `json:"-" url:"not_iptc_tags,omitempty"`
	// If true, returns only articles/sources that comply with the publisher's robots.txt rules. If false, returns only articles/sources that do not comply with robots.txt rules. If omitted, returns all articles/sources regardless of compliance status.
	RobotsCompliant *bool `json:"-" url:"robots_compliant,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (a *AggregationGetRequest) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetQ sets the Q field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationGetRequest) SetQ(q Q) {
	a.Q = q
	a.require(aggregationGetRequestFieldQ)
}

// SetAggregationBy sets the AggregationBy field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationGetRequest) SetAggregationBy(aggregationBy *AggregationBy) {
	a.AggregationBy = aggregationBy
	a.require(aggregationGetRequestFieldAggregationBy)
}

// SetSearchIn sets the SearchIn field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationGetRequest) SetSearchIn(searchIn *SearchIn) {
	a.SearchIn = searchIn
	a.require(aggregationGetRequestFieldSearchIn)
}

// SetPredefinedSources sets the PredefinedSources field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationGetRequest) SetPredefinedSources(predefinedSources *string) {
	a.PredefinedSources = predefinedSources
	a.require(aggregationGetRequestFieldPredefinedSources)
}

// SetSources sets the Sources field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationGetRequest) SetSources(sources *string) {
	a.Sources = sources
	a.require(aggregationGetRequestFieldSources)
}

// SetNotSources sets the NotSources field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationGetRequest) SetNotSources(notSources *string) {
	a.NotSources = notSources
	a.require(aggregationGetRequestFieldNotSources)
}

// SetLang sets the Lang field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationGetRequest) SetLang(lang *string) {
	a.Lang = lang
	a.require(aggregationGetRequestFieldLang)
}

// SetNotLang sets the NotLang field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationGetRequest) SetNotLang(notLang *string) {
	a.NotLang = notLang
	a.require(aggregationGetRequestFieldNotLang)
}

// SetCountries sets the Countries field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationGetRequest) SetCountries(countries *string) {
	a.Countries = countries
	a.require(aggregationGetRequestFieldCountries)
}

// SetNotCountries sets the NotCountries field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationGetRequest) SetNotCountries(notCountries *string) {
	a.NotCountries = notCountries
	a.require(aggregationGetRequestFieldNotCountries)
}

// SetNotAuthorName sets the NotAuthorName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationGetRequest) SetNotAuthorName(notAuthorName *string) {
	a.NotAuthorName = notAuthorName
	a.require(aggregationGetRequestFieldNotAuthorName)
}

// SetFrom sets the From field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationGetRequest) SetFrom(from *AggregationGetRequestFrom) {
	a.From = from
	a.require(aggregationGetRequestFieldFrom)
}

// SetTo sets the To field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationGetRequest) SetTo(to *AggregationGetRequestTo) {
	a.To = to
	a.require(aggregationGetRequestFieldTo)
}

// SetPublishedDatePrecision sets the PublishedDatePrecision field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationGetRequest) SetPublishedDatePrecision(publishedDatePrecision *AggregationGetRequestPublishedDatePrecision) {
	a.PublishedDatePrecision = publishedDatePrecision
	a.require(aggregationGetRequestFieldPublishedDatePrecision)
}

// SetByParseDate sets the ByParseDate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationGetRequest) SetByParseDate(byParseDate *bool) {
	a.ByParseDate = byParseDate
	a.require(aggregationGetRequestFieldByParseDate)
}

// SetSortBy sets the SortBy field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationGetRequest) SetSortBy(sortBy *AggregationGetRequestSortBy) {
	a.SortBy = sortBy
	a.require(aggregationGetRequestFieldSortBy)
}

// SetRankedOnly sets the RankedOnly field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationGetRequest) SetRankedOnly(rankedOnly *bool) {
	a.RankedOnly = rankedOnly
	a.require(aggregationGetRequestFieldRankedOnly)
}

// SetFromRank sets the FromRank field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationGetRequest) SetFromRank(fromRank *int) {
	a.FromRank = fromRank
	a.require(aggregationGetRequestFieldFromRank)
}

// SetToRank sets the ToRank field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationGetRequest) SetToRank(toRank *int) {
	a.ToRank = toRank
	a.require(aggregationGetRequestFieldToRank)
}

// SetIsHeadline sets the IsHeadline field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationGetRequest) SetIsHeadline(isHeadline *bool) {
	a.IsHeadline = isHeadline
	a.require(aggregationGetRequestFieldIsHeadline)
}

// SetIsOpinion sets the IsOpinion field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationGetRequest) SetIsOpinion(isOpinion *bool) {
	a.IsOpinion = isOpinion
	a.require(aggregationGetRequestFieldIsOpinion)
}

// SetIsPaidContent sets the IsPaidContent field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationGetRequest) SetIsPaidContent(isPaidContent *bool) {
	a.IsPaidContent = isPaidContent
	a.require(aggregationGetRequestFieldIsPaidContent)
}

// SetParentUrl sets the ParentUrl field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationGetRequest) SetParentUrl(parentUrl *string) {
	a.ParentUrl = parentUrl
	a.require(aggregationGetRequestFieldParentUrl)
}

// SetAllLinks sets the AllLinks field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationGetRequest) SetAllLinks(allLinks *string) {
	a.AllLinks = allLinks
	a.require(aggregationGetRequestFieldAllLinks)
}

// SetAllDomainLinks sets the AllDomainLinks field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationGetRequest) SetAllDomainLinks(allDomainLinks *string) {
	a.AllDomainLinks = allDomainLinks
	a.require(aggregationGetRequestFieldAllDomainLinks)
}

// SetWordCountMin sets the WordCountMin field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationGetRequest) SetWordCountMin(wordCountMin *int) {
	a.WordCountMin = wordCountMin
	a.require(aggregationGetRequestFieldWordCountMin)
}

// SetWordCountMax sets the WordCountMax field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationGetRequest) SetWordCountMax(wordCountMax *int) {
	a.WordCountMax = wordCountMax
	a.require(aggregationGetRequestFieldWordCountMax)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationGetRequest) SetPage(page *int) {
	a.Page = page
	a.require(aggregationGetRequestFieldPage)
}

// SetPageSize sets the PageSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationGetRequest) SetPageSize(pageSize *int) {
	a.PageSize = pageSize
	a.require(aggregationGetRequestFieldPageSize)
}

// SetIncludeNlpData sets the IncludeNlpData field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationGetRequest) SetIncludeNlpData(includeNlpData *IncludeNlpData) {
	a.IncludeNlpData = includeNlpData
	a.require(aggregationGetRequestFieldIncludeNlpData)
}

// SetHasNlp sets the HasNlp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationGetRequest) SetHasNlp(hasNlp *HasNlp) {
	a.HasNlp = hasNlp
	a.require(aggregationGetRequestFieldHasNlp)
}

// SetTheme sets the Theme field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationGetRequest) SetTheme(theme *string) {
	a.Theme = theme
	a.require(aggregationGetRequestFieldTheme)
}

// SetNotTheme sets the NotTheme field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationGetRequest) SetNotTheme(notTheme *string) {
	a.NotTheme = notTheme
	a.require(aggregationGetRequestFieldNotTheme)
}

// SetOrgEntityName sets the OrgEntityName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationGetRequest) SetOrgEntityName(orgEntityName *string) {
	a.OrgEntityName = orgEntityName
	a.require(aggregationGetRequestFieldOrgEntityName)
}

// SetPerEntityName sets the PerEntityName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationGetRequest) SetPerEntityName(perEntityName *string) {
	a.PerEntityName = perEntityName
	a.require(aggregationGetRequestFieldPerEntityName)
}

// SetLocEntityName sets the LocEntityName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationGetRequest) SetLocEntityName(locEntityName *string) {
	a.LocEntityName = locEntityName
	a.require(aggregationGetRequestFieldLocEntityName)
}

// SetMiscEntityName sets the MiscEntityName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationGetRequest) SetMiscEntityName(miscEntityName *string) {
	a.MiscEntityName = miscEntityName
	a.require(aggregationGetRequestFieldMiscEntityName)
}

// SetTitleSentimentMin sets the TitleSentimentMin field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationGetRequest) SetTitleSentimentMin(titleSentimentMin *float64) {
	a.TitleSentimentMin = titleSentimentMin
	a.require(aggregationGetRequestFieldTitleSentimentMin)
}

// SetTitleSentimentMax sets the TitleSentimentMax field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationGetRequest) SetTitleSentimentMax(titleSentimentMax *float64) {
	a.TitleSentimentMax = titleSentimentMax
	a.require(aggregationGetRequestFieldTitleSentimentMax)
}

// SetContentSentimentMin sets the ContentSentimentMin field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationGetRequest) SetContentSentimentMin(contentSentimentMin *float64) {
	a.ContentSentimentMin = contentSentimentMin
	a.require(aggregationGetRequestFieldContentSentimentMin)
}

// SetContentSentimentMax sets the ContentSentimentMax field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationGetRequest) SetContentSentimentMax(contentSentimentMax *float64) {
	a.ContentSentimentMax = contentSentimentMax
	a.require(aggregationGetRequestFieldContentSentimentMax)
}

// SetIptcTags sets the IptcTags field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationGetRequest) SetIptcTags(iptcTags *string) {
	a.IptcTags = iptcTags
	a.require(aggregationGetRequestFieldIptcTags)
}

// SetNotIptcTags sets the NotIptcTags field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationGetRequest) SetNotIptcTags(notIptcTags *string) {
	a.NotIptcTags = notIptcTags
	a.require(aggregationGetRequestFieldNotIptcTags)
}

// SetRobotsCompliant sets the RobotsCompliant field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationGetRequest) SetRobotsCompliant(robotsCompliant *bool) {
	a.RobotsCompliant = robotsCompliant
	a.require(aggregationGetRequestFieldRobotsCompliant)
}

var (
	aggregationPostRequestFieldQ                      = big.NewInt(1 << 0)
	aggregationPostRequestFieldAggregationBy          = big.NewInt(1 << 1)
	aggregationPostRequestFieldSearchIn               = big.NewInt(1 << 2)
	aggregationPostRequestFieldPredefinedSources      = big.NewInt(1 << 3)
	aggregationPostRequestFieldSources                = big.NewInt(1 << 4)
	aggregationPostRequestFieldNotSources             = big.NewInt(1 << 5)
	aggregationPostRequestFieldLang                   = big.NewInt(1 << 6)
	aggregationPostRequestFieldNotLang                = big.NewInt(1 << 7)
	aggregationPostRequestFieldCountries              = big.NewInt(1 << 8)
	aggregationPostRequestFieldNotCountries           = big.NewInt(1 << 9)
	aggregationPostRequestFieldNotAuthorName          = big.NewInt(1 << 10)
	aggregationPostRequestFieldFrom                   = big.NewInt(1 << 11)
	aggregationPostRequestFieldTo                     = big.NewInt(1 << 12)
	aggregationPostRequestFieldPublishedDatePrecision = big.NewInt(1 << 13)
	aggregationPostRequestFieldByParseDate            = big.NewInt(1 << 14)
	aggregationPostRequestFieldSortBy                 = big.NewInt(1 << 15)
	aggregationPostRequestFieldRankedOnly             = big.NewInt(1 << 16)
	aggregationPostRequestFieldFromRank               = big.NewInt(1 << 17)
	aggregationPostRequestFieldToRank                 = big.NewInt(1 << 18)
	aggregationPostRequestFieldIsHeadline             = big.NewInt(1 << 19)
	aggregationPostRequestFieldIsOpinion              = big.NewInt(1 << 20)
	aggregationPostRequestFieldIsPaidContent          = big.NewInt(1 << 21)
	aggregationPostRequestFieldParentUrl              = big.NewInt(1 << 22)
	aggregationPostRequestFieldAllLinks               = big.NewInt(1 << 23)
	aggregationPostRequestFieldAllDomainLinks         = big.NewInt(1 << 24)
	aggregationPostRequestFieldWordCountMin           = big.NewInt(1 << 25)
	aggregationPostRequestFieldWordCountMax           = big.NewInt(1 << 26)
	aggregationPostRequestFieldPage                   = big.NewInt(1 << 27)
	aggregationPostRequestFieldPageSize               = big.NewInt(1 << 28)
	aggregationPostRequestFieldIncludeNlpData         = big.NewInt(1 << 29)
	aggregationPostRequestFieldHasNlp                 = big.NewInt(1 << 30)
	aggregationPostRequestFieldTheme                  = big.NewInt(1 << 31)
	aggregationPostRequestFieldNotTheme               = big.NewInt(1 << 32)
	aggregationPostRequestFieldOrgEntityName          = big.NewInt(1 << 33)
	aggregationPostRequestFieldPerEntityName          = big.NewInt(1 << 34)
	aggregationPostRequestFieldLocEntityName          = big.NewInt(1 << 35)
	aggregationPostRequestFieldMiscEntityName         = big.NewInt(1 << 36)
	aggregationPostRequestFieldTitleSentimentMin      = big.NewInt(1 << 37)
	aggregationPostRequestFieldTitleSentimentMax      = big.NewInt(1 << 38)
	aggregationPostRequestFieldContentSentimentMin    = big.NewInt(1 << 39)
	aggregationPostRequestFieldContentSentimentMax    = big.NewInt(1 << 40)
	aggregationPostRequestFieldIptcTags               = big.NewInt(1 << 41)
	aggregationPostRequestFieldNotIptcTags            = big.NewInt(1 << 42)
	aggregationPostRequestFieldRobotsCompliant        = big.NewInt(1 << 43)
)

type AggregationPostRequest struct {
	Q                      Q                       `json:"q" url:"-"`
	AggregationBy          *AggregationBy          `json:"aggregation_by,omitempty" url:"-"`
	SearchIn               *SearchIn               `json:"search_in,omitempty" url:"-"`
	PredefinedSources      *PredefinedSources      `json:"predefined_sources,omitempty" url:"-"`
	Sources                *Sources                `json:"sources,omitempty" url:"-"`
	NotSources             *NotSources             `json:"not_sources,omitempty" url:"-"`
	Lang                   *Lang                   `json:"lang,omitempty" url:"-"`
	NotLang                *NotLang                `json:"not_lang,omitempty" url:"-"`
	Countries              *Countries              `json:"countries,omitempty" url:"-"`
	NotCountries           *NotCountries           `json:"not_countries,omitempty" url:"-"`
	NotAuthorName          *NotAuthorName          `json:"not_author_name,omitempty" url:"-"`
	From                   *From                   `json:"from_,omitempty" url:"-"`
	To                     *To                     `json:"to_,omitempty" url:"-"`
	PublishedDatePrecision *PublishedDatePrecision `json:"published_date_precision,omitempty" url:"-"`
	ByParseDate            *ByParseDate            `json:"by_parse_date,omitempty" url:"-"`
	SortBy                 *SortBy                 `json:"sort_by,omitempty" url:"-"`
	RankedOnly             *RankedOnly             `json:"ranked_only,omitempty" url:"-"`
	FromRank               *FromRank               `json:"from_rank,omitempty" url:"-"`
	ToRank                 *ToRank                 `json:"to_rank,omitempty" url:"-"`
	IsHeadline             *IsHeadline             `json:"is_headline,omitempty" url:"-"`
	IsOpinion              *IsOpinion              `json:"is_opinion,omitempty" url:"-"`
	IsPaidContent          *IsPaidContent          `json:"is_paid_content,omitempty" url:"-"`
	ParentUrl              *ParentUrl              `json:"parent_url,omitempty" url:"-"`
	AllLinks               *AllLinks               `json:"all_links,omitempty" url:"-"`
	AllDomainLinks         *AllDomainLinks         `json:"all_domain_links,omitempty" url:"-"`
	WordCountMin           *WordCountMin           `json:"word_count_min,omitempty" url:"-"`
	WordCountMax           *WordCountMax           `json:"word_count_max,omitempty" url:"-"`
	Page                   *Page                   `json:"page,omitempty" url:"-"`
	PageSize               *PageSize               `json:"page_size,omitempty" url:"-"`
	IncludeNlpData         *IncludeNlpData         `json:"include_nlp_data,omitempty" url:"-"`
	HasNlp                 *HasNlp                 `json:"has_nlp,omitempty" url:"-"`
	Theme                  *Theme                  `json:"theme,omitempty" url:"-"`
	NotTheme               *NotTheme               `json:"not_theme,omitempty" url:"-"`
	OrgEntityName          *OrgEntityName          `json:"ORG_entity_name,omitempty" url:"-"`
	PerEntityName          *PerEntityName          `json:"PER_entity_name,omitempty" url:"-"`
	LocEntityName          *LocEntityName          `json:"LOC_entity_name,omitempty" url:"-"`
	MiscEntityName         *MiscEntityName         `json:"MISC_entity_name,omitempty" url:"-"`
	TitleSentimentMin      *TitleSentimentMin      `json:"title_sentiment_min,omitempty" url:"-"`
	TitleSentimentMax      *TitleSentimentMax      `json:"title_sentiment_max,omitempty" url:"-"`
	ContentSentimentMin    *ContentSentimentMin    `json:"content_sentiment_min,omitempty" url:"-"`
	ContentSentimentMax    *ContentSentimentMax    `json:"content_sentiment_max,omitempty" url:"-"`
	IptcTags               *IptcTags               `json:"iptc_tags,omitempty" url:"-"`
	NotIptcTags            *NotIptcTags            `json:"not_iptc_tags,omitempty" url:"-"`
	RobotsCompliant        *RobotsCompliant        `json:"robots_compliant,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (a *AggregationPostRequest) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetQ sets the Q field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationPostRequest) SetQ(q Q) {
	a.Q = q
	a.require(aggregationPostRequestFieldQ)
}

// SetAggregationBy sets the AggregationBy field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationPostRequest) SetAggregationBy(aggregationBy *AggregationBy) {
	a.AggregationBy = aggregationBy
	a.require(aggregationPostRequestFieldAggregationBy)
}

// SetSearchIn sets the SearchIn field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationPostRequest) SetSearchIn(searchIn *SearchIn) {
	a.SearchIn = searchIn
	a.require(aggregationPostRequestFieldSearchIn)
}

// SetPredefinedSources sets the PredefinedSources field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationPostRequest) SetPredefinedSources(predefinedSources *PredefinedSources) {
	a.PredefinedSources = predefinedSources
	a.require(aggregationPostRequestFieldPredefinedSources)
}

// SetSources sets the Sources field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationPostRequest) SetSources(sources *Sources) {
	a.Sources = sources
	a.require(aggregationPostRequestFieldSources)
}

// SetNotSources sets the NotSources field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationPostRequest) SetNotSources(notSources *NotSources) {
	a.NotSources = notSources
	a.require(aggregationPostRequestFieldNotSources)
}

// SetLang sets the Lang field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationPostRequest) SetLang(lang *Lang) {
	a.Lang = lang
	a.require(aggregationPostRequestFieldLang)
}

// SetNotLang sets the NotLang field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationPostRequest) SetNotLang(notLang *NotLang) {
	a.NotLang = notLang
	a.require(aggregationPostRequestFieldNotLang)
}

// SetCountries sets the Countries field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationPostRequest) SetCountries(countries *Countries) {
	a.Countries = countries
	a.require(aggregationPostRequestFieldCountries)
}

// SetNotCountries sets the NotCountries field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationPostRequest) SetNotCountries(notCountries *NotCountries) {
	a.NotCountries = notCountries
	a.require(aggregationPostRequestFieldNotCountries)
}

// SetNotAuthorName sets the NotAuthorName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationPostRequest) SetNotAuthorName(notAuthorName *NotAuthorName) {
	a.NotAuthorName = notAuthorName
	a.require(aggregationPostRequestFieldNotAuthorName)
}

// SetFrom sets the From field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationPostRequest) SetFrom(from *From) {
	a.From = from
	a.require(aggregationPostRequestFieldFrom)
}

// SetTo sets the To field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationPostRequest) SetTo(to *To) {
	a.To = to
	a.require(aggregationPostRequestFieldTo)
}

// SetPublishedDatePrecision sets the PublishedDatePrecision field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationPostRequest) SetPublishedDatePrecision(publishedDatePrecision *PublishedDatePrecision) {
	a.PublishedDatePrecision = publishedDatePrecision
	a.require(aggregationPostRequestFieldPublishedDatePrecision)
}

// SetByParseDate sets the ByParseDate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationPostRequest) SetByParseDate(byParseDate *ByParseDate) {
	a.ByParseDate = byParseDate
	a.require(aggregationPostRequestFieldByParseDate)
}

// SetSortBy sets the SortBy field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationPostRequest) SetSortBy(sortBy *SortBy) {
	a.SortBy = sortBy
	a.require(aggregationPostRequestFieldSortBy)
}

// SetRankedOnly sets the RankedOnly field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationPostRequest) SetRankedOnly(rankedOnly *RankedOnly) {
	a.RankedOnly = rankedOnly
	a.require(aggregationPostRequestFieldRankedOnly)
}

// SetFromRank sets the FromRank field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationPostRequest) SetFromRank(fromRank *FromRank) {
	a.FromRank = fromRank
	a.require(aggregationPostRequestFieldFromRank)
}

// SetToRank sets the ToRank field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationPostRequest) SetToRank(toRank *ToRank) {
	a.ToRank = toRank
	a.require(aggregationPostRequestFieldToRank)
}

// SetIsHeadline sets the IsHeadline field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationPostRequest) SetIsHeadline(isHeadline *IsHeadline) {
	a.IsHeadline = isHeadline
	a.require(aggregationPostRequestFieldIsHeadline)
}

// SetIsOpinion sets the IsOpinion field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationPostRequest) SetIsOpinion(isOpinion *IsOpinion) {
	a.IsOpinion = isOpinion
	a.require(aggregationPostRequestFieldIsOpinion)
}

// SetIsPaidContent sets the IsPaidContent field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationPostRequest) SetIsPaidContent(isPaidContent *IsPaidContent) {
	a.IsPaidContent = isPaidContent
	a.require(aggregationPostRequestFieldIsPaidContent)
}

// SetParentUrl sets the ParentUrl field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationPostRequest) SetParentUrl(parentUrl *ParentUrl) {
	a.ParentUrl = parentUrl
	a.require(aggregationPostRequestFieldParentUrl)
}

// SetAllLinks sets the AllLinks field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationPostRequest) SetAllLinks(allLinks *AllLinks) {
	a.AllLinks = allLinks
	a.require(aggregationPostRequestFieldAllLinks)
}

// SetAllDomainLinks sets the AllDomainLinks field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationPostRequest) SetAllDomainLinks(allDomainLinks *AllDomainLinks) {
	a.AllDomainLinks = allDomainLinks
	a.require(aggregationPostRequestFieldAllDomainLinks)
}

// SetWordCountMin sets the WordCountMin field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationPostRequest) SetWordCountMin(wordCountMin *WordCountMin) {
	a.WordCountMin = wordCountMin
	a.require(aggregationPostRequestFieldWordCountMin)
}

// SetWordCountMax sets the WordCountMax field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationPostRequest) SetWordCountMax(wordCountMax *WordCountMax) {
	a.WordCountMax = wordCountMax
	a.require(aggregationPostRequestFieldWordCountMax)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationPostRequest) SetPage(page *Page) {
	a.Page = page
	a.require(aggregationPostRequestFieldPage)
}

// SetPageSize sets the PageSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationPostRequest) SetPageSize(pageSize *PageSize) {
	a.PageSize = pageSize
	a.require(aggregationPostRequestFieldPageSize)
}

// SetIncludeNlpData sets the IncludeNlpData field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationPostRequest) SetIncludeNlpData(includeNlpData *IncludeNlpData) {
	a.IncludeNlpData = includeNlpData
	a.require(aggregationPostRequestFieldIncludeNlpData)
}

// SetHasNlp sets the HasNlp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationPostRequest) SetHasNlp(hasNlp *HasNlp) {
	a.HasNlp = hasNlp
	a.require(aggregationPostRequestFieldHasNlp)
}

// SetTheme sets the Theme field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationPostRequest) SetTheme(theme *Theme) {
	a.Theme = theme
	a.require(aggregationPostRequestFieldTheme)
}

// SetNotTheme sets the NotTheme field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationPostRequest) SetNotTheme(notTheme *NotTheme) {
	a.NotTheme = notTheme
	a.require(aggregationPostRequestFieldNotTheme)
}

// SetOrgEntityName sets the OrgEntityName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationPostRequest) SetOrgEntityName(orgEntityName *OrgEntityName) {
	a.OrgEntityName = orgEntityName
	a.require(aggregationPostRequestFieldOrgEntityName)
}

// SetPerEntityName sets the PerEntityName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationPostRequest) SetPerEntityName(perEntityName *PerEntityName) {
	a.PerEntityName = perEntityName
	a.require(aggregationPostRequestFieldPerEntityName)
}

// SetLocEntityName sets the LocEntityName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationPostRequest) SetLocEntityName(locEntityName *LocEntityName) {
	a.LocEntityName = locEntityName
	a.require(aggregationPostRequestFieldLocEntityName)
}

// SetMiscEntityName sets the MiscEntityName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationPostRequest) SetMiscEntityName(miscEntityName *MiscEntityName) {
	a.MiscEntityName = miscEntityName
	a.require(aggregationPostRequestFieldMiscEntityName)
}

// SetTitleSentimentMin sets the TitleSentimentMin field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationPostRequest) SetTitleSentimentMin(titleSentimentMin *TitleSentimentMin) {
	a.TitleSentimentMin = titleSentimentMin
	a.require(aggregationPostRequestFieldTitleSentimentMin)
}

// SetTitleSentimentMax sets the TitleSentimentMax field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationPostRequest) SetTitleSentimentMax(titleSentimentMax *TitleSentimentMax) {
	a.TitleSentimentMax = titleSentimentMax
	a.require(aggregationPostRequestFieldTitleSentimentMax)
}

// SetContentSentimentMin sets the ContentSentimentMin field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationPostRequest) SetContentSentimentMin(contentSentimentMin *ContentSentimentMin) {
	a.ContentSentimentMin = contentSentimentMin
	a.require(aggregationPostRequestFieldContentSentimentMin)
}

// SetContentSentimentMax sets the ContentSentimentMax field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationPostRequest) SetContentSentimentMax(contentSentimentMax *ContentSentimentMax) {
	a.ContentSentimentMax = contentSentimentMax
	a.require(aggregationPostRequestFieldContentSentimentMax)
}

// SetIptcTags sets the IptcTags field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationPostRequest) SetIptcTags(iptcTags *IptcTags) {
	a.IptcTags = iptcTags
	a.require(aggregationPostRequestFieldIptcTags)
}

// SetNotIptcTags sets the NotIptcTags field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationPostRequest) SetNotIptcTags(notIptcTags *NotIptcTags) {
	a.NotIptcTags = notIptcTags
	a.require(aggregationPostRequestFieldNotIptcTags)
}

// SetRobotsCompliant sets the RobotsCompliant field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationPostRequest) SetRobotsCompliant(robotsCompliant *RobotsCompliant) {
	a.RobotsCompliant = robotsCompliant
	a.require(aggregationPostRequestFieldRobotsCompliant)
}

func (a *AggregationPostRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler AggregationPostRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*a = AggregationPostRequest(body)
	return nil
}

func (a *AggregationPostRequest) MarshalJSON() ([]byte, error) {
	type embed AggregationPostRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

// The aggregation interval for the results.
type AggregationBy string

const (
	AggregationByDay   AggregationBy = "day"
	AggregationByHour  AggregationBy = "hour"
	AggregationByMonth AggregationBy = "month"
)

func NewAggregationByFromString(s string) (AggregationBy, error) {
	switch s {
	case "day":
		return AggregationByDay, nil
	case "hour":
		return AggregationByHour, nil
	case "month":
		return AggregationByMonth, nil
	}
	var t AggregationBy
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (a AggregationBy) Ptr() *AggregationBy {
	return &a
}

// The response model for a successful `Aggregation count` request. Response field behavior:
// - Required fields are guaranteed to be present and non-null.
// - Optional fields may be `null` or `undefined` if the data point is not presented or couldn't be extracted during processing.
var (
	aggregationCountResponseDtoFieldStatus       = big.NewInt(1 << 0)
	aggregationCountResponseDtoFieldTotalHits    = big.NewInt(1 << 1)
	aggregationCountResponseDtoFieldPage         = big.NewInt(1 << 2)
	aggregationCountResponseDtoFieldTotalPages   = big.NewInt(1 << 3)
	aggregationCountResponseDtoFieldPageSize     = big.NewInt(1 << 4)
	aggregationCountResponseDtoFieldAggregations = big.NewInt(1 << 5)
	aggregationCountResponseDtoFieldUserInput    = big.NewInt(1 << 6)
)

type AggregationCountResponseDto struct {
	// The status of the response.
	Status *string `json:"status,omitempty" url:"status,omitempty"`
	// The total number of articles matching the search criteria.
	TotalHits *int `json:"total_hits,omitempty" url:"total_hits,omitempty"`
	// The current page number of the results.
	Page *int `json:"page,omitempty" url:"page,omitempty"`
	// The total number of pages available for the given search criteria.
	TotalPages *int `json:"total_pages,omitempty" url:"total_pages,omitempty"`
	// The number of articles per page.
	PageSize *int `json:"page_size,omitempty" url:"page_size,omitempty"`
	// The aggregation results. Can be either a dictionary or a list of dictionaries.
	Aggregations *AggregationCountResponseDtoAggregations `json:"aggregations,omitempty" url:"aggregations,omitempty"`
	UserInput    *UserInputDto                            `json:"user_input,omitempty" url:"user_input,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AggregationCountResponseDto) GetStatus() *string {
	if a == nil {
		return nil
	}
	return a.Status
}

func (a *AggregationCountResponseDto) GetTotalHits() *int {
	if a == nil {
		return nil
	}
	return a.TotalHits
}

func (a *AggregationCountResponseDto) GetPage() *int {
	if a == nil {
		return nil
	}
	return a.Page
}

func (a *AggregationCountResponseDto) GetTotalPages() *int {
	if a == nil {
		return nil
	}
	return a.TotalPages
}

func (a *AggregationCountResponseDto) GetPageSize() *int {
	if a == nil {
		return nil
	}
	return a.PageSize
}

func (a *AggregationCountResponseDto) GetAggregations() *AggregationCountResponseDtoAggregations {
	if a == nil {
		return nil
	}
	return a.Aggregations
}

func (a *AggregationCountResponseDto) GetUserInput() *UserInputDto {
	if a == nil {
		return nil
	}
	return a.UserInput
}

func (a *AggregationCountResponseDto) GetExtraProperties() map[string]interface{} {
	if a == nil {
		return nil
	}
	return a.extraProperties
}

func (a *AggregationCountResponseDto) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationCountResponseDto) SetStatus(status *string) {
	a.Status = status
	a.require(aggregationCountResponseDtoFieldStatus)
}

// SetTotalHits sets the TotalHits field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationCountResponseDto) SetTotalHits(totalHits *int) {
	a.TotalHits = totalHits
	a.require(aggregationCountResponseDtoFieldTotalHits)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationCountResponseDto) SetPage(page *int) {
	a.Page = page
	a.require(aggregationCountResponseDtoFieldPage)
}

// SetTotalPages sets the TotalPages field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationCountResponseDto) SetTotalPages(totalPages *int) {
	a.TotalPages = totalPages
	a.require(aggregationCountResponseDtoFieldTotalPages)
}

// SetPageSize sets the PageSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationCountResponseDto) SetPageSize(pageSize *int) {
	a.PageSize = pageSize
	a.require(aggregationCountResponseDtoFieldPageSize)
}

// SetAggregations sets the Aggregations field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationCountResponseDto) SetAggregations(aggregations *AggregationCountResponseDtoAggregations) {
	a.Aggregations = aggregations
	a.require(aggregationCountResponseDtoFieldAggregations)
}

// SetUserInput sets the UserInput field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationCountResponseDto) SetUserInput(userInput *UserInputDto) {
	a.UserInput = userInput
	a.require(aggregationCountResponseDtoFieldUserInput)
}

func (a *AggregationCountResponseDto) UnmarshalJSON(data []byte) error {
	type unmarshaler AggregationCountResponseDto
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AggregationCountResponseDto(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AggregationCountResponseDto) MarshalJSON() ([]byte, error) {
	type embed AggregationCountResponseDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *AggregationCountResponseDto) String() string {
	if a == nil {
		return "<nil>"
	}
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

// The aggregation results. Can be either a dictionary or a list of dictionaries.
type AggregationCountResponseDtoAggregations struct {
	AggregationItem     *AggregationItem
	AggregationItemList []*AggregationItem

	typ string
}

func (a *AggregationCountResponseDtoAggregations) GetAggregationItem() *AggregationItem {
	if a == nil {
		return nil
	}
	return a.AggregationItem
}

func (a *AggregationCountResponseDtoAggregations) GetAggregationItemList() []*AggregationItem {
	if a == nil {
		return nil
	}
	return a.AggregationItemList
}

func (a *AggregationCountResponseDtoAggregations) UnmarshalJSON(data []byte) error {
	valueAggregationItem := new(AggregationItem)
	if err := json.Unmarshal(data, &valueAggregationItem); err == nil {
		a.typ = "AggregationItem"
		a.AggregationItem = valueAggregationItem
		return nil
	}
	var valueAggregationItemList []*AggregationItem
	if err := json.Unmarshal(data, &valueAggregationItemList); err == nil {
		a.typ = "AggregationItemList"
		a.AggregationItemList = valueAggregationItemList
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, a)
}

func (a AggregationCountResponseDtoAggregations) MarshalJSON() ([]byte, error) {
	if a.typ == "AggregationItem" || a.AggregationItem != nil {
		return json.Marshal(a.AggregationItem)
	}
	if a.typ == "AggregationItemList" || a.AggregationItemList != nil {
		return json.Marshal(a.AggregationItemList)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", a)
}

type AggregationCountResponseDtoAggregationsVisitor interface {
	VisitAggregationItem(*AggregationItem) error
	VisitAggregationItemList([]*AggregationItem) error
}

func (a *AggregationCountResponseDtoAggregations) Accept(visitor AggregationCountResponseDtoAggregationsVisitor) error {
	if a.typ == "AggregationItem" || a.AggregationItem != nil {
		return visitor.VisitAggregationItem(a.AggregationItem)
	}
	if a.typ == "AggregationItemList" || a.AggregationItemList != nil {
		return visitor.VisitAggregationItemList(a.AggregationItemList)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", a)
}

type AggregationGetRequestFrom struct {
	DateTime time.Time
	String   string

	typ string
}

func (a *AggregationGetRequestFrom) GetDateTime() time.Time {
	if a == nil {
		return time.Time{}
	}
	return a.DateTime
}

func (a *AggregationGetRequestFrom) GetString() string {
	if a == nil {
		return ""
	}
	return a.String
}

func (a *AggregationGetRequestFrom) UnmarshalJSON(data []byte) error {
	var valueDateTime *internal.DateTime
	if err := json.Unmarshal(data, &valueDateTime); err == nil {
		a.typ = "DateTime"
		a.DateTime = valueDateTime.Time()
		return nil
	}
	var valueString string
	if err := json.Unmarshal(data, &valueString); err == nil {
		a.typ = "String"
		a.String = valueString
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, a)
}

func (a AggregationGetRequestFrom) MarshalJSON() ([]byte, error) {
	if a.typ == "DateTime" || !a.DateTime.IsZero() {
		return json.Marshal(internal.NewDateTime(a.DateTime))
	}
	if a.typ == "String" || a.String != "" {
		return json.Marshal(a.String)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", a)
}

type AggregationGetRequestFromVisitor interface {
	VisitDateTime(time.Time) error
	VisitString(string) error
}

func (a *AggregationGetRequestFrom) Accept(visitor AggregationGetRequestFromVisitor) error {
	if a.typ == "DateTime" || !a.DateTime.IsZero() {
		return visitor.VisitDateTime(a.DateTime)
	}
	if a.typ == "String" || a.String != "" {
		return visitor.VisitString(a.String)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", a)
}

type AggregationGetRequestTo struct {
	DateTime time.Time
	String   string

	typ string
}

func (a *AggregationGetRequestTo) GetDateTime() time.Time {
	if a == nil {
		return time.Time{}
	}
	return a.DateTime
}

func (a *AggregationGetRequestTo) GetString() string {
	if a == nil {
		return ""
	}
	return a.String
}

func (a *AggregationGetRequestTo) UnmarshalJSON(data []byte) error {
	var valueDateTime *internal.DateTime
	if err := json.Unmarshal(data, &valueDateTime); err == nil {
		a.typ = "DateTime"
		a.DateTime = valueDateTime.Time()
		return nil
	}
	var valueString string
	if err := json.Unmarshal(data, &valueString); err == nil {
		a.typ = "String"
		a.String = valueString
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, a)
}

func (a AggregationGetRequestTo) MarshalJSON() ([]byte, error) {
	if a.typ == "DateTime" || !a.DateTime.IsZero() {
		return json.Marshal(internal.NewDateTime(a.DateTime))
	}
	if a.typ == "String" || a.String != "" {
		return json.Marshal(a.String)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", a)
}

type AggregationGetRequestToVisitor interface {
	VisitDateTime(time.Time) error
	VisitString(string) error
}

func (a *AggregationGetRequestTo) Accept(visitor AggregationGetRequestToVisitor) error {
	if a.typ == "DateTime" || !a.DateTime.IsZero() {
		return visitor.VisitDateTime(a.DateTime)
	}
	if a.typ == "String" || a.String != "" {
		return visitor.VisitString(a.String)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", a)
}

// A single item in the aggregations array containing a collection of time-based article counts.
var (
	aggregationItemFieldAggregationCount = big.NewInt(1 << 0)
)

type AggregationItem struct {
	// Array of time frames and their corresponding article counts
	AggregationCount []*TimeFrameCount `json:"aggregation_count" url:"aggregation_count"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AggregationItem) GetAggregationCount() []*TimeFrameCount {
	if a == nil {
		return nil
	}
	return a.AggregationCount
}

func (a *AggregationItem) GetExtraProperties() map[string]interface{} {
	if a == nil {
		return nil
	}
	return a.extraProperties
}

func (a *AggregationItem) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetAggregationCount sets the AggregationCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AggregationItem) SetAggregationCount(aggregationCount []*TimeFrameCount) {
	a.AggregationCount = aggregationCount
	a.require(aggregationItemFieldAggregationCount)
}

func (a *AggregationItem) UnmarshalJSON(data []byte) error {
	type unmarshaler AggregationItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AggregationItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AggregationItem) MarshalJSON() ([]byte, error) {
	type embed AggregationItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *AggregationItem) String() string {
	if a == nil {
		return "<nil>"
	}
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

// The response model for a failed `Aggregation count` request.
var (
	failedAggregationCountResponseDtoFieldStatus     = big.NewInt(1 << 0)
	failedAggregationCountResponseDtoFieldTotalHits  = big.NewInt(1 << 1)
	failedAggregationCountResponseDtoFieldPage       = big.NewInt(1 << 2)
	failedAggregationCountResponseDtoFieldTotalPages = big.NewInt(1 << 3)
	failedAggregationCountResponseDtoFieldPageSize   = big.NewInt(1 << 4)
	failedAggregationCountResponseDtoFieldUserInput  = big.NewInt(1 << 5)
)

type FailedAggregationCountResponseDto struct {
	// The status of the response.
	Status *string `json:"status,omitempty" url:"status,omitempty"`
	// The total number of articles matching the search criteria.
	TotalHits *int `json:"total_hits,omitempty" url:"total_hits,omitempty"`
	// The current page number of the results.
	Page *int `json:"page,omitempty" url:"page,omitempty"`
	// The total number of pages available for the given search criteria.
	TotalPages *int `json:"total_pages,omitempty" url:"total_pages,omitempty"`
	// The number of articles per page.
	PageSize  *int          `json:"page_size,omitempty" url:"page_size,omitempty"`
	UserInput *UserInputDto `json:"user_input,omitempty" url:"user_input,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (f *FailedAggregationCountResponseDto) GetStatus() *string {
	if f == nil {
		return nil
	}
	return f.Status
}

func (f *FailedAggregationCountResponseDto) GetTotalHits() *int {
	if f == nil {
		return nil
	}
	return f.TotalHits
}

func (f *FailedAggregationCountResponseDto) GetPage() *int {
	if f == nil {
		return nil
	}
	return f.Page
}

func (f *FailedAggregationCountResponseDto) GetTotalPages() *int {
	if f == nil {
		return nil
	}
	return f.TotalPages
}

func (f *FailedAggregationCountResponseDto) GetPageSize() *int {
	if f == nil {
		return nil
	}
	return f.PageSize
}

func (f *FailedAggregationCountResponseDto) GetUserInput() *UserInputDto {
	if f == nil {
		return nil
	}
	return f.UserInput
}

func (f *FailedAggregationCountResponseDto) GetExtraProperties() map[string]interface{} {
	if f == nil {
		return nil
	}
	return f.extraProperties
}

func (f *FailedAggregationCountResponseDto) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FailedAggregationCountResponseDto) SetStatus(status *string) {
	f.Status = status
	f.require(failedAggregationCountResponseDtoFieldStatus)
}

// SetTotalHits sets the TotalHits field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FailedAggregationCountResponseDto) SetTotalHits(totalHits *int) {
	f.TotalHits = totalHits
	f.require(failedAggregationCountResponseDtoFieldTotalHits)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FailedAggregationCountResponseDto) SetPage(page *int) {
	f.Page = page
	f.require(failedAggregationCountResponseDtoFieldPage)
}

// SetTotalPages sets the TotalPages field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FailedAggregationCountResponseDto) SetTotalPages(totalPages *int) {
	f.TotalPages = totalPages
	f.require(failedAggregationCountResponseDtoFieldTotalPages)
}

// SetPageSize sets the PageSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FailedAggregationCountResponseDto) SetPageSize(pageSize *int) {
	f.PageSize = pageSize
	f.require(failedAggregationCountResponseDtoFieldPageSize)
}

// SetUserInput sets the UserInput field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FailedAggregationCountResponseDto) SetUserInput(userInput *UserInputDto) {
	f.UserInput = userInput
	f.require(failedAggregationCountResponseDtoFieldUserInput)
}

func (f *FailedAggregationCountResponseDto) UnmarshalJSON(data []byte) error {
	type unmarshaler FailedAggregationCountResponseDto
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*f = FailedAggregationCountResponseDto(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties
	f.rawJSON = json.RawMessage(data)
	return nil
}

func (f *FailedAggregationCountResponseDto) MarshalJSON() ([]byte, error) {
	type embed FailedAggregationCountResponseDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*f),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, f.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (f *FailedAggregationCountResponseDto) String() string {
	if f == nil {
		return "<nil>"
	}
	if len(f.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(f.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

// Represents the article count for a specific time frame.
var (
	timeFrameCountFieldTimeFrame    = big.NewInt(1 << 0)
	timeFrameCountFieldArticleCount = big.NewInt(1 << 1)
)

type TimeFrameCount struct {
	// The timestamp for the aggregation period in format "YYYY-MM-DD HH:mm:ss"
	TimeFrame time.Time `json:"time_frame" url:"time_frame"`
	// The number of articles published during this time frame
	ArticleCount int `json:"article_count" url:"article_count"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TimeFrameCount) GetTimeFrame() time.Time {
	if t == nil {
		return time.Time{}
	}
	return t.TimeFrame
}

func (t *TimeFrameCount) GetArticleCount() int {
	if t == nil {
		return 0
	}
	return t.ArticleCount
}

func (t *TimeFrameCount) GetExtraProperties() map[string]interface{} {
	if t == nil {
		return nil
	}
	return t.extraProperties
}

func (t *TimeFrameCount) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetTimeFrame sets the TimeFrame field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TimeFrameCount) SetTimeFrame(timeFrame time.Time) {
	t.TimeFrame = timeFrame
	t.require(timeFrameCountFieldTimeFrame)
}

// SetArticleCount sets the ArticleCount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TimeFrameCount) SetArticleCount(articleCount int) {
	t.ArticleCount = articleCount
	t.require(timeFrameCountFieldArticleCount)
}

func (t *TimeFrameCount) UnmarshalJSON(data []byte) error {
	type embed TimeFrameCount
	var unmarshaler = struct {
		embed
		TimeFrame *internal.DateTime `json:"time_frame"`
	}{
		embed: embed(*t),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*t = TimeFrameCount(unmarshaler.embed)
	t.TimeFrame = unmarshaler.TimeFrame.Time()
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TimeFrameCount) MarshalJSON() ([]byte, error) {
	type embed TimeFrameCount
	var marshaler = struct {
		embed
		TimeFrame *internal.DateTime `json:"time_frame"`
	}{
		embed:     embed(*t),
		TimeFrame: internal.NewDateTime(t.TimeFrame),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *TimeFrameCount) String() string {
	if t == nil {
		return "<nil>"
	}
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

type AggregationGetRequestPublishedDatePrecision string

const (
	AggregationGetRequestPublishedDatePrecisionFull            AggregationGetRequestPublishedDatePrecision = "full"
	AggregationGetRequestPublishedDatePrecisionTimezoneUnknown AggregationGetRequestPublishedDatePrecision = "timezone unknown"
	AggregationGetRequestPublishedDatePrecisionDate            AggregationGetRequestPublishedDatePrecision = "date"
)

func NewAggregationGetRequestPublishedDatePrecisionFromString(s string) (AggregationGetRequestPublishedDatePrecision, error) {
	switch s {
	case "full":
		return AggregationGetRequestPublishedDatePrecisionFull, nil
	case "timezone unknown":
		return AggregationGetRequestPublishedDatePrecisionTimezoneUnknown, nil
	case "date":
		return AggregationGetRequestPublishedDatePrecisionDate, nil
	}
	var t AggregationGetRequestPublishedDatePrecision
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (a AggregationGetRequestPublishedDatePrecision) Ptr() *AggregationGetRequestPublishedDatePrecision {
	return &a
}

type AggregationGetRequestSortBy string

const (
	AggregationGetRequestSortByRelevancy AggregationGetRequestSortBy = "relevancy"
	AggregationGetRequestSortByDate      AggregationGetRequestSortBy = "date"
	AggregationGetRequestSortByRank      AggregationGetRequestSortBy = "rank"
)

func NewAggregationGetRequestSortByFromString(s string) (AggregationGetRequestSortBy, error) {
	switch s {
	case "relevancy":
		return AggregationGetRequestSortByRelevancy, nil
	case "date":
		return AggregationGetRequestSortByDate, nil
	case "rank":
		return AggregationGetRequestSortByRank, nil
	}
	var t AggregationGetRequestSortBy
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (a AggregationGetRequestSortBy) Ptr() *AggregationGetRequestSortBy {
	return &a
}

type AggregationGetResponse struct {
	AggregationCountResponseDto       *AggregationCountResponseDto
	FailedAggregationCountResponseDto *FailedAggregationCountResponseDto

	typ string
}

func (a *AggregationGetResponse) GetAggregationCountResponseDto() *AggregationCountResponseDto {
	if a == nil {
		return nil
	}
	return a.AggregationCountResponseDto
}

func (a *AggregationGetResponse) GetFailedAggregationCountResponseDto() *FailedAggregationCountResponseDto {
	if a == nil {
		return nil
	}
	return a.FailedAggregationCountResponseDto
}

func (a *AggregationGetResponse) UnmarshalJSON(data []byte) error {
	valueAggregationCountResponseDto := new(AggregationCountResponseDto)
	if err := json.Unmarshal(data, &valueAggregationCountResponseDto); err == nil {
		a.typ = "AggregationCountResponseDto"
		a.AggregationCountResponseDto = valueAggregationCountResponseDto
		return nil
	}
	valueFailedAggregationCountResponseDto := new(FailedAggregationCountResponseDto)
	if err := json.Unmarshal(data, &valueFailedAggregationCountResponseDto); err == nil {
		a.typ = "FailedAggregationCountResponseDto"
		a.FailedAggregationCountResponseDto = valueFailedAggregationCountResponseDto
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, a)
}

func (a AggregationGetResponse) MarshalJSON() ([]byte, error) {
	if a.typ == "AggregationCountResponseDto" || a.AggregationCountResponseDto != nil {
		return json.Marshal(a.AggregationCountResponseDto)
	}
	if a.typ == "FailedAggregationCountResponseDto" || a.FailedAggregationCountResponseDto != nil {
		return json.Marshal(a.FailedAggregationCountResponseDto)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", a)
}

type AggregationGetResponseVisitor interface {
	VisitAggregationCountResponseDto(*AggregationCountResponseDto) error
	VisitFailedAggregationCountResponseDto(*FailedAggregationCountResponseDto) error
}

func (a *AggregationGetResponse) Accept(visitor AggregationGetResponseVisitor) error {
	if a.typ == "AggregationCountResponseDto" || a.AggregationCountResponseDto != nil {
		return visitor.VisitAggregationCountResponseDto(a.AggregationCountResponseDto)
	}
	if a.typ == "FailedAggregationCountResponseDto" || a.FailedAggregationCountResponseDto != nil {
		return visitor.VisitFailedAggregationCountResponseDto(a.FailedAggregationCountResponseDto)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", a)
}

type AggregationPostResponse struct {
	AggregationCountResponseDto       *AggregationCountResponseDto
	FailedAggregationCountResponseDto *FailedAggregationCountResponseDto

	typ string
}

func (a *AggregationPostResponse) GetAggregationCountResponseDto() *AggregationCountResponseDto {
	if a == nil {
		return nil
	}
	return a.AggregationCountResponseDto
}

func (a *AggregationPostResponse) GetFailedAggregationCountResponseDto() *FailedAggregationCountResponseDto {
	if a == nil {
		return nil
	}
	return a.FailedAggregationCountResponseDto
}

func (a *AggregationPostResponse) UnmarshalJSON(data []byte) error {
	valueAggregationCountResponseDto := new(AggregationCountResponseDto)
	if err := json.Unmarshal(data, &valueAggregationCountResponseDto); err == nil {
		a.typ = "AggregationCountResponseDto"
		a.AggregationCountResponseDto = valueAggregationCountResponseDto
		return nil
	}
	valueFailedAggregationCountResponseDto := new(FailedAggregationCountResponseDto)
	if err := json.Unmarshal(data, &valueFailedAggregationCountResponseDto); err == nil {
		a.typ = "FailedAggregationCountResponseDto"
		a.FailedAggregationCountResponseDto = valueFailedAggregationCountResponseDto
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, a)
}

func (a AggregationPostResponse) MarshalJSON() ([]byte, error) {
	if a.typ == "AggregationCountResponseDto" || a.AggregationCountResponseDto != nil {
		return json.Marshal(a.AggregationCountResponseDto)
	}
	if a.typ == "FailedAggregationCountResponseDto" || a.FailedAggregationCountResponseDto != nil {
		return json.Marshal(a.FailedAggregationCountResponseDto)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", a)
}

type AggregationPostResponseVisitor interface {
	VisitAggregationCountResponseDto(*AggregationCountResponseDto) error
	VisitFailedAggregationCountResponseDto(*FailedAggregationCountResponseDto) error
}

func (a *AggregationPostResponse) Accept(visitor AggregationPostResponseVisitor) error {
	if a.typ == "AggregationCountResponseDto" || a.AggregationCountResponseDto != nil {
		return visitor.VisitAggregationCountResponseDto(a.AggregationCountResponseDto)
	}
	if a.typ == "FailedAggregationCountResponseDto" || a.FailedAggregationCountResponseDto != nil {
		return visitor.VisitFailedAggregationCountResponseDto(a.FailedAggregationCountResponseDto)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", a)
}
