// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/Newscatcher/newscatcher-go/v2/internal"
	big "math/big"
)

var (
	authorsGetRequestFieldAuthorName               = big.NewInt(1 << 0)
	authorsGetRequestFieldNotAuthorName            = big.NewInt(1 << 1)
	authorsGetRequestFieldPredefinedSources        = big.NewInt(1 << 2)
	authorsGetRequestFieldSources                  = big.NewInt(1 << 3)
	authorsGetRequestFieldNotSources               = big.NewInt(1 << 4)
	authorsGetRequestFieldLang                     = big.NewInt(1 << 5)
	authorsGetRequestFieldNotLang                  = big.NewInt(1 << 6)
	authorsGetRequestFieldCountries                = big.NewInt(1 << 7)
	authorsGetRequestFieldNotCountries             = big.NewInt(1 << 8)
	authorsGetRequestFieldFrom                     = big.NewInt(1 << 9)
	authorsGetRequestFieldTo                       = big.NewInt(1 << 10)
	authorsGetRequestFieldPublishedDatePrecision   = big.NewInt(1 << 11)
	authorsGetRequestFieldByParseDate              = big.NewInt(1 << 12)
	authorsGetRequestFieldSortBy                   = big.NewInt(1 << 13)
	authorsGetRequestFieldRankedOnly               = big.NewInt(1 << 14)
	authorsGetRequestFieldFromRank                 = big.NewInt(1 << 15)
	authorsGetRequestFieldToRank                   = big.NewInt(1 << 16)
	authorsGetRequestFieldIsHeadline               = big.NewInt(1 << 17)
	authorsGetRequestFieldIsOpinion                = big.NewInt(1 << 18)
	authorsGetRequestFieldIsPaidContent            = big.NewInt(1 << 19)
	authorsGetRequestFieldParentUrl                = big.NewInt(1 << 20)
	authorsGetRequestFieldAllLinks                 = big.NewInt(1 << 21)
	authorsGetRequestFieldAllDomainLinks           = big.NewInt(1 << 22)
	authorsGetRequestFieldAllLinksText             = big.NewInt(1 << 23)
	authorsGetRequestFieldWordCountMin             = big.NewInt(1 << 24)
	authorsGetRequestFieldWordCountMax             = big.NewInt(1 << 25)
	authorsGetRequestFieldPage                     = big.NewInt(1 << 26)
	authorsGetRequestFieldPageSize                 = big.NewInt(1 << 27)
	authorsGetRequestFieldIncludeTranslationFields = big.NewInt(1 << 28)
	authorsGetRequestFieldIncludeNlpData           = big.NewInt(1 << 29)
	authorsGetRequestFieldHasNlp                   = big.NewInt(1 << 30)
	authorsGetRequestFieldTheme                    = big.NewInt(1 << 31)
	authorsGetRequestFieldNotTheme                 = big.NewInt(1 << 32)
	authorsGetRequestFieldNerName                  = big.NewInt(1 << 33)
	authorsGetRequestFieldTitleSentimentMin        = big.NewInt(1 << 34)
	authorsGetRequestFieldTitleSentimentMax        = big.NewInt(1 << 35)
	authorsGetRequestFieldContentSentimentMin      = big.NewInt(1 << 36)
	authorsGetRequestFieldContentSentimentMax      = big.NewInt(1 << 37)
	authorsGetRequestFieldIptcTags                 = big.NewInt(1 << 38)
	authorsGetRequestFieldNotIptcTags              = big.NewInt(1 << 39)
	authorsGetRequestFieldIabTags                  = big.NewInt(1 << 40)
	authorsGetRequestFieldNotIabTags               = big.NewInt(1 << 41)
	authorsGetRequestFieldCustomTags               = big.NewInt(1 << 42)
	authorsGetRequestFieldRobotsCompliant          = big.NewInt(1 << 43)
)

type AuthorsGetRequest struct {
	AuthorName AuthorName `json:"-" url:"author_name"`
	// The list of author names to exclude from your search. To exclude articles by specific authors, use a comma-separated string.
	NotAuthorName *string `json:"-" url:"not_author_name,omitempty"`
	// Predefined top news sources per country.
	//
	// Format: start with the word `top`, followed by the number of desired sources, and then the two-letter country code [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2).
	//
	// Multiple countries with the number of top sources can be specified as a comma-separated string.
	PredefinedSources *string `json:"-" url:"predefined_sources,omitempty"`
	// One or more news sources to narrow down the search. The format must be a domain URL. Subdomains, such as `finance.yahoo.com`, are also acceptable.To specify multiple sources, use a comma-separated string.
	Sources *string `json:"-" url:"sources,omitempty"`
	// The news sources to exclude from the search. To exclude multiple sources, use a comma-separated string.
	NotSources *string `json:"-" url:"not_sources,omitempty"`
	// The language(s) of the search. The only accepted format is the two-letter [ISO 639-1](https://en.wikipedia.org/wiki/ISO_639-1) code. To select multiple languages, use a comma-separated string.
	//
	// To learn more, see [Enumerated parameters > Language](https://www.newscatcherapi.com/docs/news-api/api-reference/enumerated-parameters#language-lang-and-not-lang).
	Lang *string `json:"-" url:"lang,omitempty"`
	// The language(s) to exclude from the search. The accepted format is the two-letter [ISO 639-1](https://en.wikipedia.org/wiki/ISO_639-1) code. To exclude multiple languages, use a comma-separated string.
	//
	// To learn more, see [Enumerated parameters > Language](https://www.newscatcherapi.com/docs/news-api/api-reference/enumerated-parameters#language-lang-and-not-lang).
	NotLang *string `json:"-" url:"not_lang,omitempty"`
	// The countries where the news publisher is located. The accepted format is the two-letter [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) code. To select multiple countries, use a comma-separated string.
	//
	// To learn more, see [Enumerated parameters > Country](https://www.newscatcherapi.com/docs/news-api/api-reference/enumerated-parameters#country-country-and-not-country).
	Countries *string `json:"-" url:"countries,omitempty"`
	// The publisher location countries to exclude from the search. The accepted format is the two-letter [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) code. To exclude multiple countries, use a comma-separated string.
	//
	// To learn more, see [Enumerated parameters > Country](https://www.newscatcherapi.com/docs/news-api/api-reference/enumerated-parameters#country-country-and-not-country).
	NotCountries           *string                 `json:"-" url:"not_countries,omitempty"`
	From                   *From                   `json:"-" url:"from_,omitempty"`
	To                     *To                     `json:"-" url:"to_,omitempty"`
	PublishedDatePrecision *PublishedDatePrecision `json:"-" url:"published_date_precision,omitempty"`
	ByParseDate            *ByParseDate            `json:"-" url:"by_parse_date,omitempty"`
	SortBy                 *SortBy                 `json:"-" url:"sort_by,omitempty"`
	RankedOnly             *RankedOnly             `json:"-" url:"ranked_only,omitempty"`
	FromRank               *FromRank               `json:"-" url:"from_rank,omitempty"`
	ToRank                 *ToRank                 `json:"-" url:"to_rank,omitempty"`
	IsHeadline             *IsHeadline             `json:"-" url:"is_headline,omitempty"`
	IsOpinion              *IsOpinion              `json:"-" url:"is_opinion,omitempty"`
	IsPaidContent          *IsPaidContent          `json:"-" url:"is_paid_content,omitempty"`
	// The categorical URL(s) to filter your search. To filter your search by multiple categorical URLs, use a comma-separated string.
	ParentUrl *string `json:"-" url:"parent_url,omitempty"`
	// The complete URL(s) mentioned in the article. For multiple URLs, use a comma-separated string.
	//
	// For more details, see [Search by URL](https://www.newscatcherapi.com/docs/news-api/how-to/search-by-url).
	AllLinks *string `json:"-" url:"all_links,omitempty"`
	// The domain(s) mentioned in the article. For multiple domains, use a comma-separated string.
	//
	// For more details, see [Search by URL](https://www.newscatcherapi.com/docs/news-api/how-to/search-by-url).
	AllDomainLinks *string `json:"-" url:"all_domain_links,omitempty"`
	// The text content of links mentioned in the article. Searches for links where the anchor text contains the specified terms. For multiple terms, use a comma-separated string.
	//
	// **Note**: When this parameter is used, the response includes the `all_links_data` field with detailed link information.
	//
	// To learn more, see [Search by URL](https://www.newscatcherapi.com/docs/news-api/how-to/search-by-url).
	AllLinksText             *string                   `json:"-" url:"all_links_text,omitempty"`
	WordCountMin             *WordCountMin             `json:"-" url:"word_count_min,omitempty"`
	WordCountMax             *WordCountMax             `json:"-" url:"word_count_max,omitempty"`
	Page                     *Page                     `json:"-" url:"page,omitempty"`
	PageSize                 *PageSize                 `json:"-" url:"page_size,omitempty"`
	IncludeTranslationFields *IncludeTranslationFields `json:"-" url:"include_translation_fields,omitempty"`
	IncludeNlpData           *IncludeNlpData           `json:"-" url:"include_nlp_data,omitempty"`
	HasNlp                   *HasNlp                   `json:"-" url:"has_nlp,omitempty"`
	Theme                    *Theme                    `json:"-" url:"theme,omitempty"`
	NotTheme                 *NotTheme                 `json:"-" url:"not_theme,omitempty"`
	NerName                  *NerName                  `json:"-" url:"ner_name,omitempty"`
	TitleSentimentMin        *TitleSentimentMin        `json:"-" url:"title_sentiment_min,omitempty"`
	TitleSentimentMax        *TitleSentimentMax        `json:"-" url:"title_sentiment_max,omitempty"`
	ContentSentimentMin      *ContentSentimentMin      `json:"-" url:"content_sentiment_min,omitempty"`
	ContentSentimentMax      *ContentSentimentMax      `json:"-" url:"content_sentiment_max,omitempty"`
	// Filters articles based on International Press Telecommunications Council (IPTC) media topic tags. To specify multiple IPTC tags, use a comma-separated string of tag IDs.
	//
	// **Note**: The `iptc_tags` parameter is only available in the `v3_nlp_iptc_tags` subscription plan.
	//
	// To learn more, see [IPTC Media Topic NewsCodes](https://www.iptc.org/std/NewsCodes/treeview/mediatopic/mediatopic-en-GB.html).
	IptcTags *string `json:"-" url:"iptc_tags,omitempty"`
	// Inverse of the `iptc_tags` parameter. Excludes articles based on International Press Telecommunications Council (IPTC) media topic tags. To specify multiple IPTC tags to exclude, use a comma-separated string of tag IDs.
	//
	// **Note**: The `not_iptc_tags` parameter is only available in the `v3_nlp_iptc_tags` subscription plan.
	//
	// To learn more, see [IPTC Media Topic NewsCodes](https://www.iptc.org/std/NewsCodes/treeview/mediatopic/mediatopic-en-GB.html).
	NotIptcTags *string `json:"-" url:"not_iptc_tags,omitempty"`
	// Filters articles based on Interactive Advertising Bureau (IAB) content categories. These tags provide a standardized taxonomy for digital advertising content categorization. To specify multiple IAB categories, use a comma-separated string.
	//
	// **Note**: The `iab_tags` parameter is only available in the `v3_nlp_iptc_tags` subscription plan.
	//
	// To learn more, see the [IAB Content taxonomy](https://iabtechlab.com/standards/content-taxonomy/).
	IabTags *string `json:"-" url:"iab_tags,omitempty"`
	// Inverse of the `iab_tags` parameter. Excludes articles based on Interactive Advertising Bureau (IAB) content categories. These tags provide a standardized taxonomy for digital advertising content categorization. To specify multiple IAB categories to exclude, use a comma-separated string.
	//
	// **Note**: The `not_iab_tags` parameter is only available in the `v3_nlp_iptc_tags` subscription plan.
	//
	// To learn more, see the [IAB Content taxonomy](https://iabtechlab.com/standards/content-taxonomy/).
	NotIabTags *string `json:"-" url:"not_iab_tags,omitempty"`
	// Filters articles based on provided taxonomy that is tailored to your specific needs and is accessible only with your API key. To specify tags, use the following pattern:
	//
	// - `custom_tags.taxonomy=Tag1,Tag2`, where `taxonomy` is the taxonomy name and `Tag1,Tag2` is a comma-separated list of tag names.
	//
	// Example: `custom_tags.industry="Manufacturing,Logistics"`
	//
	// To learn more, see the [Custom tags](https://www.newscatcherapi.com/docs/news-api/guides-and-concepts/custom-tags).
	CustomTags      *string          `json:"-" url:"custom_tags,omitempty"`
	RobotsCompliant *RobotsCompliant `json:"-" url:"robots_compliant,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (a *AuthorsGetRequest) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetAuthorName sets the AuthorName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsGetRequest) SetAuthorName(authorName AuthorName) {
	a.AuthorName = authorName
	a.require(authorsGetRequestFieldAuthorName)
}

// SetNotAuthorName sets the NotAuthorName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsGetRequest) SetNotAuthorName(notAuthorName *string) {
	a.NotAuthorName = notAuthorName
	a.require(authorsGetRequestFieldNotAuthorName)
}

// SetPredefinedSources sets the PredefinedSources field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsGetRequest) SetPredefinedSources(predefinedSources *string) {
	a.PredefinedSources = predefinedSources
	a.require(authorsGetRequestFieldPredefinedSources)
}

// SetSources sets the Sources field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsGetRequest) SetSources(sources *string) {
	a.Sources = sources
	a.require(authorsGetRequestFieldSources)
}

// SetNotSources sets the NotSources field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsGetRequest) SetNotSources(notSources *string) {
	a.NotSources = notSources
	a.require(authorsGetRequestFieldNotSources)
}

// SetLang sets the Lang field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsGetRequest) SetLang(lang *string) {
	a.Lang = lang
	a.require(authorsGetRequestFieldLang)
}

// SetNotLang sets the NotLang field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsGetRequest) SetNotLang(notLang *string) {
	a.NotLang = notLang
	a.require(authorsGetRequestFieldNotLang)
}

// SetCountries sets the Countries field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsGetRequest) SetCountries(countries *string) {
	a.Countries = countries
	a.require(authorsGetRequestFieldCountries)
}

// SetNotCountries sets the NotCountries field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsGetRequest) SetNotCountries(notCountries *string) {
	a.NotCountries = notCountries
	a.require(authorsGetRequestFieldNotCountries)
}

// SetFrom sets the From field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsGetRequest) SetFrom(from *From) {
	a.From = from
	a.require(authorsGetRequestFieldFrom)
}

// SetTo sets the To field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsGetRequest) SetTo(to *To) {
	a.To = to
	a.require(authorsGetRequestFieldTo)
}

// SetPublishedDatePrecision sets the PublishedDatePrecision field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsGetRequest) SetPublishedDatePrecision(publishedDatePrecision *PublishedDatePrecision) {
	a.PublishedDatePrecision = publishedDatePrecision
	a.require(authorsGetRequestFieldPublishedDatePrecision)
}

// SetByParseDate sets the ByParseDate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsGetRequest) SetByParseDate(byParseDate *ByParseDate) {
	a.ByParseDate = byParseDate
	a.require(authorsGetRequestFieldByParseDate)
}

// SetSortBy sets the SortBy field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsGetRequest) SetSortBy(sortBy *SortBy) {
	a.SortBy = sortBy
	a.require(authorsGetRequestFieldSortBy)
}

// SetRankedOnly sets the RankedOnly field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsGetRequest) SetRankedOnly(rankedOnly *RankedOnly) {
	a.RankedOnly = rankedOnly
	a.require(authorsGetRequestFieldRankedOnly)
}

// SetFromRank sets the FromRank field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsGetRequest) SetFromRank(fromRank *FromRank) {
	a.FromRank = fromRank
	a.require(authorsGetRequestFieldFromRank)
}

// SetToRank sets the ToRank field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsGetRequest) SetToRank(toRank *ToRank) {
	a.ToRank = toRank
	a.require(authorsGetRequestFieldToRank)
}

// SetIsHeadline sets the IsHeadline field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsGetRequest) SetIsHeadline(isHeadline *IsHeadline) {
	a.IsHeadline = isHeadline
	a.require(authorsGetRequestFieldIsHeadline)
}

// SetIsOpinion sets the IsOpinion field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsGetRequest) SetIsOpinion(isOpinion *IsOpinion) {
	a.IsOpinion = isOpinion
	a.require(authorsGetRequestFieldIsOpinion)
}

// SetIsPaidContent sets the IsPaidContent field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsGetRequest) SetIsPaidContent(isPaidContent *IsPaidContent) {
	a.IsPaidContent = isPaidContent
	a.require(authorsGetRequestFieldIsPaidContent)
}

// SetParentUrl sets the ParentUrl field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsGetRequest) SetParentUrl(parentUrl *string) {
	a.ParentUrl = parentUrl
	a.require(authorsGetRequestFieldParentUrl)
}

// SetAllLinks sets the AllLinks field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsGetRequest) SetAllLinks(allLinks *string) {
	a.AllLinks = allLinks
	a.require(authorsGetRequestFieldAllLinks)
}

// SetAllDomainLinks sets the AllDomainLinks field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsGetRequest) SetAllDomainLinks(allDomainLinks *string) {
	a.AllDomainLinks = allDomainLinks
	a.require(authorsGetRequestFieldAllDomainLinks)
}

// SetAllLinksText sets the AllLinksText field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsGetRequest) SetAllLinksText(allLinksText *string) {
	a.AllLinksText = allLinksText
	a.require(authorsGetRequestFieldAllLinksText)
}

// SetWordCountMin sets the WordCountMin field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsGetRequest) SetWordCountMin(wordCountMin *WordCountMin) {
	a.WordCountMin = wordCountMin
	a.require(authorsGetRequestFieldWordCountMin)
}

// SetWordCountMax sets the WordCountMax field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsGetRequest) SetWordCountMax(wordCountMax *WordCountMax) {
	a.WordCountMax = wordCountMax
	a.require(authorsGetRequestFieldWordCountMax)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsGetRequest) SetPage(page *Page) {
	a.Page = page
	a.require(authorsGetRequestFieldPage)
}

// SetPageSize sets the PageSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsGetRequest) SetPageSize(pageSize *PageSize) {
	a.PageSize = pageSize
	a.require(authorsGetRequestFieldPageSize)
}

// SetIncludeTranslationFields sets the IncludeTranslationFields field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsGetRequest) SetIncludeTranslationFields(includeTranslationFields *IncludeTranslationFields) {
	a.IncludeTranslationFields = includeTranslationFields
	a.require(authorsGetRequestFieldIncludeTranslationFields)
}

// SetIncludeNlpData sets the IncludeNlpData field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsGetRequest) SetIncludeNlpData(includeNlpData *IncludeNlpData) {
	a.IncludeNlpData = includeNlpData
	a.require(authorsGetRequestFieldIncludeNlpData)
}

// SetHasNlp sets the HasNlp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsGetRequest) SetHasNlp(hasNlp *HasNlp) {
	a.HasNlp = hasNlp
	a.require(authorsGetRequestFieldHasNlp)
}

// SetTheme sets the Theme field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsGetRequest) SetTheme(theme *Theme) {
	a.Theme = theme
	a.require(authorsGetRequestFieldTheme)
}

// SetNotTheme sets the NotTheme field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsGetRequest) SetNotTheme(notTheme *NotTheme) {
	a.NotTheme = notTheme
	a.require(authorsGetRequestFieldNotTheme)
}

// SetNerName sets the NerName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsGetRequest) SetNerName(nerName *NerName) {
	a.NerName = nerName
	a.require(authorsGetRequestFieldNerName)
}

// SetTitleSentimentMin sets the TitleSentimentMin field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsGetRequest) SetTitleSentimentMin(titleSentimentMin *TitleSentimentMin) {
	a.TitleSentimentMin = titleSentimentMin
	a.require(authorsGetRequestFieldTitleSentimentMin)
}

// SetTitleSentimentMax sets the TitleSentimentMax field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsGetRequest) SetTitleSentimentMax(titleSentimentMax *TitleSentimentMax) {
	a.TitleSentimentMax = titleSentimentMax
	a.require(authorsGetRequestFieldTitleSentimentMax)
}

// SetContentSentimentMin sets the ContentSentimentMin field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsGetRequest) SetContentSentimentMin(contentSentimentMin *ContentSentimentMin) {
	a.ContentSentimentMin = contentSentimentMin
	a.require(authorsGetRequestFieldContentSentimentMin)
}

// SetContentSentimentMax sets the ContentSentimentMax field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsGetRequest) SetContentSentimentMax(contentSentimentMax *ContentSentimentMax) {
	a.ContentSentimentMax = contentSentimentMax
	a.require(authorsGetRequestFieldContentSentimentMax)
}

// SetIptcTags sets the IptcTags field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsGetRequest) SetIptcTags(iptcTags *string) {
	a.IptcTags = iptcTags
	a.require(authorsGetRequestFieldIptcTags)
}

// SetNotIptcTags sets the NotIptcTags field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsGetRequest) SetNotIptcTags(notIptcTags *string) {
	a.NotIptcTags = notIptcTags
	a.require(authorsGetRequestFieldNotIptcTags)
}

// SetIabTags sets the IabTags field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsGetRequest) SetIabTags(iabTags *string) {
	a.IabTags = iabTags
	a.require(authorsGetRequestFieldIabTags)
}

// SetNotIabTags sets the NotIabTags field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsGetRequest) SetNotIabTags(notIabTags *string) {
	a.NotIabTags = notIabTags
	a.require(authorsGetRequestFieldNotIabTags)
}

// SetCustomTags sets the CustomTags field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsGetRequest) SetCustomTags(customTags *string) {
	a.CustomTags = customTags
	a.require(authorsGetRequestFieldCustomTags)
}

// SetRobotsCompliant sets the RobotsCompliant field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsGetRequest) SetRobotsCompliant(robotsCompliant *RobotsCompliant) {
	a.RobotsCompliant = robotsCompliant
	a.require(authorsGetRequestFieldRobotsCompliant)
}

var (
	authorsPostRequestFieldAuthorName               = big.NewInt(1 << 0)
	authorsPostRequestFieldNotAuthorName            = big.NewInt(1 << 1)
	authorsPostRequestFieldPredefinedSources        = big.NewInt(1 << 2)
	authorsPostRequestFieldSources                  = big.NewInt(1 << 3)
	authorsPostRequestFieldNotSources               = big.NewInt(1 << 4)
	authorsPostRequestFieldLang                     = big.NewInt(1 << 5)
	authorsPostRequestFieldNotLang                  = big.NewInt(1 << 6)
	authorsPostRequestFieldCountries                = big.NewInt(1 << 7)
	authorsPostRequestFieldNotCountries             = big.NewInt(1 << 8)
	authorsPostRequestFieldFrom                     = big.NewInt(1 << 9)
	authorsPostRequestFieldTo                       = big.NewInt(1 << 10)
	authorsPostRequestFieldPublishedDatePrecision   = big.NewInt(1 << 11)
	authorsPostRequestFieldByParseDate              = big.NewInt(1 << 12)
	authorsPostRequestFieldSortBy                   = big.NewInt(1 << 13)
	authorsPostRequestFieldRankedOnly               = big.NewInt(1 << 14)
	authorsPostRequestFieldFromRank                 = big.NewInt(1 << 15)
	authorsPostRequestFieldToRank                   = big.NewInt(1 << 16)
	authorsPostRequestFieldIsHeadline               = big.NewInt(1 << 17)
	authorsPostRequestFieldIsOpinion                = big.NewInt(1 << 18)
	authorsPostRequestFieldIsPaidContent            = big.NewInt(1 << 19)
	authorsPostRequestFieldParentUrl                = big.NewInt(1 << 20)
	authorsPostRequestFieldAllLinks                 = big.NewInt(1 << 21)
	authorsPostRequestFieldAllDomainLinks           = big.NewInt(1 << 22)
	authorsPostRequestFieldAllLinksText             = big.NewInt(1 << 23)
	authorsPostRequestFieldWordCountMin             = big.NewInt(1 << 24)
	authorsPostRequestFieldWordCountMax             = big.NewInt(1 << 25)
	authorsPostRequestFieldPage                     = big.NewInt(1 << 26)
	authorsPostRequestFieldPageSize                 = big.NewInt(1 << 27)
	authorsPostRequestFieldIncludeTranslationFields = big.NewInt(1 << 28)
	authorsPostRequestFieldIncludeNlpData           = big.NewInt(1 << 29)
	authorsPostRequestFieldHasNlp                   = big.NewInt(1 << 30)
	authorsPostRequestFieldTheme                    = big.NewInt(1 << 31)
	authorsPostRequestFieldNotTheme                 = big.NewInt(1 << 32)
	authorsPostRequestFieldNerName                  = big.NewInt(1 << 33)
	authorsPostRequestFieldTitleSentimentMin        = big.NewInt(1 << 34)
	authorsPostRequestFieldTitleSentimentMax        = big.NewInt(1 << 35)
	authorsPostRequestFieldContentSentimentMin      = big.NewInt(1 << 36)
	authorsPostRequestFieldContentSentimentMax      = big.NewInt(1 << 37)
	authorsPostRequestFieldIptcTags                 = big.NewInt(1 << 38)
	authorsPostRequestFieldNotIptcTags              = big.NewInt(1 << 39)
	authorsPostRequestFieldIabTags                  = big.NewInt(1 << 40)
	authorsPostRequestFieldNotIabTags               = big.NewInt(1 << 41)
	authorsPostRequestFieldCustomTags               = big.NewInt(1 << 42)
	authorsPostRequestFieldRobotsCompliant          = big.NewInt(1 << 43)
)

type AuthorsPostRequest struct {
	AuthorName               AuthorName                `json:"author_name" url:"-"`
	NotAuthorName            *NotAuthorName            `json:"not_author_name,omitempty" url:"-"`
	PredefinedSources        *PredefinedSources        `json:"predefined_sources,omitempty" url:"-"`
	Sources                  *Sources                  `json:"sources,omitempty" url:"-"`
	NotSources               *NotSources               `json:"not_sources,omitempty" url:"-"`
	Lang                     *Lang                     `json:"lang,omitempty" url:"-"`
	NotLang                  *NotLang                  `json:"not_lang,omitempty" url:"-"`
	Countries                *Countries                `json:"countries,omitempty" url:"-"`
	NotCountries             *NotCountries             `json:"not_countries,omitempty" url:"-"`
	From                     *From                     `json:"from_,omitempty" url:"-"`
	To                       *To                       `json:"to_,omitempty" url:"-"`
	PublishedDatePrecision   *PublishedDatePrecision   `json:"published_date_precision,omitempty" url:"-"`
	ByParseDate              *ByParseDate              `json:"by_parse_date,omitempty" url:"-"`
	SortBy                   *SortBy                   `json:"sort_by,omitempty" url:"-"`
	RankedOnly               *RankedOnly               `json:"ranked_only,omitempty" url:"-"`
	FromRank                 *FromRank                 `json:"from_rank,omitempty" url:"-"`
	ToRank                   *ToRank                   `json:"to_rank,omitempty" url:"-"`
	IsHeadline               *IsHeadline               `json:"is_headline,omitempty" url:"-"`
	IsOpinion                *IsOpinion                `json:"is_opinion,omitempty" url:"-"`
	IsPaidContent            *IsPaidContent            `json:"is_paid_content,omitempty" url:"-"`
	ParentUrl                *ParentUrl                `json:"parent_url,omitempty" url:"-"`
	AllLinks                 *AllLinks                 `json:"all_links,omitempty" url:"-"`
	AllDomainLinks           *AllDomainLinks           `json:"all_domain_links,omitempty" url:"-"`
	AllLinksText             *AllLinksText             `json:"all_links_text,omitempty" url:"-"`
	WordCountMin             *WordCountMin             `json:"word_count_min,omitempty" url:"-"`
	WordCountMax             *WordCountMax             `json:"word_count_max,omitempty" url:"-"`
	Page                     *Page                     `json:"page,omitempty" url:"-"`
	PageSize                 *PageSize                 `json:"page_size,omitempty" url:"-"`
	IncludeTranslationFields *IncludeTranslationFields `json:"include_translation_fields,omitempty" url:"-"`
	IncludeNlpData           *IncludeNlpData           `json:"include_nlp_data,omitempty" url:"-"`
	HasNlp                   *HasNlp                   `json:"has_nlp,omitempty" url:"-"`
	Theme                    *Theme                    `json:"theme,omitempty" url:"-"`
	NotTheme                 *NotTheme                 `json:"not_theme,omitempty" url:"-"`
	NerName                  *NerName                  `json:"ner_name,omitempty" url:"-"`
	TitleSentimentMin        *TitleSentimentMin        `json:"title_sentiment_min,omitempty" url:"-"`
	TitleSentimentMax        *TitleSentimentMax        `json:"title_sentiment_max,omitempty" url:"-"`
	ContentSentimentMin      *ContentSentimentMin      `json:"content_sentiment_min,omitempty" url:"-"`
	ContentSentimentMax      *ContentSentimentMax      `json:"content_sentiment_max,omitempty" url:"-"`
	IptcTags                 *IptcTags                 `json:"iptc_tags,omitempty" url:"-"`
	NotIptcTags              *NotIptcTags              `json:"not_iptc_tags,omitempty" url:"-"`
	IabTags                  *IabTags                  `json:"iab_tags,omitempty" url:"-"`
	NotIabTags               *NotIabTags               `json:"not_iab_tags,omitempty" url:"-"`
	CustomTags               *CustomTags               `json:"custom_tags,omitempty" url:"-"`
	RobotsCompliant          *RobotsCompliant          `json:"robots_compliant,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (a *AuthorsPostRequest) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetAuthorName sets the AuthorName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsPostRequest) SetAuthorName(authorName AuthorName) {
	a.AuthorName = authorName
	a.require(authorsPostRequestFieldAuthorName)
}

// SetNotAuthorName sets the NotAuthorName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsPostRequest) SetNotAuthorName(notAuthorName *NotAuthorName) {
	a.NotAuthorName = notAuthorName
	a.require(authorsPostRequestFieldNotAuthorName)
}

// SetPredefinedSources sets the PredefinedSources field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsPostRequest) SetPredefinedSources(predefinedSources *PredefinedSources) {
	a.PredefinedSources = predefinedSources
	a.require(authorsPostRequestFieldPredefinedSources)
}

// SetSources sets the Sources field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsPostRequest) SetSources(sources *Sources) {
	a.Sources = sources
	a.require(authorsPostRequestFieldSources)
}

// SetNotSources sets the NotSources field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsPostRequest) SetNotSources(notSources *NotSources) {
	a.NotSources = notSources
	a.require(authorsPostRequestFieldNotSources)
}

// SetLang sets the Lang field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsPostRequest) SetLang(lang *Lang) {
	a.Lang = lang
	a.require(authorsPostRequestFieldLang)
}

// SetNotLang sets the NotLang field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsPostRequest) SetNotLang(notLang *NotLang) {
	a.NotLang = notLang
	a.require(authorsPostRequestFieldNotLang)
}

// SetCountries sets the Countries field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsPostRequest) SetCountries(countries *Countries) {
	a.Countries = countries
	a.require(authorsPostRequestFieldCountries)
}

// SetNotCountries sets the NotCountries field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsPostRequest) SetNotCountries(notCountries *NotCountries) {
	a.NotCountries = notCountries
	a.require(authorsPostRequestFieldNotCountries)
}

// SetFrom sets the From field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsPostRequest) SetFrom(from *From) {
	a.From = from
	a.require(authorsPostRequestFieldFrom)
}

// SetTo sets the To field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsPostRequest) SetTo(to *To) {
	a.To = to
	a.require(authorsPostRequestFieldTo)
}

// SetPublishedDatePrecision sets the PublishedDatePrecision field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsPostRequest) SetPublishedDatePrecision(publishedDatePrecision *PublishedDatePrecision) {
	a.PublishedDatePrecision = publishedDatePrecision
	a.require(authorsPostRequestFieldPublishedDatePrecision)
}

// SetByParseDate sets the ByParseDate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsPostRequest) SetByParseDate(byParseDate *ByParseDate) {
	a.ByParseDate = byParseDate
	a.require(authorsPostRequestFieldByParseDate)
}

// SetSortBy sets the SortBy field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsPostRequest) SetSortBy(sortBy *SortBy) {
	a.SortBy = sortBy
	a.require(authorsPostRequestFieldSortBy)
}

// SetRankedOnly sets the RankedOnly field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsPostRequest) SetRankedOnly(rankedOnly *RankedOnly) {
	a.RankedOnly = rankedOnly
	a.require(authorsPostRequestFieldRankedOnly)
}

// SetFromRank sets the FromRank field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsPostRequest) SetFromRank(fromRank *FromRank) {
	a.FromRank = fromRank
	a.require(authorsPostRequestFieldFromRank)
}

// SetToRank sets the ToRank field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsPostRequest) SetToRank(toRank *ToRank) {
	a.ToRank = toRank
	a.require(authorsPostRequestFieldToRank)
}

// SetIsHeadline sets the IsHeadline field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsPostRequest) SetIsHeadline(isHeadline *IsHeadline) {
	a.IsHeadline = isHeadline
	a.require(authorsPostRequestFieldIsHeadline)
}

// SetIsOpinion sets the IsOpinion field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsPostRequest) SetIsOpinion(isOpinion *IsOpinion) {
	a.IsOpinion = isOpinion
	a.require(authorsPostRequestFieldIsOpinion)
}

// SetIsPaidContent sets the IsPaidContent field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsPostRequest) SetIsPaidContent(isPaidContent *IsPaidContent) {
	a.IsPaidContent = isPaidContent
	a.require(authorsPostRequestFieldIsPaidContent)
}

// SetParentUrl sets the ParentUrl field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsPostRequest) SetParentUrl(parentUrl *ParentUrl) {
	a.ParentUrl = parentUrl
	a.require(authorsPostRequestFieldParentUrl)
}

// SetAllLinks sets the AllLinks field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsPostRequest) SetAllLinks(allLinks *AllLinks) {
	a.AllLinks = allLinks
	a.require(authorsPostRequestFieldAllLinks)
}

// SetAllDomainLinks sets the AllDomainLinks field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsPostRequest) SetAllDomainLinks(allDomainLinks *AllDomainLinks) {
	a.AllDomainLinks = allDomainLinks
	a.require(authorsPostRequestFieldAllDomainLinks)
}

// SetAllLinksText sets the AllLinksText field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsPostRequest) SetAllLinksText(allLinksText *AllLinksText) {
	a.AllLinksText = allLinksText
	a.require(authorsPostRequestFieldAllLinksText)
}

// SetWordCountMin sets the WordCountMin field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsPostRequest) SetWordCountMin(wordCountMin *WordCountMin) {
	a.WordCountMin = wordCountMin
	a.require(authorsPostRequestFieldWordCountMin)
}

// SetWordCountMax sets the WordCountMax field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsPostRequest) SetWordCountMax(wordCountMax *WordCountMax) {
	a.WordCountMax = wordCountMax
	a.require(authorsPostRequestFieldWordCountMax)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsPostRequest) SetPage(page *Page) {
	a.Page = page
	a.require(authorsPostRequestFieldPage)
}

// SetPageSize sets the PageSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsPostRequest) SetPageSize(pageSize *PageSize) {
	a.PageSize = pageSize
	a.require(authorsPostRequestFieldPageSize)
}

// SetIncludeTranslationFields sets the IncludeTranslationFields field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsPostRequest) SetIncludeTranslationFields(includeTranslationFields *IncludeTranslationFields) {
	a.IncludeTranslationFields = includeTranslationFields
	a.require(authorsPostRequestFieldIncludeTranslationFields)
}

// SetIncludeNlpData sets the IncludeNlpData field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsPostRequest) SetIncludeNlpData(includeNlpData *IncludeNlpData) {
	a.IncludeNlpData = includeNlpData
	a.require(authorsPostRequestFieldIncludeNlpData)
}

// SetHasNlp sets the HasNlp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsPostRequest) SetHasNlp(hasNlp *HasNlp) {
	a.HasNlp = hasNlp
	a.require(authorsPostRequestFieldHasNlp)
}

// SetTheme sets the Theme field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsPostRequest) SetTheme(theme *Theme) {
	a.Theme = theme
	a.require(authorsPostRequestFieldTheme)
}

// SetNotTheme sets the NotTheme field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsPostRequest) SetNotTheme(notTheme *NotTheme) {
	a.NotTheme = notTheme
	a.require(authorsPostRequestFieldNotTheme)
}

// SetNerName sets the NerName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsPostRequest) SetNerName(nerName *NerName) {
	a.NerName = nerName
	a.require(authorsPostRequestFieldNerName)
}

// SetTitleSentimentMin sets the TitleSentimentMin field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsPostRequest) SetTitleSentimentMin(titleSentimentMin *TitleSentimentMin) {
	a.TitleSentimentMin = titleSentimentMin
	a.require(authorsPostRequestFieldTitleSentimentMin)
}

// SetTitleSentimentMax sets the TitleSentimentMax field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsPostRequest) SetTitleSentimentMax(titleSentimentMax *TitleSentimentMax) {
	a.TitleSentimentMax = titleSentimentMax
	a.require(authorsPostRequestFieldTitleSentimentMax)
}

// SetContentSentimentMin sets the ContentSentimentMin field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsPostRequest) SetContentSentimentMin(contentSentimentMin *ContentSentimentMin) {
	a.ContentSentimentMin = contentSentimentMin
	a.require(authorsPostRequestFieldContentSentimentMin)
}

// SetContentSentimentMax sets the ContentSentimentMax field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsPostRequest) SetContentSentimentMax(contentSentimentMax *ContentSentimentMax) {
	a.ContentSentimentMax = contentSentimentMax
	a.require(authorsPostRequestFieldContentSentimentMax)
}

// SetIptcTags sets the IptcTags field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsPostRequest) SetIptcTags(iptcTags *IptcTags) {
	a.IptcTags = iptcTags
	a.require(authorsPostRequestFieldIptcTags)
}

// SetNotIptcTags sets the NotIptcTags field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsPostRequest) SetNotIptcTags(notIptcTags *NotIptcTags) {
	a.NotIptcTags = notIptcTags
	a.require(authorsPostRequestFieldNotIptcTags)
}

// SetIabTags sets the IabTags field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsPostRequest) SetIabTags(iabTags *IabTags) {
	a.IabTags = iabTags
	a.require(authorsPostRequestFieldIabTags)
}

// SetNotIabTags sets the NotIabTags field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsPostRequest) SetNotIabTags(notIabTags *NotIabTags) {
	a.NotIabTags = notIabTags
	a.require(authorsPostRequestFieldNotIabTags)
}

// SetCustomTags sets the CustomTags field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsPostRequest) SetCustomTags(customTags *CustomTags) {
	a.CustomTags = customTags
	a.require(authorsPostRequestFieldCustomTags)
}

// SetRobotsCompliant sets the RobotsCompliant field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AuthorsPostRequest) SetRobotsCompliant(robotsCompliant *RobotsCompliant) {
	a.RobotsCompliant = robotsCompliant
	a.require(authorsPostRequestFieldRobotsCompliant)
}

func (a *AuthorsPostRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler AuthorsPostRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*a = AuthorsPostRequest(body)
	return nil
}

func (a *AuthorsPostRequest) MarshalJSON() ([]byte, error) {
	type embed AuthorsPostRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

// The name of the author to search for. This parameter returns exact matches only.
type AuthorName = string

// The response model for a failed `Authors` search request.
var (
	failedAuthorsResponseDtoFieldStatus     = big.NewInt(1 << 0)
	failedAuthorsResponseDtoFieldTotalHits  = big.NewInt(1 << 1)
	failedAuthorsResponseDtoFieldPage       = big.NewInt(1 << 2)
	failedAuthorsResponseDtoFieldTotalPages = big.NewInt(1 << 3)
	failedAuthorsResponseDtoFieldPageSize   = big.NewInt(1 << 4)
	failedAuthorsResponseDtoFieldArticles   = big.NewInt(1 << 5)
	failedAuthorsResponseDtoFieldUserInput  = big.NewInt(1 << 6)
)

type FailedAuthorsResponseDto struct {
	// The status of the response.
	Status string `json:"status" url:"status"`
	// The total number of articles matching the search criteria.
	TotalHits int `json:"total_hits" url:"total_hits"`
	// The current page number of the results.
	Page int `json:"page" url:"page"`
	// The total number of pages available for the given search criteria.
	TotalPages int `json:"total_pages" url:"total_pages"`
	// The number of articles per page.
	PageSize int `json:"page_size" url:"page_size"`
	// An empty list of articles, as no matches were found.
	Articles  []map[string]interface{} `json:"articles,omitempty" url:"articles,omitempty"`
	UserInput *UserInputDto            `json:"user_input,omitempty" url:"user_input,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (f *FailedAuthorsResponseDto) GetStatus() string {
	if f == nil {
		return ""
	}
	return f.Status
}

func (f *FailedAuthorsResponseDto) GetTotalHits() int {
	if f == nil {
		return 0
	}
	return f.TotalHits
}

func (f *FailedAuthorsResponseDto) GetPage() int {
	if f == nil {
		return 0
	}
	return f.Page
}

func (f *FailedAuthorsResponseDto) GetTotalPages() int {
	if f == nil {
		return 0
	}
	return f.TotalPages
}

func (f *FailedAuthorsResponseDto) GetPageSize() int {
	if f == nil {
		return 0
	}
	return f.PageSize
}

func (f *FailedAuthorsResponseDto) GetArticles() []map[string]interface{} {
	if f == nil {
		return nil
	}
	return f.Articles
}

func (f *FailedAuthorsResponseDto) GetUserInput() *UserInputDto {
	if f == nil {
		return nil
	}
	return f.UserInput
}

func (f *FailedAuthorsResponseDto) GetExtraProperties() map[string]interface{} {
	if f == nil {
		return nil
	}
	return f.extraProperties
}

func (f *FailedAuthorsResponseDto) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FailedAuthorsResponseDto) SetStatus(status string) {
	f.Status = status
	f.require(failedAuthorsResponseDtoFieldStatus)
}

// SetTotalHits sets the TotalHits field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FailedAuthorsResponseDto) SetTotalHits(totalHits int) {
	f.TotalHits = totalHits
	f.require(failedAuthorsResponseDtoFieldTotalHits)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FailedAuthorsResponseDto) SetPage(page int) {
	f.Page = page
	f.require(failedAuthorsResponseDtoFieldPage)
}

// SetTotalPages sets the TotalPages field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FailedAuthorsResponseDto) SetTotalPages(totalPages int) {
	f.TotalPages = totalPages
	f.require(failedAuthorsResponseDtoFieldTotalPages)
}

// SetPageSize sets the PageSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FailedAuthorsResponseDto) SetPageSize(pageSize int) {
	f.PageSize = pageSize
	f.require(failedAuthorsResponseDtoFieldPageSize)
}

// SetArticles sets the Articles field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FailedAuthorsResponseDto) SetArticles(articles []map[string]interface{}) {
	f.Articles = articles
	f.require(failedAuthorsResponseDtoFieldArticles)
}

// SetUserInput sets the UserInput field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FailedAuthorsResponseDto) SetUserInput(userInput *UserInputDto) {
	f.UserInput = userInput
	f.require(failedAuthorsResponseDtoFieldUserInput)
}

func (f *FailedAuthorsResponseDto) UnmarshalJSON(data []byte) error {
	type unmarshaler FailedAuthorsResponseDto
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*f = FailedAuthorsResponseDto(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties
	f.rawJSON = json.RawMessage(data)
	return nil
}

func (f *FailedAuthorsResponseDto) MarshalJSON() ([]byte, error) {
	type embed FailedAuthorsResponseDto
	var marshaler = struct {
		embed
	}{
		embed: embed(*f),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, f.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (f *FailedAuthorsResponseDto) String() string {
	if f == nil {
		return "<nil>"
	}
	if len(f.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(f.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

// The name of person, organization, location, product or other named entity to search for. To specify multiple names use a comma-separated string.
//
// Example: `"Tesla, Amazon"`
type NerName = string

type AuthorsGetResponse struct {
	SearchResponseDto        *SearchResponseDto
	FailedAuthorsResponseDto *FailedAuthorsResponseDto

	typ string
}

func (a *AuthorsGetResponse) GetSearchResponseDto() *SearchResponseDto {
	if a == nil {
		return nil
	}
	return a.SearchResponseDto
}

func (a *AuthorsGetResponse) GetFailedAuthorsResponseDto() *FailedAuthorsResponseDto {
	if a == nil {
		return nil
	}
	return a.FailedAuthorsResponseDto
}

func (a *AuthorsGetResponse) UnmarshalJSON(data []byte) error {
	valueSearchResponseDto := new(SearchResponseDto)
	if err := json.Unmarshal(data, &valueSearchResponseDto); err == nil {
		a.typ = "SearchResponseDto"
		a.SearchResponseDto = valueSearchResponseDto
		return nil
	}
	valueFailedAuthorsResponseDto := new(FailedAuthorsResponseDto)
	if err := json.Unmarshal(data, &valueFailedAuthorsResponseDto); err == nil {
		a.typ = "FailedAuthorsResponseDto"
		a.FailedAuthorsResponseDto = valueFailedAuthorsResponseDto
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, a)
}

func (a AuthorsGetResponse) MarshalJSON() ([]byte, error) {
	if a.typ == "SearchResponseDto" || a.SearchResponseDto != nil {
		return json.Marshal(a.SearchResponseDto)
	}
	if a.typ == "FailedAuthorsResponseDto" || a.FailedAuthorsResponseDto != nil {
		return json.Marshal(a.FailedAuthorsResponseDto)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", a)
}

type AuthorsGetResponseVisitor interface {
	VisitSearchResponseDto(*SearchResponseDto) error
	VisitFailedAuthorsResponseDto(*FailedAuthorsResponseDto) error
}

func (a *AuthorsGetResponse) Accept(visitor AuthorsGetResponseVisitor) error {
	if a.typ == "SearchResponseDto" || a.SearchResponseDto != nil {
		return visitor.VisitSearchResponseDto(a.SearchResponseDto)
	}
	if a.typ == "FailedAuthorsResponseDto" || a.FailedAuthorsResponseDto != nil {
		return visitor.VisitFailedAuthorsResponseDto(a.FailedAuthorsResponseDto)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", a)
}

type AuthorsPostResponse struct {
	SearchResponseDto        *SearchResponseDto
	FailedAuthorsResponseDto *FailedAuthorsResponseDto

	typ string
}

func (a *AuthorsPostResponse) GetSearchResponseDto() *SearchResponseDto {
	if a == nil {
		return nil
	}
	return a.SearchResponseDto
}

func (a *AuthorsPostResponse) GetFailedAuthorsResponseDto() *FailedAuthorsResponseDto {
	if a == nil {
		return nil
	}
	return a.FailedAuthorsResponseDto
}

func (a *AuthorsPostResponse) UnmarshalJSON(data []byte) error {
	valueSearchResponseDto := new(SearchResponseDto)
	if err := json.Unmarshal(data, &valueSearchResponseDto); err == nil {
		a.typ = "SearchResponseDto"
		a.SearchResponseDto = valueSearchResponseDto
		return nil
	}
	valueFailedAuthorsResponseDto := new(FailedAuthorsResponseDto)
	if err := json.Unmarshal(data, &valueFailedAuthorsResponseDto); err == nil {
		a.typ = "FailedAuthorsResponseDto"
		a.FailedAuthorsResponseDto = valueFailedAuthorsResponseDto
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, a)
}

func (a AuthorsPostResponse) MarshalJSON() ([]byte, error) {
	if a.typ == "SearchResponseDto" || a.SearchResponseDto != nil {
		return json.Marshal(a.SearchResponseDto)
	}
	if a.typ == "FailedAuthorsResponseDto" || a.FailedAuthorsResponseDto != nil {
		return json.Marshal(a.FailedAuthorsResponseDto)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", a)
}

type AuthorsPostResponseVisitor interface {
	VisitSearchResponseDto(*SearchResponseDto) error
	VisitFailedAuthorsResponseDto(*FailedAuthorsResponseDto) error
}

func (a *AuthorsPostResponse) Accept(visitor AuthorsPostResponseVisitor) error {
	if a.typ == "SearchResponseDto" || a.SearchResponseDto != nil {
		return visitor.VisitSearchResponseDto(a.SearchResponseDto)
	}
	if a.typ == "FailedAuthorsResponseDto" || a.FailedAuthorsResponseDto != nil {
		return visitor.VisitFailedAuthorsResponseDto(a.FailedAuthorsResponseDto)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", a)
}
