// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/Newscatcher/newscatcher-go/internal"
	big "math/big"
)

var (
	searchUrlPostRequestFieldIds             = big.NewInt(1 << 0)
	searchUrlPostRequestFieldLinks           = big.NewInt(1 << 1)
	searchUrlPostRequestFieldSource          = big.NewInt(1 << 2)
	searchUrlPostRequestFieldFrom            = big.NewInt(1 << 3)
	searchUrlPostRequestFieldTo              = big.NewInt(1 << 4)
	searchUrlPostRequestFieldPage            = big.NewInt(1 << 5)
	searchUrlPostRequestFieldPageSize        = big.NewInt(1 << 6)
	searchUrlPostRequestFieldRobotsCompliant = big.NewInt(1 << 7)
)

type SearchUrlPostRequest struct {
	Ids    *Ids    `json:"ids,omitempty" url:"-"`
	Links  *Links  `json:"links,omitempty" url:"-"`
	Source *Source `json:"_source,omitempty" url:"-"`
	// The starting point in time to search from. Accepts date-time strings in ISO 8601 format and plain text strings. The default time zone is UTC.
	//
	// Formats with examples:
	// - YYYY-mm-ddTHH:MM:SS: `2024-07-01T00:00:00`
	// - YYYY-MM-dd: `2024-07-01`
	// - YYYY/mm/dd HH:MM:SS: `2024/07/01 00:00:00`
	// - YYYY/mm/dd: `2024/07/01`
	// - English phrases: `1 day ago`, `today`
	From *From `json:"from_,omitempty" url:"-"`
	// The ending point in time to search up to. Accepts date-time strings in ISO 8601 format and plain text strings. The default time zone is UTC.
	//
	// Formats with examples:
	// - YYYY-mm-ddTHH:MM:SS: `2024-07-01T00:00:00`
	// - YYYY-MM-dd: `2024-07-01`
	// - YYYY/mm/dd HH:MM:SS: `2024/07/01 00:00:00`
	// - YYYY/mm/dd: `2024/07/01`
	// - English phrases: `1 day ago`, `now`
	To              *To              `json:"to_,omitempty" url:"-"`
	Page            *Page            `json:"page,omitempty" url:"-"`
	PageSize        *PageSize        `json:"page_size,omitempty" url:"-"`
	RobotsCompliant *RobotsCompliant `json:"robots_compliant,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (s *SearchUrlPostRequest) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetIds sets the Ids field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchUrlPostRequest) SetIds(ids *Ids) {
	s.Ids = ids
	s.require(searchUrlPostRequestFieldIds)
}

// SetLinks sets the Links field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchUrlPostRequest) SetLinks(links *Links) {
	s.Links = links
	s.require(searchUrlPostRequestFieldLinks)
}

// SetSource sets the Source field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchUrlPostRequest) SetSource(source *Source) {
	s.Source = source
	s.require(searchUrlPostRequestFieldSource)
}

// SetFrom sets the From field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchUrlPostRequest) SetFrom(from *From) {
	s.From = from
	s.require(searchUrlPostRequestFieldFrom)
}

// SetTo sets the To field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchUrlPostRequest) SetTo(to *To) {
	s.To = to
	s.require(searchUrlPostRequestFieldTo)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchUrlPostRequest) SetPage(page *Page) {
	s.Page = page
	s.require(searchUrlPostRequestFieldPage)
}

// SetPageSize sets the PageSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchUrlPostRequest) SetPageSize(pageSize *PageSize) {
	s.PageSize = pageSize
	s.require(searchUrlPostRequestFieldPageSize)
}

// SetRobotsCompliant sets the RobotsCompliant field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchUrlPostRequest) SetRobotsCompliant(robotsCompliant *RobotsCompliant) {
	s.RobotsCompliant = robotsCompliant
	s.require(searchUrlPostRequestFieldRobotsCompliant)
}

func (s *SearchUrlPostRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler SearchUrlPostRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*s = SearchUrlPostRequest(body)
	return nil
}

func (s *SearchUrlPostRequest) MarshalJSON() ([]byte, error) {
	type embed SearchUrlPostRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	searchUrlGetRequestFieldIds             = big.NewInt(1 << 0)
	searchUrlGetRequestFieldLinks           = big.NewInt(1 << 1)
	searchUrlGetRequestFieldSource          = big.NewInt(1 << 2)
	searchUrlGetRequestFieldFrom            = big.NewInt(1 << 3)
	searchUrlGetRequestFieldTo              = big.NewInt(1 << 4)
	searchUrlGetRequestFieldPage            = big.NewInt(1 << 5)
	searchUrlGetRequestFieldPageSize        = big.NewInt(1 << 6)
	searchUrlGetRequestFieldRobotsCompliant = big.NewInt(1 << 7)
)

type SearchUrlGetRequest struct {
	// The Newscatcher article ID (corresponds to the `_id` field in API response) or a list of article IDs to search for. To specify multiple IDs, use a comma-separated string.
	//
	// Example: `"1234567890abcdef, abcdef1234567890"`
	//
	// **Caution**: You can use either the `links` or the `ids` parameter, but not both at the same time.
	Ids *string `json:"-" url:"ids,omitempty"`
	// The article link or list of article links to search for. To specify multiple links, use a comma-separated string.
	//
	// Example: `"https://example.com/article1, https://example.com/article2"`
	//
	// **Caution**: You can use either the `links` or the `ids` parameter, but not both at the same time.
	Links  *string `json:"-" url:"links,omitempty"`
	Source *Source `json:"-" url:"_source,omitempty"`
	From   *From   `json:"-" url:"from_,omitempty"`
	To     *To     `json:"-" url:"to_,omitempty"`
	// The page number to scroll through the results. Use for pagination, as a single API response can return up to 1,000 articles.
	//
	// For details, see [How to paginate large datasets](https://www.newscatcherapi.com/docs/v3/documentation/how-to/paginate-large-datasets).
	Page *int `json:"-" url:"page,omitempty"`
	// The number of articles to return per page.
	PageSize *int `json:"-" url:"page_size,omitempty"`
	// If true, returns only articles/sources that comply with the publisher's robots.txt rules. If false, returns only articles/sources that do not comply with robots.txt rules. If omitted, returns all articles/sources regardless of compliance status.
	RobotsCompliant *bool `json:"-" url:"robots_compliant,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (s *SearchUrlGetRequest) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetIds sets the Ids field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchUrlGetRequest) SetIds(ids *string) {
	s.Ids = ids
	s.require(searchUrlGetRequestFieldIds)
}

// SetLinks sets the Links field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchUrlGetRequest) SetLinks(links *string) {
	s.Links = links
	s.require(searchUrlGetRequestFieldLinks)
}

// SetSource sets the Source field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchUrlGetRequest) SetSource(source *Source) {
	s.Source = source
	s.require(searchUrlGetRequestFieldSource)
}

// SetFrom sets the From field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchUrlGetRequest) SetFrom(from *From) {
	s.From = from
	s.require(searchUrlGetRequestFieldFrom)
}

// SetTo sets the To field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchUrlGetRequest) SetTo(to *To) {
	s.To = to
	s.require(searchUrlGetRequestFieldTo)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchUrlGetRequest) SetPage(page *int) {
	s.Page = page
	s.require(searchUrlGetRequestFieldPage)
}

// SetPageSize sets the PageSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchUrlGetRequest) SetPageSize(pageSize *int) {
	s.PageSize = pageSize
	s.require(searchUrlGetRequestFieldPageSize)
}

// SetRobotsCompliant sets the RobotsCompliant field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchUrlGetRequest) SetRobotsCompliant(robotsCompliant *bool) {
	s.RobotsCompliant = robotsCompliant
	s.require(searchUrlGetRequestFieldRobotsCompliant)
}

// The Newscatcher article ID (corresponds to the `_id` field in API response) or a list of article IDs to search for. To specify multiple IDs, use a comma-separated string or an array of strings.
//
// Examples:
// - `"5f8d0d55b6e45e00179c6e7e,5f8d0d55b6e45e00179c6e7f"`
// - `["5f8d0d55b6e45e00179c6e7e","5f8d0d55b6e45e00179c6e7f"]`
//
// **Caution**: You can use either the `links` or the `ids` parameter, but not both at the same time.
type Ids struct {
	String     string
	StringList []string

	typ string
}

func (i *Ids) GetString() string {
	if i == nil {
		return ""
	}
	return i.String
}

func (i *Ids) GetStringList() []string {
	if i == nil {
		return nil
	}
	return i.StringList
}

func (i *Ids) UnmarshalJSON(data []byte) error {
	var valueString string
	if err := json.Unmarshal(data, &valueString); err == nil {
		i.typ = "String"
		i.String = valueString
		return nil
	}
	var valueStringList []string
	if err := json.Unmarshal(data, &valueStringList); err == nil {
		i.typ = "StringList"
		i.StringList = valueStringList
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, i)
}

func (i Ids) MarshalJSON() ([]byte, error) {
	if i.typ == "String" || i.String != "" {
		return json.Marshal(i.String)
	}
	if i.typ == "StringList" || i.StringList != nil {
		return json.Marshal(i.StringList)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", i)
}

type IdsVisitor interface {
	VisitString(string) error
	VisitStringList([]string) error
}

func (i *Ids) Accept(visitor IdsVisitor) error {
	if i.typ == "String" || i.String != "" {
		return visitor.VisitString(i.String)
	}
	if i.typ == "StringList" || i.StringList != nil {
		return visitor.VisitStringList(i.StringList)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", i)
}

// The article link or list of article links to search for. To specify multiple links, use a comma-separated string or an array of strings.
//
// Examples:
// - `"https://nytimes.com/article1, https://bbc.com/article2"`
// - `["https://nytimes.com/article1", "https://bbc.com/article2"]`
//
// **Caution**: You can use either the `links` or the `ids` parameter, but not both at the same time.
type Links struct {
	String     string
	StringList []string

	typ string
}

func (l *Links) GetString() string {
	if l == nil {
		return ""
	}
	return l.String
}

func (l *Links) GetStringList() []string {
	if l == nil {
		return nil
	}
	return l.StringList
}

func (l *Links) UnmarshalJSON(data []byte) error {
	var valueString string
	if err := json.Unmarshal(data, &valueString); err == nil {
		l.typ = "String"
		l.String = valueString
		return nil
	}
	var valueStringList []string
	if err := json.Unmarshal(data, &valueStringList); err == nil {
		l.typ = "StringList"
		l.StringList = valueStringList
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, l)
}

func (l Links) MarshalJSON() ([]byte, error) {
	if l.typ == "String" || l.String != "" {
		return json.Marshal(l.String)
	}
	if l.typ == "StringList" || l.StringList != nil {
		return json.Marshal(l.StringList)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", l)
}

type LinksVisitor interface {
	VisitString(string) error
	VisitStringList([]string) error
}

func (l *Links) Accept(visitor LinksVisitor) error {
	if l.typ == "String" || l.String != "" {
		return visitor.VisitString(l.String)
	}
	if l.typ == "StringList" || l.StringList != nil {
		return visitor.VisitStringList(l.StringList)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", l)
}

// Specifies which article fields to include in the response.
// Separate multiple fields with commas. For nested fields, use dot notation:
//
// - Top-level fields: `page_size`, `total_pages`, `status`
// - Article fields: `articles.id`, `articles.title`, `articles.content`
// - Nested fields: `articles.nlp.summary`, `articles.nlp.sentiment.title`
type Source = string
