// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/Newscatcher/newscatcher-go/v2/internal"
	big "math/big"
)

var (
	searchByLinkGetRequestFieldIds             = big.NewInt(1 << 0)
	searchByLinkGetRequestFieldLinks           = big.NewInt(1 << 1)
	searchByLinkGetRequestFieldFrom            = big.NewInt(1 << 2)
	searchByLinkGetRequestFieldTo              = big.NewInt(1 << 3)
	searchByLinkGetRequestFieldPage            = big.NewInt(1 << 4)
	searchByLinkGetRequestFieldPageSize        = big.NewInt(1 << 5)
	searchByLinkGetRequestFieldRobotsCompliant = big.NewInt(1 << 6)
)

type SearchByLinkGetRequest struct {
	// The Newscatcher article ID (corresponds to the `_id` field in API response) or a list of article IDs to search for. To specify multiple IDs, use a comma-separated string.
	//
	// **Caution**: You can use either the `links` or the `ids` parameter, but not both at the same time.
	Ids *string `json:"-" url:"ids,omitempty"`
	// The article link or list of article links to search for. To specify multiple links, use a comma-separated string.
	//
	// **Caution**: You can use either the `links` or the `ids` parameter, but not both at the same time.
	Links           *string          `json:"-" url:"links,omitempty"`
	From            *From            `json:"-" url:"from_,omitempty"`
	To              *To              `json:"-" url:"to_,omitempty"`
	Page            *Page            `json:"-" url:"page,omitempty"`
	PageSize        *PageSize        `json:"-" url:"page_size,omitempty"`
	RobotsCompliant *RobotsCompliant `json:"-" url:"robots_compliant,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (s *SearchByLinkGetRequest) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetIds sets the Ids field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchByLinkGetRequest) SetIds(ids *string) {
	s.Ids = ids
	s.require(searchByLinkGetRequestFieldIds)
}

// SetLinks sets the Links field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchByLinkGetRequest) SetLinks(links *string) {
	s.Links = links
	s.require(searchByLinkGetRequestFieldLinks)
}

// SetFrom sets the From field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchByLinkGetRequest) SetFrom(from *From) {
	s.From = from
	s.require(searchByLinkGetRequestFieldFrom)
}

// SetTo sets the To field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchByLinkGetRequest) SetTo(to *To) {
	s.To = to
	s.require(searchByLinkGetRequestFieldTo)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchByLinkGetRequest) SetPage(page *Page) {
	s.Page = page
	s.require(searchByLinkGetRequestFieldPage)
}

// SetPageSize sets the PageSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchByLinkGetRequest) SetPageSize(pageSize *PageSize) {
	s.PageSize = pageSize
	s.require(searchByLinkGetRequestFieldPageSize)
}

// SetRobotsCompliant sets the RobotsCompliant field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchByLinkGetRequest) SetRobotsCompliant(robotsCompliant *RobotsCompliant) {
	s.RobotsCompliant = robotsCompliant
	s.require(searchByLinkGetRequestFieldRobotsCompliant)
}

var (
	searchByLinkPostRequestFieldIds             = big.NewInt(1 << 0)
	searchByLinkPostRequestFieldLinks           = big.NewInt(1 << 1)
	searchByLinkPostRequestFieldFrom            = big.NewInt(1 << 2)
	searchByLinkPostRequestFieldTo              = big.NewInt(1 << 3)
	searchByLinkPostRequestFieldPage            = big.NewInt(1 << 4)
	searchByLinkPostRequestFieldPageSize        = big.NewInt(1 << 5)
	searchByLinkPostRequestFieldRobotsCompliant = big.NewInt(1 << 6)
)

type SearchByLinkPostRequest struct {
	Ids   *Ids   `json:"ids,omitempty" url:"-"`
	Links *Links `json:"links,omitempty" url:"-"`
	// The starting point in time to search from. Accepts date-time strings in ISO 8601 format and plain text strings. The default time zone is UTC.
	//
	// Formats with examples:
	// - YYYY-mm-ddTHH:MM:SS: `2024-07-01T00:00:00`
	// - YYYY-MM-dd: `2024-07-01`
	// - YYYY/mm/dd HH:MM:SS: `2024/07/01 00:00:00`
	// - YYYY/mm/dd: `2024/07/01`
	// - English phrases: `1 day ago`, `today`
	From *From `json:"from_,omitempty" url:"-"`
	// The ending point in time to search up to. Accepts date-time strings in ISO 8601 format and plain text strings. The default time zone is UTC.
	//
	// Formats with examples:
	// - YYYY-mm-ddTHH:MM:SS: `2024-07-01T00:00:00`
	// - YYYY-MM-dd: `2024-07-01`
	// - YYYY/mm/dd HH:MM:SS: `2024/07/01 00:00:00`
	// - YYYY/mm/dd: `2024/07/01`
	// - English phrases: `1 day ago`, `now`
	To              *To              `json:"to_,omitempty" url:"-"`
	Page            *Page            `json:"page,omitempty" url:"-"`
	PageSize        *PageSize        `json:"page_size,omitempty" url:"-"`
	RobotsCompliant *RobotsCompliant `json:"robots_compliant,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (s *SearchByLinkPostRequest) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetIds sets the Ids field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchByLinkPostRequest) SetIds(ids *Ids) {
	s.Ids = ids
	s.require(searchByLinkPostRequestFieldIds)
}

// SetLinks sets the Links field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchByLinkPostRequest) SetLinks(links *Links) {
	s.Links = links
	s.require(searchByLinkPostRequestFieldLinks)
}

// SetFrom sets the From field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchByLinkPostRequest) SetFrom(from *From) {
	s.From = from
	s.require(searchByLinkPostRequestFieldFrom)
}

// SetTo sets the To field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchByLinkPostRequest) SetTo(to *To) {
	s.To = to
	s.require(searchByLinkPostRequestFieldTo)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchByLinkPostRequest) SetPage(page *Page) {
	s.Page = page
	s.require(searchByLinkPostRequestFieldPage)
}

// SetPageSize sets the PageSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchByLinkPostRequest) SetPageSize(pageSize *PageSize) {
	s.PageSize = pageSize
	s.require(searchByLinkPostRequestFieldPageSize)
}

// SetRobotsCompliant sets the RobotsCompliant field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchByLinkPostRequest) SetRobotsCompliant(robotsCompliant *RobotsCompliant) {
	s.RobotsCompliant = robotsCompliant
	s.require(searchByLinkPostRequestFieldRobotsCompliant)
}

func (s *SearchByLinkPostRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler SearchByLinkPostRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*s = SearchByLinkPostRequest(body)
	return nil
}

func (s *SearchByLinkPostRequest) MarshalJSON() ([]byte, error) {
	type embed SearchByLinkPostRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

// The Newscatcher article ID (corresponds to the `_id` field in API response) or a list of article IDs to search for. To specify multiple IDs, use a comma-separated string or an array of strings.
//
// **Caution**: You can use either the `links` or the `ids` parameter, but not both at the same time.
type Ids struct {
	String     string
	StringList []string

	typ string
}

func (i *Ids) GetString() string {
	if i == nil {
		return ""
	}
	return i.String
}

func (i *Ids) GetStringList() []string {
	if i == nil {
		return nil
	}
	return i.StringList
}

func (i *Ids) UnmarshalJSON(data []byte) error {
	var valueString string
	if err := json.Unmarshal(data, &valueString); err == nil {
		i.typ = "String"
		i.String = valueString
		return nil
	}
	var valueStringList []string
	if err := json.Unmarshal(data, &valueStringList); err == nil {
		i.typ = "StringList"
		i.StringList = valueStringList
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, i)
}

func (i Ids) MarshalJSON() ([]byte, error) {
	if i.typ == "String" || i.String != "" {
		return json.Marshal(i.String)
	}
	if i.typ == "StringList" || i.StringList != nil {
		return json.Marshal(i.StringList)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", i)
}

type IdsVisitor interface {
	VisitString(string) error
	VisitStringList([]string) error
}

func (i *Ids) Accept(visitor IdsVisitor) error {
	if i.typ == "String" || i.String != "" {
		return visitor.VisitString(i.String)
	}
	if i.typ == "StringList" || i.StringList != nil {
		return visitor.VisitStringList(i.StringList)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", i)
}

// The article link or list of article links to search for. To specify multiple links, use a comma-separated string or an array of strings.
//
// **Caution**: You can use either the `links` or the `ids` parameter, but not both at the same time.
type Links struct {
	String     string
	StringList []string

	typ string
}

func (l *Links) GetString() string {
	if l == nil {
		return ""
	}
	return l.String
}

func (l *Links) GetStringList() []string {
	if l == nil {
		return nil
	}
	return l.StringList
}

func (l *Links) UnmarshalJSON(data []byte) error {
	var valueString string
	if err := json.Unmarshal(data, &valueString); err == nil {
		l.typ = "String"
		l.String = valueString
		return nil
	}
	var valueStringList []string
	if err := json.Unmarshal(data, &valueStringList); err == nil {
		l.typ = "StringList"
		l.StringList = valueStringList
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, l)
}

func (l Links) MarshalJSON() ([]byte, error) {
	if l.typ == "String" || l.String != "" {
		return json.Marshal(l.String)
	}
	if l.typ == "StringList" || l.StringList != nil {
		return json.Marshal(l.StringList)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", l)
}

type LinksVisitor interface {
	VisitString(string) error
	VisitStringList([]string) error
}

func (l *Links) Accept(visitor LinksVisitor) error {
	if l.typ == "String" || l.String != "" {
		return visitor.VisitString(l.String)
	}
	if l.typ == "StringList" || l.StringList != nil {
		return visitor.VisitStringList(l.StringList)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", l)
}
