// Code generated by Fern. DO NOT EDIT.

package latestheadlines

import (
	context "context"
	newscatchergo "github.com/Newscatcher/newscatcher-go"
	core "github.com/Newscatcher/newscatcher-go/core"
	internal "github.com/Newscatcher/newscatcher-go/internal"
	option "github.com/Newscatcher/newscatcher-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Retrieves the latest headlines for the specified time period. You can filter results by language, country, source, and more.
func (c *Client) Get(
	ctx context.Context,
	request *newscatchergo.LatestHeadlinesGetRequest,
	opts ...option.RequestOption,
) (*newscatchergo.LatestHeadlinesGetResponse, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieves the latest headlines for the specified time period. You can filter results by language, country, source, and more.
func (c *Client) Post(
	ctx context.Context,
	request *newscatchergo.LatestHeadlinesPostRequest,
	opts ...option.RequestOption,
) (*newscatchergo.LatestHeadlinesPostResponse, error) {
	response, err := c.WithRawResponse.Post(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
