// Code generated by Fern. DO NOT EDIT.

package breaking_news_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	v505 "github.com/Newscatcher/newscatcher-go/v2"
	client "github.com/Newscatcher/newscatcher-go/v2/client"
	option "github.com/Newscatcher/newscatcher-go/v2/option"
	require "github.com/stretchr/testify/require"
	http "net/http"
	os "os"
	testing "testing"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestBreakingNewsBreakingNewsGetWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &v505.BreakingNewsGetRequest{
		RankedOnly: v505.Bool(
			true,
		),
		FromRank: v505.Int(
			100,
		),
		ToRank: v505.Int(
			100,
		),
		Page: v505.Int(
			2,
		),
		PageSize: v505.Int(
			50,
		),
		TopNArticles: v505.Int(
			5,
		),
		IncludeTranslationFields: v505.Bool(
			true,
		),
		IncludeNlpData: v505.Bool(
			true,
		),
		HasNlp: v505.Bool(
			true,
		),
		Theme: v505.String(
			"Finance,Tech",
		),
		NotTheme: v505.String(
			"Crime,Sports",
		),
		OrgEntityName: v505.String(
			`"Apple Inc" OR Microsoft`,
		),
		PerEntityName: v505.String(
			`"Elon Musk" OR "Jeff Bezos"`,
		),
		LocEntityName: v505.String(
			`"San Francisco" OR "New York City"`,
		),
		MiscEntityName: v505.String(
			`AWS OR "Microsoft Azure"`,
		),
		TitleSentimentMin: v505.Float64(
			-0.5,
		),
		TitleSentimentMax: v505.Float64(
			0.5,
		),
		ContentSentimentMin: v505.Float64(
			-0.5,
		),
		ContentSentimentMax: v505.Float64(
			0.5,
		),
	}
	_, invocationErr := client.BreakingNews.BreakingNewsGet(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBreakingNewsBreakingNewsGetWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBreakingNewsBreakingNewsGetWithWireMock", "GET", "/api/breaking_news", map[string]string{"ranked_only": "true", "from_rank": "100", "to_rank": "100", "page": "2", "page_size": "50", "top_n_articles": "5", "include_translation_fields": "true", "include_nlp_data": "true", "has_nlp": "true", "theme": "Finance,Tech", "not_theme": "Crime,Sports", "ORG_entity_name": "\"Apple Inc\" OR Microsoft", "PER_entity_name": "\"Elon Musk\" OR \"Jeff Bezos\"", "LOC_entity_name": "\"San Francisco\" OR \"New York City\"", "MISC_entity_name": "AWS OR \"Microsoft Azure\"", "title_sentiment_min": "-0.5", "title_sentiment_max": "0.5", "content_sentiment_min": "-0.5", "content_sentiment_max": "0.5"}, 1)
}

func TestBreakingNewsBreakingNewsPostWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &v505.BreakingNewsPostRequest{
		SortBy: v505.SortByRelevancy.Ptr(),
		RankedOnly: v505.Bool(
			true,
		),
		TopNArticles: v505.Int(
			1,
		),
	}
	_, invocationErr := client.BreakingNews.BreakingNewsPost(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestBreakingNewsBreakingNewsPostWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestBreakingNewsBreakingNewsPostWithWireMock", "POST", "/api/breaking_news", nil, 1)
}
