// Code generated by Fern. DO NOT EDIT.

package breakingnews

import (
	context "context"
	newscatchergo "github.com/Newscatcher/newscatcher-go"
	core "github.com/Newscatcher/newscatcher-go/core"
	internal "github.com/Newscatcher/newscatcher-go/internal"
	option "github.com/Newscatcher/newscatcher-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Retrieves breaking news articles and sorts them based on specified criteria.
func (c *Client) BreakingNewsGet(
	ctx context.Context,
	request *newscatchergo.BreakingNewsGetRequest,
	opts ...option.RequestOption,
) (*newscatchergo.BreakingNewsResponseDto, error) {
	response, err := c.WithRawResponse.BreakingNewsGet(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieves breaking news articles and sorts them based on specified criteria.
func (c *Client) BreakingNewsPost(
	ctx context.Context,
	request *newscatchergo.BreakingNewsPostRequest,
	opts ...option.RequestOption,
) (*newscatchergo.BreakingNewsResponseDto, error) {
	response, err := c.WithRawResponse.BreakingNewsPost(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
