// Code generated by Fern. DO NOT EDIT.

package authors

import (
	context "context"

	newscatchergo "github.com/Newscatcher/newscatcher-go"
	core "github.com/Newscatcher/newscatcher-go/core"
	internal "github.com/Newscatcher/newscatcher-go/internal"
	option "github.com/Newscatcher/newscatcher-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Searches for articles written by a specified author. You can filter results by language, country, source, and more.
//
// Example:
//
//	request := &newscatchergo.GetAuthorsRequest{
//	    AuthorName: "Jane Smith",
//	    NotAuthorName: newscatchergo.String(
//	        "John Doe, Jane Doe",
//	    ),
//	    PredefinedSources: newscatchergo.String(
//	        "top 50 US, top 20 GB",
//	    ),
//	    Sources: newscatchergo.String(
//	        "nytimes.com,finance.yahoo.com",
//	    ),
//	    NotSources: newscatchergo.String(
//	        "cnn.com,wsj.com",
//	    ),
//	    Lang: newscatchergo.String(
//	        "en,es",
//	    ),
//	    NotLang: newscatchergo.String(
//	        "fr,de",
//	    ),
//	    Countries: newscatchergo.String(
//	        "US,CA",
//	    ),
//	    NotCountries: newscatchergo.String(
//	        "UK,FR",
//	    ),
//	    From: &newscatchergo.From{
//	        DateTime: newscatchergo.MustParseDateTime(
//	            "1 day ago",
//	        ),
//	    },
//	    To: &newscatchergo.To{
//	        String: "now",
//	    },
//	    PublishedDatePrecision: newscatchergo.String(
//	        "full",
//	    ),
//	    ByParseDate: newscatchergo.Bool(
//	        true,
//	    ),
//	    RankedOnly: newscatchergo.Bool(
//	        true,
//	    ),
//	    FromRank: newscatchergo.Int(
//	        100,
//	    ),
//	    ToRank: newscatchergo.Int(
//	        100,
//	    ),
//	    IsHeadline: newscatchergo.Bool(
//	        true,
//	    ),
//	    IsOpinion: newscatchergo.Bool(
//	        true,
//	    ),
//	    IsPaidContent: newscatchergo.Bool(
//	        false,
//	    ),
//	    ParentUrl: newscatchergo.String(
//	        "wsj.com/politics,wsj.com/tech",
//	    ),
//	    AllLinks: newscatchergo.String(
//	        "https://aiindex.stanford.edu/report,https://www.stateof.ai",
//	    ),
//	    AllDomainLinks: newscatchergo.String(
//	        "who.int,nih.gov",
//	    ),
//	    AllLinksText: newscatchergo.String(
//	        "Nvidia,Tesla",
//	    ),
//	    WordCountMin: newscatchergo.Int(
//	        300,
//	    ),
//	    WordCountMax: newscatchergo.Int(
//	        1000,
//	    ),
//	    Page: newscatchergo.Int(
//	        2,
//	    ),
//	    PageSize: newscatchergo.Int(
//	        50,
//	    ),
//	    IncludeTranslationFields: newscatchergo.Bool(
//	        true,
//	    ),
//	    IncludeNlpData: newscatchergo.Bool(
//	        true,
//	    ),
//	    HasNlp: newscatchergo.Bool(
//	        true,
//	    ),
//	    Theme: newscatchergo.String(
//	        "Finance,Tech",
//	    ),
//	    NotTheme: newscatchergo.String(
//	        "Crime,Sports",
//	    ),
//	    NerName: newscatchergo.String(
//	        "Tesla,Amazon",
//	    ),
//	    TitleSentimentMin: newscatchergo.Float64(
//	        -0.5,
//	    ),
//	    TitleSentimentMax: newscatchergo.Float64(
//	        0.5,
//	    ),
//	    ContentSentimentMin: newscatchergo.Float64(
//	        -0.5,
//	    ),
//	    ContentSentimentMax: newscatchergo.Float64(
//	        0.5,
//	    ),
//	    IptcTags: newscatchergo.String(
//	        "20000199,20000209",
//	    ),
//	    NotIptcTags: newscatchergo.String(
//	        "20000205,20000209",
//	    ),
//	    IabTags: newscatchergo.String(
//	        "Business,Events",
//	    ),
//	    NotIabTags: newscatchergo.String(
//	        "Agriculture,Metals",
//	    ),
//	    CustomTags: newscatchergo.String(
//	        "Tag1,Tag2",
//	    ),
//	    RobotsCompliant: newscatchergo.Bool(
//	        true,
//	    ),
//	}
//	client.Authors.Get(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Get(
	ctx context.Context,
	request *newscatchergo.GetAuthorsRequest,
	opts ...option.RequestOption,
) (*newscatchergo.GetAuthorsResponse, error) {
	response, err := c.WithRawResponse.Get(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Searches for articles by author. You can filter results by language, country, source, and more.
//
// Example:
//
//	request := &newscatchergo.PostAuthorsRequest{
//	    AuthorName: "David Muir",
//	}
//	client.Authors.Post(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) Post(
	ctx context.Context,
	request *newscatchergo.PostAuthorsRequest,
	opts ...option.RequestOption,
) (*newscatchergo.PostAuthorsResponse, error) {
	response, err := c.WithRawResponse.Post(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
