// Code generated by Fern. DO NOT EDIT.

package search_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	v505 "github.com/Newscatcher/newscatcher-go"
	client "github.com/Newscatcher/newscatcher-go/client"
	option "github.com/Newscatcher/newscatcher-go/option"
	require "github.com/stretchr/testify/require"
	http "net/http"
	os "os"
	testing "testing"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestSearchGetWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &v505.SearchGetRequest{
		Q: `"supply chain" AND Amazon NOT China`,
		SearchIn: v505.String(
			"title_content, title_content_translated",
		),
		IncludeTranslationFields: v505.Bool(
			true,
		),
		PredefinedSources: v505.String(
			"top 100 US, top 5 GB",
		),
		SourceName: v505.String(
			"sport",
		),
		Sources: v505.String(
			"nytimes.com",
		),
		NotSources: v505.String(
			"cnn.com",
		),
		Lang: v505.String(
			"en",
		),
		NotLang: v505.String(
			"fr",
		),
		Countries: v505.String(
			"US",
		),
		NotCountries: v505.String(
			"UK",
		),
		NotAuthorName: v505.String(
			"John Doe",
		),
		From: &v505.SearchGetRequestFrom{
			DateTime: v505.MustParseDateTime(
				"2024-07-01T00:00:00Z",
			),
		},
		To: &v505.SearchGetRequestTo{
			DateTime: v505.MustParseDateTime(
				"2024-07-01T00:00:00Z",
			),
		},
		ParentUrl: v505.String(
			"https://www.washingtonpost.com/politics",
		),
		AllLinks: v505.String(
			"https://aiindex.stanford.edu/report",
		),
		AllDomainLinks: v505.String(
			"nvidia.com",
		),
		NewsType: v505.String(
			"General News Outlets",
		),
		IncludeNlpData: v505.Bool(
			true,
		),
		HasNlp: v505.Bool(
			true,
		),
		Theme: v505.String(
			"Business,Finance",
		),
		NotTheme: v505.String(
			"Crime",
		),
		OrgEntityName: v505.String(
			"Apple",
		),
		PerEntityName: v505.String(
			"Elon Musk",
		),
		LocEntityName: v505.String(
			"California",
		),
		MiscEntityName: v505.String(
			"Bitcoin",
		),
		IptcTags: v505.String(
			"20000199,20000209",
		),
		NotIptcTags: v505.String(
			"20000205,20000209",
		),
		IabTags: v505.String(
			"Business,Events",
		),
		NotIabTags: v505.String(
			"Agriculture,Metals",
		),
		CustomTags: v505.String(
			"Tag1,Tag2,Tag3",
		),
	}
	_, invocationErr := client.Search.Get(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSearchGetWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSearchGetWithWireMock", "GET", "/api/search", map[string]string{"q": "\"supply chain\" AND Amazon NOT China", "search_in": "title_content, title_content_translated", "include_translation_fields": "true", "predefined_sources": "top 100 US, top 5 GB", "source_name": "sport", "sources": "nytimes.com", "not_sources": "cnn.com", "lang": "en", "not_lang": "fr", "countries": "US", "not_countries": "UK", "not_author_name": "John Doe", "from_": "2024-07-01T00:00:00Z", "to_": "2024-07-01T00:00:00Z", "parent_url": "https://www.washingtonpost.com/politics", "all_links": "https://aiindex.stanford.edu/report", "all_domain_links": "nvidia.com", "news_type": "General News Outlets", "include_nlp_data": "true", "has_nlp": "true", "theme": "Business,Finance", "not_theme": "Crime", "ORG_entity_name": "Apple", "PER_entity_name": "Elon Musk", "LOC_entity_name": "California", "MISC_entity_name": "Bitcoin", "iptc_tags": "20000199,20000209", "not_iptc_tags": "20000205,20000209", "iab_tags": "Business,Events", "not_iab_tags": "Agriculture,Metals", "custom_tags": "Tag1,Tag2,Tag3"}, 1)
}

func TestSearchPostWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &v505.SearchPostRequest{
		Q: `"supply chain" AND Amazon NOT China`,
		PageSize: v505.Int(
			1,
		),
	}
	_, invocationErr := client.Search.Post(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSearchPostWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSearchPostWithWireMock", "POST", "/api/search", nil, 1)
}
