// Code generated by Fern. DO NOT EDIT.

package authors_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	newscatchergo "github.com/Newscatcher/newscatcher-go"
	client "github.com/Newscatcher/newscatcher-go/client"
	option "github.com/Newscatcher/newscatcher-go/option"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestAuthorsGetWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithApiKey("test-value"),
	)
	request := &newscatchergo.GetAuthorsRequest{
		AuthorName: "Jane Smith",
		NotAuthorName: newscatchergo.String(
			"John Doe, Jane Doe",
		),
		PredefinedSources: newscatchergo.String(
			"top 50 US, top 20 GB",
		),
		Sources: newscatchergo.String(
			"nytimes.com,finance.yahoo.com",
		),
		NotSources: newscatchergo.String(
			"cnn.com,wsj.com",
		),
		Lang: newscatchergo.String(
			"en,es",
		),
		NotLang: newscatchergo.String(
			"fr,de",
		),
		Countries: newscatchergo.String(
			"US,CA",
		),
		NotCountries: newscatchergo.String(
			"UK,FR",
		),
		From: &newscatchergo.From{
			DateTime: newscatchergo.MustParseDateTime(
				"1 day ago",
			),
		},
		To: &newscatchergo.To{
			DateTime: newscatchergo.MustParseDateTime(
				"1 day ago",
			),
		},
		PublishedDatePrecision: newscatchergo.String(
			"full",
		),
		ByParseDate: newscatchergo.Bool(
			true,
		),
		RankedOnly: newscatchergo.Bool(
			true,
		),
		FromRank: newscatchergo.Int(
			100,
		),
		ToRank: newscatchergo.Int(
			100,
		),
		IsHeadline: newscatchergo.Bool(
			true,
		),
		IsOpinion: newscatchergo.Bool(
			true,
		),
		IsPaidContent: newscatchergo.Bool(
			false,
		),
		ParentUrl: newscatchergo.String(
			"wsj.com/politics,wsj.com/tech",
		),
		AllLinks: newscatchergo.String(
			"https://aiindex.stanford.edu/report,https://www.stateof.ai",
		),
		AllDomainLinks: newscatchergo.String(
			"who.int,nih.gov",
		),
		AllLinksText: newscatchergo.String(
			"Nvidia,Tesla",
		),
		WordCountMin: newscatchergo.Int(
			300,
		),
		WordCountMax: newscatchergo.Int(
			1000,
		),
		Page: newscatchergo.Int(
			2,
		),
		PageSize: newscatchergo.Int(
			50,
		),
		IncludeTranslationFields: newscatchergo.Bool(
			true,
		),
		IncludeNlpData: newscatchergo.Bool(
			true,
		),
		HasNlp: newscatchergo.Bool(
			true,
		),
		Theme: newscatchergo.String(
			"Finance,Tech",
		),
		NotTheme: newscatchergo.String(
			"Crime,Sports",
		),
		NerName: newscatchergo.String(
			"Tesla,Amazon",
		),
		TitleSentimentMin: newscatchergo.Float64(
			-0.5,
		),
		TitleSentimentMax: newscatchergo.Float64(
			0.5,
		),
		ContentSentimentMin: newscatchergo.Float64(
			-0.5,
		),
		ContentSentimentMax: newscatchergo.Float64(
			0.5,
		),
		IptcTags: newscatchergo.String(
			"20000199,20000209",
		),
		NotIptcTags: newscatchergo.String(
			"20000205,20000209",
		),
		IabTags: newscatchergo.String(
			"Business,Events",
		),
		NotIabTags: newscatchergo.String(
			"Agriculture,Metals",
		),
		CustomTags: newscatchergo.String(
			"Tag1,Tag2",
		),
		RobotsCompliant: newscatchergo.Bool(
			true,
		),
	}
	_, invocationErr := client.Authors.Get(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAuthorsGetWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAuthorsGetWithWireMock", "GET", "/api/authors", map[string]interface{}{"author_name": "Jane Smith", "not_author_name": "John Doe, Jane Doe", "predefined_sources": "top 50 US, top 20 GB", "sources": "nytimes.com,finance.yahoo.com", "not_sources": "cnn.com,wsj.com", "lang": "en,es", "not_lang": "fr,de", "countries": "US,CA", "not_countries": "UK,FR", "from_": "1 day ago", "to_": "1 day ago", "published_date_precision": "full", "by_parse_date": "true", "ranked_only": "true", "from_rank": "100", "to_rank": "100", "is_headline": "true", "is_opinion": "true", "is_paid_content": "false", "parent_url": "wsj.com/politics,wsj.com/tech", "all_links": "https://aiindex.stanford.edu/report,https://www.stateof.ai", "all_domain_links": "who.int,nih.gov", "all_links_text": "Nvidia,Tesla", "word_count_min": "300", "word_count_max": "1000", "page": "2", "page_size": "50", "include_translation_fields": "true", "include_nlp_data": "true", "has_nlp": "true", "theme": "Finance,Tech", "not_theme": "Crime,Sports", "ner_name": "Tesla,Amazon", "title_sentiment_min": "-0.5", "title_sentiment_max": "0.5", "content_sentiment_min": "-0.5", "content_sentiment_max": "0.5", "iptc_tags": "20000199,20000209", "not_iptc_tags": "20000205,20000209", "iab_tags": "Business,Events", "not_iab_tags": "Agriculture,Metals", "custom_tags": "Tag1,Tag2", "robots_compliant": "true"}, 1)
}

func TestAuthorsPostWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithApiKey("test-value"),
	)
	request := &newscatchergo.PostAuthorsRequest{
		AuthorName: "David Muir",
	}
	_, invocationErr := client.Authors.Post(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAuthorsPostWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAuthorsPostWithWireMock", "POST", "/api/authors", nil, 1)
}
