// Code generated by Fern. DO NOT EDIT.

package search_link_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	newscatchergo "github.com/Newscatcher/newscatcher-go"
	client "github.com/Newscatcher/newscatcher-go/client"
	option "github.com/Newscatcher/newscatcher-go/option"
	require "github.com/stretchr/testify/require"
	http "net/http"
	os "os"
	testing "testing"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WiremockAdminURL := "http://localhost:" + wiremockPort + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestSearchLinkSearchUrlGetWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &newscatchergo.SearchUrlGetRequest{
		Ids: newscatchergo.String(
			"5f8d0d55b6e45e00179c6e7e",
		),
		Links: newscatchergo.String(
			"https://nytimes.com/article1",
		),
		Source: newscatchergo.String(
			"articles.id,articles.title,articles.link,articles.published_date",
		),
		From: &newscatchergo.From{
			DateTime: newscatchergo.MustParseDateTime(
				"2024-07-01T00:00:00Z",
			),
		},
		To: &newscatchergo.To{
			DateTime: newscatchergo.MustParseDateTime(
				"2024-01-01T00:00:00Z",
			),
		},
	}
	_, invocationErr := client.SearchLink.SearchUrlGet(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSearchLinkSearchUrlGetWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSearchLinkSearchUrlGetWithWireMock", "GET", "/api/search_by_link", map[string]string{"ids": "5f8d0d55b6e45e00179c6e7e", "links": "https://nytimes.com/article1", "_source": "articles.id,articles.title,articles.link,articles.published_date", "from_": "2024-07-01T00:00:00Z", "to_": "2024-01-01T00:00:00Z"}, 1)
}

func TestSearchLinkSearchUrlPostWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &newscatchergo.SearchUrlPostRequest{
		Links: &newscatchergo.Links{
			String: "https://www.reuters.com/business/energy/oil-prices-up-after-israeli-attacks-oversupply-caps-gains-2025-09-10/",
		},
		Source: newscatchergo.String(
			"articles.id,articles.title,articles.link,articles.canonical_url",
		),
	}
	_, invocationErr := client.SearchLink.SearchUrlPost(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSearchLinkSearchUrlPostWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSearchLinkSearchUrlPostWithWireMock", "POST", "/api/search_by_link", nil, 1)
}
