// Code generated by Fern. DO NOT EDIT.

package sources_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	newscatchergo "github.com/Newscatcher/newscatcher-go"
	client "github.com/Newscatcher/newscatcher-go/client"
	option "github.com/Newscatcher/newscatcher-go/option"
	require "github.com/stretchr/testify/require"
	http "net/http"
	os "os"
	testing "testing"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WiremockAdminURL := "http://localhost:" + wiremockPort + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestSourcesGetWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &newscatchergo.SourcesGetRequest{
		Lang: newscatchergo.String(
			"en",
		),
		Countries: newscatchergo.String(
			"US",
		),
		PredefinedSources: newscatchergo.String(
			"top 100 US, top 5 GB",
		),
		SourceName: newscatchergo.String(
			"sport",
		),
		SourceUrl: newscatchergo.String(
			"bbc.com",
		),
		NewsType: newscatchergo.String(
			"General News Outlets",
		),
	}
	_, invocationErr := client.Sources.Get(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSourcesGetWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSourcesGetWithWireMock", "GET", "/api/sources", map[string]string{"lang": "en", "countries": "US", "predefined_sources": "top 100 US, top 5 GB", "source_name": "sport", "source_url": "bbc.com", "news_type": "General News Outlets"}, 1)
}

func TestSourcesPostWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &newscatchergo.SourcesPostRequest{
		PredefinedSources: &newscatchergo.PredefinedSources{
			String: "top 10 US",
		},
	}
	_, invocationErr := client.Sources.Post(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSourcesPostWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSourcesPostWithWireMock", "POST", "/api/sources", nil, 1)
}
